
var f;f||(f=typeof Module !== 'undefined' ? Module : {});f.Gg||(f.Gg=0);f.Gg++;
(function(a){function b(n,r,u){var t=new XMLHttpRequest;t.open("GET",n,!0);t.responseType="arraybuffer";t.onprogress=function(x){var z=r;x.total&&(z=x.total);if(x.loaded){t.Xf?f.fg[n].loaded=x.loaded:(t.Xf=!0,f.fg||(f.fg={}),f.fg[n]={loaded:x.loaded,total:z});var C=z=x=0,F;for(F in f.fg){var N=f.fg[F];x+=N.total;z+=N.loaded;C++}x=Math.ceil(x*f.Gg/C);f.setStatus&&f.setStatus("Downloading data... ("+z+"/"+x+")")}else!f.fg&&f.setStatus&&f.setStatus("Downloading data...")};t.onerror=function(){throw Error("NetworkError for: "+
n);};t.onload=function(){if(200==t.status||304==t.status||206==t.status||0==t.status&&t.response)u(t.response);else throw Error(t.statusText+" : "+t.responseURL);};t.send(null)}function c(n){console.error("package error:",n)}function d(){function n(x,z,C){this.start=x;this.Ag=z;this.audio=C}function r(x){if(!x)throw"Loading data file failed."+Error().stack;if(!(x instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;x=new Uint8Array(x);n.prototype.lh=x;x=a.files;for(var z=0;z<
x.length;++z)n.prototype.Xf[x[z].filename].onload();f.removeRunDependency("datafile_build/web/index.data")}f.FS_createPath("/","assets",!0,!0);f.FS_createPath("/assets","sounds",!0,!0);f.FS_createPath("/assets","music",!0,!0);n.prototype={Xf:{},open:function(x,z){this.name=z;this.Xf[z]=this;f.addRunDependency("fp "+this.name)},onload:function(){this.kh(this.lh.subarray(this.start,this.Ag))},kh:function(x){f.FS_createDataFile(this.name,null,x,!0,!0,!0);f.removeRunDependency("fp "+this.name);this.Xf[this.name]=
null}};for(var u=a.files,t=0;t<u.length;++t)(new n(u[t].start,u[t].end,u[t].audio)).open("GET",u[t].filename);f.addRunDependency("datafile_build/web/index.data");f.ah||(f.ah={});f.ah["build/web/index.data"]={Mh:!1};m?(r(m),m=null):k=r}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+
"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof f.locateFilePackage||f.locateFile||(f.locateFile=f.locateFilePackage,h("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=f.locateFile?f.locateFile("index.data",""):"index.data",g=a.remote_package_size,k=null,m=f.getPreloadedPackage?f.getPreloadedPackage(e,g):null;m||b(e,g,function(n){k?(k(n),k=null):m=n},
c);f.calledRun?d():(f.preRun||(f.preRun=[]),f.preRun.push(d))})({files:[{filename:"/assets/atlas.dat",start:0,end:484,audio:0},{filename:"/assets/atlas.png",start:484,end:5277,audio:0},{filename:"/assets/sounds/break.ogg",start:5277,end:12593,audio:1},{filename:"/assets/sounds/place.ogg",start:12593,end:18131,audio:1},{filename:"/assets/music/good.ogg",start:18131,end:1882032,audio:1}],remote_package_size:1882032,package_uuid:"57217f18-b110-4547-81e6-a5ef70b28a49"});var aa={},ba;
for(ba in f)f.hasOwnProperty(ba)&&(aa[ba]=f[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}var fa=!1,ha=!1,ia=!1,ja=!1;fa="object"===typeof window;ha="function"===typeof importScripts;ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ja=!fa&&!ia&&!ha;var l="",ka,la,ma,na,oa;
if(ia)l=ha?require("path").dirname(l)+"/":__dirname+"/",ka=function(a,b){na||(na=require("fs"));oa||(oa=require("path"));a=oa.normalize(a);return na.readFileSync(a,b?null:"utf8")},ma=function(a){a=ka(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof pa))throw a;}),process.on("unhandledRejection",
p),ea=function(a){process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(ja)"undefined"!=typeof read&&(ka=function(a){return read(a)}),ma=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||ha)ha?l=self.location.href:document.currentScript&&(l=document.currentScript.src),l=0!==l.indexOf("blob:")?l.substr(0,l.lastIndexOf("/")+1):"",ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(ma=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),la=function(a,
b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var qa=f.print||console.log.bind(console),h=f.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(f[ba]=aa[ba]);aa=null;f.arguments&&(ca=f.arguments);f.thisProgram&&(da=f.thisProgram);f.quit&&(ea=f.quit);
function ra(a){switch(a){case "i1":case "i8":return 1;case "i16":return 2;case "i32":return 4;case "i64":return 8;case "float":return 4;case "double":return 8;default:if("*"===a[a.length-1])return 4;if("i"===a[0]){var b=Number(a.substr(1));assert(0===b%8,"getNativeTypeSize invalid bits "+b+", type "+a);return b/8}return 0}}function sa(a){ta||(ta={});ta[a]||(ta[a]=1,h(a))}var ta;function ua(a,b){b&&b.length?f.dynCall_vi.apply(null,[a].concat(b)):f.dynCall_vi.call(null,a)}var va;f.wasmBinary&&(va=f.wasmBinary);
var noExitRuntime;f.noExitRuntime&&(noExitRuntime=f.noExitRuntime);"object"!==typeof WebAssembly&&p("no native wasm support detected");
function q(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":v[a>>0]=b;break;case "i8":v[a>>0]=b;break;case "i16":wa[a>>1]=b;break;case "i32":w[a>>2]=b;break;case "i64":y=[b>>>0,(A=b,1<=+xa(A)?0<A?(ya(+za(A/4294967296),4294967295)|0)>>>0:~~+Aa((A-+(~~A>>>0))/4294967296)>>>0:0)];w[a>>2]=y[0];w[a+4>>2]=y[1];break;case "float":B[a>>2]=b;break;case "double":Ba[a>>3]=b;break;default:p("invalid type for setValue: "+c)}}
var Ca,Da=new WebAssembly.Table({initial:449,maximum:449,element:"anyfunc"}),Ea=!1;function assert(a,b){a||p("Assertion failed: "+b)}
function Fa(a,b){if("number"===typeof a){var c=!0;var d=a}else c=!1,d=a.length;var e="string"===typeof b?b:null;var g=Ga(Math.max(d,e?1:b.length));if(c){a=g;assert(0==(g&3));for(b=g+(d&-4);a<b;a+=4)w[a>>2]=0;for(b=g+d;a<b;)v[a++>>0]=0;return g}if("i8"===e)return a.subarray||a.slice?D.set(a,g):D.set(new Uint8Array(a),g),g;c=0;for(var k,m,n;c<d;){var r=a[c];k=e||b[c];0===k?c++:("i64"==k&&(k="i32"),q(g+c,r,k),n!==k&&(m=ra(k),n=k),c+=m)}return g}
var Ha="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ja(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ha)return Ha.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function E(a,b){return a?Ja(D,a,b):""}
function Ka(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var m=a.charCodeAt(++g);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function La(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ma(a){var b=La(a)+1,c=Na(b);Ka(a,v,c,b);return c}var Oa,v,D,wa,Pa,w,G,B,Ba;
function Qa(a){Oa=a;f.HEAP8=v=new Int8Array(a);f.HEAP16=wa=new Int16Array(a);f.HEAP32=w=new Int32Array(a);f.HEAPU8=D=new Uint8Array(a);f.HEAPU16=Pa=new Uint16Array(a);f.HEAPU32=G=new Uint32Array(a);f.HEAPF32=B=new Float32Array(a);f.HEAPF64=Ba=new Float64Array(a)}var Ra=f.INITIAL_MEMORY||16777216;f.wasmMemory?Ca=f.wasmMemory:Ca=new WebAssembly.Memory({initial:Ra/65536,maximum:32768});Ca&&(Oa=Ca.buffer);Ra=Oa.byteLength;Qa(Oa);w[10592]=5285408;
function Sa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.Ug;"number"===typeof c?void 0===b.mg?f.dynCall_v(c):f.dynCall_vi(c,b.mg):c(void 0===b.mg?null:b.mg)}}}var Ta=[],Ua=[],Va=[],Wa=[],Xa=!1;function Ya(){var a=f.preRun.shift();Ta.unshift(a)}var xa=Math.abs,Aa=Math.ceil,za=Math.floor,ya=Math.min,Za=0,$a=null,ab=null;function bb(){Za++;f.monitorRunDependencies&&f.monitorRunDependencies(Za)}
function cb(){Za--;f.monitorRunDependencies&&f.monitorRunDependencies(Za);if(0==Za&&(null!==$a&&(clearInterval($a),$a=null),ab)){var a=ab;ab=null;a()}}f.preloadedImages={};f.preloadedAudios={};function p(a){if(f.onAbort)f.onAbort(a);qa(a);h(a);Ea=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function db(a){var b=eb;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}
function fb(){return db("data:application/octet-stream;base64,")}var eb="index.wasm";if(!fb()){var gb=eb;eb=f.locateFile?f.locateFile(gb,l):l+gb}function hb(){try{if(va)return new Uint8Array(va);if(ma)return ma(eb);throw"both async and sync fetching of the wasm failed";}catch(a){p(a)}}
function jb(){return va||!fa&&!ha||"function"!==typeof fetch||db("file://")?new Promise(function(a){a(hb())}):fetch(eb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+eb+"'";return a.arrayBuffer()}).catch(function(){return hb()})}
var A,y,kb={15735:function(){return"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?1:0},15901:function(){return"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?1:0},16127:function(a){var b=f.SDL2;if(a){void 0!==b.capture.lg&&clearTimeout(b.capture.lg);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);
b.capture.stream=void 0}void 0!==b.capture.Wf&&(b.capture.Wf.onaudioprocess=function(){},b.capture.Wf.disconnect(),b.capture.Wf=void 0);void 0!==b.capture.sg&&(b.capture.sg.disconnect(),b.capture.sg=void 0);void 0!==b.capture.yg&&(b.capture.yg=void 0);b.capture=void 0}else void 0!=b.audio.Wf&&(b.audio.Wf.disconnect(),b.audio.Wf=void 0),b.audio=void 0;void 0!==b.Uf&&void 0===b.audio&&void 0===b.capture&&(b.Uf.close(),b.Uf=void 0)},17299:function(a){"undefined"===typeof f.SDL2&&(f.SDL2={});var b=f.SDL2;
a?b.capture={}:b.audio={};b.Uf||("undefined"!==typeof AudioContext?b.Uf=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.Uf=new webkitAudioContext));return void 0===b.Uf?-1:0},17782:function(){return f.SDL2.Uf.sampleRate},17852:function(a,b,c,d){function e(){}function g(m){void 0!==k.capture.lg&&(clearTimeout(k.capture.lg),k.capture.lg=void 0);k.capture.sg=k.Uf.createMediaStreamSource(m);k.capture.Wf=k.Uf.createScriptProcessor(b,a,1);k.capture.Wf.onaudioprocess=function(n){void 0!==k&&
void 0!==k.capture&&(n.outputBuffer.getChannelData(0).fill(0),k.capture.Cg=n.inputBuffer,ua(c,[d]))};k.capture.sg.connect(k.capture.Wf);k.capture.Wf.connect(k.Uf.destination);k.capture.stream=m}var k=f.SDL2;k.capture.yg=k.Uf.createBuffer(a,b,k.Uf.sampleRate);k.capture.yg.getChannelData(0).fill(0);k.capture.lg=setTimeout(function(){k.capture.Cg=k.capture.yg;ua(c,[d])},b/k.Uf.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,
video:!1}).then(g).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},g,e)},19504:function(a,b,c,d){var e=f.SDL2;e.audio.Wf=e.Uf.createScriptProcessor(b,0,a);e.audio.Wf.onaudioprocess=function(g){void 0!==e&&void 0!==e.audio&&(e.audio.Rg=g.outputBuffer,ua(c,[d]))};e.audio.Wf.connect(e.Uf.destination)},19914:function(a,b){for(var c=f.SDL2,d=c.audio.Rg.numberOfChannels,e=0;e<d;++e){var g=c.audio.Rg.getChannelData(e);if(g.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+
g.length+" samples vs expected "+b+" samples!";for(var k=0;k<b;++k)g[k]=B[a+(k*d+e<<2)>>2]}},20394:function(a,b){for(var c=f.SDL2,d=c.capture.Cg.numberOfChannels,e=0;e<d;++e){var g=c.capture.Cg.getChannelData(e);if(g.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";if(1==d)for(var k=0;k<b;++k)q(a+4*k,g[k],"float");else for(k=0;k<b;++k)q(a+4*(k*d+e),g[k],"float")}}};Ua.push({Ug:function(){lb()}});
function mb(a){w[nb()>>2]=a}function ob(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function H(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=ob(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function pb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function qb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function rb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=ob(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var sb=[];function tb(a,b){sb[a]={input:[],output:[],hg:b};ub(a,vb)}
var vb={open:function(a){var b=sb[a.node.rdev];if(!b)throw new I(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.hg.flush(a.tty)},flush:function(a){a.tty.hg.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.hg.Vg)throw new I(60);for(var e=0,g=0;g<d;g++){try{var k=a.tty.hg.Vg(a.tty)}catch(m){throw new I(29);}if(void 0===k&&0===e)throw new I(6);if(null===k||void 0===k)break;e++;b[c+g]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.hg.Lg)throw new I(60);
try{for(var e=0;e<d;e++)a.tty.hg.Lg(a.tty,b[c+e])}catch(g){throw new I(29);}d&&(a.node.timestamp=Date.now());return e}},xb={Vg:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.Xf?Buffer.Xf(256):new Buffer(256),d=0;try{d=na.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=wb(b,!0)}return a.input.shift()},Lg:function(a,b){null===b||10===b?(qa(Ja(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(qa(Ja(a.output,0)),a.output=[])}},yb={Lg:function(a,b){null===b||10===b?(h(Ja(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(h(Ja(a.output,0)),a.output=[])}},J={bg:null,cg:function(){return J.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new I(63);J.bg||(J.bg={dir:{node:{ag:J.Rf.ag,Yf:J.Rf.Yf,lookup:J.Rf.lookup,tg:J.Rf.tg,rename:J.Rf.rename,unlink:J.Rf.unlink,rmdir:J.Rf.rmdir,readdir:J.Rf.readdir,symlink:J.Rf.symlink},stream:{dg:J.Sf.dg}},file:{node:{ag:J.Rf.ag,Yf:J.Rf.Yf},stream:{dg:J.Sf.dg,read:J.Sf.read,write:J.Sf.write,Ng:J.Sf.Ng,ug:J.Sf.ug,wg:J.Sf.wg}},link:{node:{ag:J.Rf.ag,Yf:J.Rf.Yf,readlink:J.Rf.readlink},stream:{}},Qg:{node:{ag:J.Rf.ag,
Yf:J.Rf.Yf},stream:zb}});c=Ab(a,b,c,d);K(c.mode)?(c.Rf=J.bg.dir.node,c.Sf=J.bg.dir.stream,c.Qf={}):32768===(c.mode&61440)?(c.Rf=J.bg.file.node,c.Sf=J.bg.file.stream,c.Tf=0,c.Qf=null):40960===(c.mode&61440)?(c.Rf=J.bg.link.node,c.Sf=J.bg.link.stream):8192===(c.mode&61440)&&(c.Rf=J.bg.Qg.node,c.Sf=J.bg.Qg.stream);c.timestamp=Date.now();a&&(a.Qf[b]=c);return c},Nh:function(a){if(a.Qf&&a.Qf.subarray){for(var b=[],c=0;c<a.Tf;++c)b.push(a.Qf[c]);return b}return a.Qf},Oh:function(a){return a.Qf?a.Qf.subarray?
a.Qf.subarray(0,a.Tf):new Uint8Array(a.Qf):new Uint8Array(0)},Sg:function(a,b){var c=a.Qf?a.Qf.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Qf,a.Qf=new Uint8Array(b),0<a.Tf&&a.Qf.set(c.subarray(0,a.Tf),0))},Ch:function(a,b){if(a.Tf!=b)if(0==b)a.Qf=null,a.Tf=0;else{if(!a.Qf||a.Qf.subarray){var c=a.Qf;a.Qf=new Uint8Array(b);c&&a.Qf.set(c.subarray(0,Math.min(b,a.Tf)))}else if(a.Qf||(a.Qf=[]),a.Qf.length>b)a.Qf.length=b;else for(;a.Qf.length<b;)a.Qf.push(0);a.Tf=
b}},Rf:{ag:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;K(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.Tf:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.oh=4096;b.blocks=Math.ceil(b.size/b.oh);return b},Yf:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&J.Ch(a,
b.size)},lookup:function(){throw Bb[44];},tg:function(a,b,c,d){return J.createNode(a,b,c,d)},rename:function(a,b,c){if(K(a.mode)){try{var d=Cb(b,c)}catch(g){}if(d)for(var e in d.Qf)throw new I(55);}delete a.parent.Qf[a.name];a.name=c;b.Qf[c]=a;a.parent=b},unlink:function(a,b){delete a.Qf[b]},rmdir:function(a,b){var c=Cb(a,b),d;for(d in c.Qf)throw new I(55);delete a.Qf[b]},readdir:function(a){var b=[".",".."],c;for(c in a.Qf)a.Qf.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=J.createNode(a,
b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new I(28);return a.link}},Sf:{read:function(a,b,c,d,e){var g=a.node.Qf;if(e>=a.node.Tf)return 0;a=Math.min(a.node.Tf-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){b.buffer===v.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Qf||a.Qf.subarray)){if(g)return a.Qf=b.subarray(c,c+d),a.Tf=d;if(0===a.Tf&&0===e)return a.Qf=
b.slice(c,c+d),a.Tf=d;if(e+d<=a.Tf)return a.Qf.set(b.subarray(c,c+d),e),d}J.Sg(a,e+d);if(a.Qf.subarray&&b.subarray)a.Qf.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.Qf[e+g]=b[c+g];a.Tf=Math.max(a.Tf,e+d);return d},dg:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Tf);if(0>b)throw new I(28);return b},Ng:function(a,b,c){J.Sg(a.node,b+c);a.node.Tf=Math.max(a.node.Tf,b+c)},ug:function(a,b,c,d,e,g){assert(0===b);if(32768!==(a.node.mode&61440))throw new I(43);a=a.node.Qf;
if(g&2||a.buffer!==Oa){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;c=Ga(c);if(!c)throw new I(48);v.set(a,c)}else d=!1,c=a.byteOffset;return{Ah:c,Bg:d}},wg:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new I(43);if(e&2)return 0;J.Sf.write(a,b,0,d,c,!1);return 0}}},Db=null,Eb={},Fb=[],Gb=1,Hb=null,Ib=!0,Jb={},I=null,Bb={};
function Kb(a,b){a=rb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Tg:!0,Mg:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Mg)throw new I(32);a=ob(a.split("/").filter(function(k){return!!k}),!1);var e=Db;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=Cb(e,a[d]);c=H(c+"/"+a[d]);e.kg&&(!g||g&&b.Tg)&&(e=e.kg.root);if(!g||b.pg)for(g=0;40960===(e.mode&61440);)if(e=Lb(c),c=rb(pb(c),e),e=Kb(c,{Mg:b.Mg}).node,40<g++)throw new I(32);}return{path:c,node:e}}
function Mb(a){for(var b;;){if(a===a.parent)return a=a.cg.Zg,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Nb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Hb.length}function Cb(a,b){var c;if(c=(c=Ob(a,"x"))?c:a.Rf.lookup?0:2)throw new I(c,a);for(c=Hb[Nb(a.id,b)];c;c=c.gg){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Rf.lookup(a,b)}
function Ab(a,b,c,d){a=new Pb(a,b,c,d);b=Nb(a.parent.id,a.name);a.gg=Hb[b];return Hb[b]=a}function K(a){return 16384===(a&61440)}var Qb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Rb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Ob(a,b){if(Ib)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Sb(a,b){try{return Cb(a,b),20}catch(c){}return Ob(a,"wx")}function Tb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Fb[a])return a;throw new I(33);}function Ub(a,b){Vb||(Vb=function(){},Vb.prototype={});var c=new Vb,d;for(d in a)c[d]=a[d];a=c;b=Tb(b);a.fd=b;return Fb[b]=a}
var zb={open:function(a){a.Sf=Eb[a.node.rdev].Sf;a.Sf.open&&a.Sf.open(a)},dg:function(){throw new I(70);}};function ub(a,b){Eb[a]={Sf:b}}function Wb(a,b){var c="/"===b,d=!b;if(c&&Db)throw new I(10);if(!c&&!d){var e=Kb(b,{Tg:!1});b=e.path;e=e.node;if(e.kg)throw new I(10);if(!K(e.mode))throw new I(54);}b={type:a,Th:{},Zg:b,yh:[]};a=a.cg(b);a.cg=b;b.root=a;c?Db=a:e&&(e.kg=b,e.cg&&e.cg.yh.push(b))}
function Xb(a,b,c){var d=Kb(a,{parent:!0}).node;a=qb(a);if(!a||"."===a||".."===a)throw new I(28);var e=Sb(d,a);if(e)throw new I(e);if(!d.Rf.tg)throw new I(63);return d.Rf.tg(d,a,b,c)}function L(a,b){return Xb(a,(void 0!==b?b:511)&1023|16384,0)}function Yb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Xb(a,b|8192,c)}
function Zb(a,b){if(!rb(a))throw new I(44);var c=Kb(b,{parent:!0}).node;if(!c)throw new I(44);b=qb(b);var d=Sb(c,b);if(d)throw new I(d);if(!c.Rf.symlink)throw new I(63);return c.Rf.symlink(c,b,a)}
function $b(a){var b=Kb(a,{parent:!0}).node,c=qb(a),d=Cb(b,c);a:{try{var e=Cb(b,c)}catch(k){e=k.Vf;break a}var g=Ob(b,"wx");e=g?g:K(e.mode)?31:0}if(e)throw new I(e);if(!b.Rf.unlink)throw new I(63);if(d.kg)throw new I(10);try{Jb.willDeletePath&&Jb.willDeletePath(a)}catch(k){h("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+k.message)}b.Rf.unlink(b,c);b=Nb(d.parent.id,d.name);if(Hb[b]===d)Hb[b]=d.gg;else for(b=Hb[b];b;){if(b.gg===d){b.gg=d.gg;break}b=b.gg}try{if(Jb.onDeletePath)Jb.onDeletePath(a)}catch(k){h("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+k.message)}}function Lb(a){a=Kb(a).node;if(!a)throw new I(44);if(!a.Rf.readlink)throw new I(28);return rb(Mb(a.parent),a.Rf.readlink(a))}function ac(a,b){var c;"string"===typeof a?c=Kb(a,{pg:!0}).node:c=a;if(!c.Rf.Yf)throw new I(63);c.Rf.Yf(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function bc(a,b,c,d){if(""===a)throw new I(44);if("string"===typeof b){var e=Qb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=H(a);try{g=Kb(a,{pg:!(b&131072)}).node}catch(m){}}e=!1;if(b&64)if(g){if(b&128)throw new I(20);}else g=Xb(a,c,0),e=!0;if(!g)throw new I(44);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!K(g.mode))throw new I(54);if(!e&&(c=g?40960===(g.mode&61440)?32:K(g.mode)&&
("r"!==Rb(b)||b&512)?31:Ob(g,Rb(b)):44))throw new I(c);if(b&512){c=g;var k;"string"===typeof c?k=Kb(c,{pg:!0}).node:k=c;if(!k.Rf.Yf)throw new I(63);if(K(k.mode))throw new I(31);if(32768!==(k.mode&61440))throw new I(28);if(c=Ob(k,"w"))throw new I(c);k.Rf.Yf(k,{size:0,timestamp:Date.now()})}b&=-131713;d=Ub({node:g,path:Mb(g),flags:b,seekable:!0,position:0,Sf:g.Sf,Eh:[],error:!1},d);d.Sf.open&&d.Sf.open(d);!f.logReadFiles||b&1||(cc||(cc={}),a in cc||(cc[a]=1,h("FS.trackingDelegate error on read file: "+
a)));try{Jb.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),Jb.onOpenFile(a,g))}catch(m){h("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return d}function dc(a){if(null===a.fd)throw new I(8);a.Ig&&(a.Ig=null);try{a.Sf.close&&a.Sf.close(a)}catch(b){throw b;}finally{Fb[a.fd]=null}a.fd=null}
function ec(a,b,c){if(null===a.fd)throw new I(8);if(!a.seekable||!a.Sf.dg)throw new I(70);if(0!=c&&1!=c&&2!=c)throw new I(28);a.position=a.Sf.dg(a,b,c);a.Eh=[]}function fc(a,b,c,d){var e=v;if(0>c||0>d)throw new I(28);if(null===a.fd)throw new I(8);if(1===(a.flags&2097155))throw new I(8);if(K(a.node.mode))throw new I(31);if(!a.Sf.read)throw new I(28);var g="undefined"!==typeof d;if(!g)d=a.position;else if(!a.seekable)throw new I(70);b=a.Sf.read(a,e,b,c,d);g||(a.position+=b);return b}
function hc(a,b,c,d,e,g){if(0>d||0>e)throw new I(28);if(null===a.fd)throw new I(8);if(0===(a.flags&2097155))throw new I(8);if(K(a.node.mode))throw new I(31);if(!a.Sf.write)throw new I(28);a.seekable&&a.flags&1024&&ec(a,0,2);var k="undefined"!==typeof e;if(!k)e=a.position;else if(!a.seekable)throw new I(70);b=a.Sf.write(a,b,c,d,e,g);k||(a.position+=b);try{if(a.path&&Jb.onWriteToFile)Jb.onWriteToFile(a.path)}catch(m){h("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+m.message)}return b}
function ic(){I||(I=function(a,b){this.node=b;this.Dh=function(c){this.Vf=c};this.Dh(a);this.message="FS error"},I.prototype=Error(),I.prototype.constructor=I,[44].forEach(function(a){Bb[a]=new I(a);Bb[a].stack="<generic error, no stack>"}))}var jc;function kc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function lc(a,b,c,d){a=H(("string"===typeof a?a:Mb(a))+"/"+b);return L(a,kc(c,d))}
function mc(a,b){a="string"===typeof a?a:Mb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=H(a+"/"+c);try{L(d)}catch(e){}a=d}}return d}function nc(a,b,c,d){a=H(("string"===typeof a?a:Mb(a))+"/"+b);c=kc(c,d);return Xb(a,(void 0!==c?c:438)&4095|32768,0)}
function oc(a,b,c,d,e,g){a=b?H(("string"===typeof a?a:Mb(a))+"/"+b):a;d=kc(d,e);e=Xb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}ac(e,d|146);a=bc(e,"w");hc(a,c,0,c.length,0,g);dc(a);ac(e,d)}return e}
function pc(a,b,c,d){a=H(("string"===typeof a?a:Mb(a))+"/"+b);b=kc(!!c,!!d);pc.Xg||(pc.Xg=64);var e=pc.Xg++<<8|0;ub(e,{open:function(g){g.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(g,k,m,n){for(var r=0,u=0;u<n;u++){try{var t=c()}catch(x){throw new I(29);}if(void 0===t&&0===r)throw new I(6);if(null===t||void 0===t)break;r++;k[m+u]=t}r&&(g.node.timestamp=Date.now());return r},write:function(g,k,m,n){for(var r=0;r<n;r++)try{d(k[m+r])}catch(u){throw new I(29);}n&&
(g.node.timestamp=Date.now());return r}});return Yb(a,b,e)}function qc(a,b,c){a=H(("string"===typeof a?a:Mb(a))+"/"+b);return Zb(c,a)}
function rc(a){if(a.uh||a.vh||a.link||a.Qf)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ka)try{a.Qf=wb(ka(a.url),!0),a.Tf=a.Qf.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||mb(29);return b}
function sc(a,b,c,d,e){function g(){this.Jg=!1;this.Xf=[]}g.prototype.get=function(u){if(!(u>this.length-1||0>u)){var t=u%this.chunkSize;return this.Wg(u/this.chunkSize|0)[t]}};g.prototype.Ag=function(u){this.Wg=u};g.prototype.Og=function(){var u=new XMLHttpRequest;u.open("HEAD",c,!1);u.send(null);if(!(200<=u.status&&300>u.status||304===u.status))throw Error("Couldn't load "+c+". Status: "+u.status);var t=Number(u.getResponseHeader("Content-length")),x,z=(x=u.getResponseHeader("Accept-Ranges"))&&
"bytes"===x;u=(x=u.getResponseHeader("Content-Encoding"))&&"gzip"===x;var C=1048576;z||(C=t);var F=this;F.Ag(function(N){var ib=N*C,Ia=(N+1)*C-1;Ia=Math.min(Ia,t-1);if("undefined"===typeof F.Xf[N]){var Ee=F.Xf;if(ib>Ia)throw Error("invalid range ("+ib+", "+Ia+") or no bytes requested!");if(Ia>t-1)throw Error("only "+t+" bytes available! programmer error!");var P=new XMLHttpRequest;P.open("GET",c,!1);t!==C&&P.setRequestHeader("Range","bytes="+ib+"-"+Ia);"undefined"!=typeof Uint8Array&&(P.responseType=
"arraybuffer");P.overrideMimeType&&P.overrideMimeType("text/plain; charset=x-user-defined");P.send(null);if(!(200<=P.status&&300>P.status||304===P.status))throw Error("Couldn't load "+c+". Status: "+P.status);ib=void 0!==P.response?new Uint8Array(P.response||[]):wb(P.responseText||"",!0);Ee[N]=ib}if("undefined"===typeof F.Xf[N])throw Error("doXHR failed!");return F.Xf[N]});if(u||!t)C=t=1,C=t=this.Wg(0).length,qa("LazyFiles on gzip forces download of the whole file when length is accessed");this.nh=
t;this.mh=C;this.Jg=!0};if("undefined"!==typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new g;Object.defineProperties(k,{length:{get:function(){this.Jg||this.Og();return this.nh}},chunkSize:{get:function(){this.Jg||this.Og();return this.mh}}});var m=void 0}else m=c,k=void 0;var n=nc(a,b,d,e);k?n.Qf=k:m&&(n.Qf=null,n.url=m);Object.defineProperties(n,{Tf:{get:function(){return this.Qf.length}}});
var r={};Object.keys(n.Sf).forEach(function(u){var t=n.Sf[u];r[u]=function(){if(!rc(n))throw new I(29);return t.apply(null,arguments)}});r.read=function(u,t,x,z,C){if(!rc(n))throw new I(29);u=u.node.Qf;if(C>=u.length)return 0;z=Math.min(u.length-C,z);if(u.slice)for(var F=0;F<z;F++)t[x+F]=u[C+F];else for(F=0;F<z;F++)t[x+F]=u.get(C+F);return z};n.Sf=r;return n}
function tc(a,b,c,d,e,g,k,m,n,r){function u(z){function C(N){r&&r();m||oc(a,b,N,d,e,n);g&&g();cb(x)}var F=!1;f.preloadPlugins.forEach(function(N){!F&&N.canHandle(t)&&(N.handle(z,t,C,function(){k&&k();cb(x)}),F=!0)});F||C(z)}uc();var t=b?rb(H(a+"/"+b)):a,x="cp "+t;bb(x);"string"==typeof c?vc(c,function(z){u(z)},k):u(c)}var M={},Vb,cc,wc={};
function xc(a,b){try{var c=Kb(a,{pg:!0}).node;if(!c)throw new I(44);if(!c.Rf.ag)throw new I(63);var d=c.Rf.ag(c)}catch(e){if(e&&e.node&&H(a)!==H(Mb(e.node)))return-54;throw e;}w[b>>2]=d.dev;w[b+4>>2]=0;w[b+8>>2]=d.ino;w[b+12>>2]=d.mode;w[b+16>>2]=d.nlink;w[b+20>>2]=d.uid;w[b+24>>2]=d.gid;w[b+28>>2]=d.rdev;w[b+32>>2]=0;y=[d.size>>>0,(A=d.size,1<=+xa(A)?0<A?(ya(+za(A/4294967296),4294967295)|0)>>>0:~~+Aa((A-+(~~A>>>0))/4294967296)>>>0:0)];w[b+40>>2]=y[0];w[b+44>>2]=y[1];w[b+48>>2]=4096;w[b+52>>2]=d.blocks;
w[b+56>>2]=d.atime.getTime()/1E3|0;w[b+60>>2]=0;w[b+64>>2]=d.mtime.getTime()/1E3|0;w[b+68>>2]=0;w[b+72>>2]=d.ctime.getTime()/1E3|0;w[b+76>>2]=0;y=[d.ino>>>0,(A=d.ino,1<=+xa(A)?0<A?(ya(+za(A/4294967296),4294967295)|0)>>>0:~~+Aa((A-+(~~A>>>0))/4294967296)>>>0:0)];w[b+80>>2]=y[0];w[b+84>>2]=y[1];return 0}var yc=void 0;function zc(){yc+=4;return w[yc-4>>2]}function Ac(a){a=Fb[a];if(!a)throw new I(8);return a}var Bc;
ia?Bc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?Bc=dateNow:Bc=function(){return performance.now()};function Cc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,g){b.drawArraysInstancedANGLE(c,d,e,g)},a.drawElementsInstanced=function(c,d,e,g,k){b.drawElementsInstancedANGLE(c,d,e,g,k)})}
function Dc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Ec(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
var Fc=1,Gc=[],O=[],Hc=[],Ic=[],Jc=[],Q=[],R=[],Kc=[],Lc=[],S=[],Mc=[],T=[],Nc=[],Oc=[],Pc={},Qc={},Rc={},Sc=4;function U(a){Tc||(Tc=a)}function Uc(a){for(var b=Fc++,c=a.length;c<b;c++)a[c]=null;return b}function Vc(a,b){if(a=1<b.Yg?a.getContext("webgl2",b):a.getContext("webgl",b)){var c=Uc(Lc),d={Ph:c,attributes:b,version:b.Yg,zg:a};a.canvas&&(a.canvas.Gh=d);Lc[c]=d;("undefined"===typeof b.qh||b.qh)&&Wc(d);b=c}else b=0;return b}
function Wc(a){a||(a=V);if(!a.sh){a.sh=!0;var b=a.zg;Cc(b);Dc(b);Ec(b);b.Kh=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Zf=b.getExtension("EXT_disjoint_timer_query");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod EXT_texture_norm16 WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");
(b.getSupportedExtensions()||[]).forEach(function(d){-1!=c.indexOf(d)&&b.getExtension(d)})}}var Xc={},Tc,V,Yc=[];function Zc(a,b,c,d){for(var e=0;e<a;e++){var g=W[c](),k=g&&Uc(d);g?(g.name=k,d[k]=g):U(1282);w[b+4*e>>2]=k}}function $c(a,b,c,d,e,g,k,m){b=O[b];if(a=W[a](b,c))d=m&&Ka(a.name,D,m,d),e&&(w[e>>2]=d),g&&(w[g>>2]=a.size),k&&(w[k>>2]=a.type)}function ad(a,b){G[a>>2]=b;G[a+4>>2]=(b-G[a>>2])/4294967296}
function bd(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&U(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=W.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>V.version){U(1282);return}d=2*(W.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>V.version){U(1280);return}d=33307==a?3:0}if(void 0===d)switch(e=W.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":U(1280);return;case "object":if(null===
e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:U(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:w[b+4*a>>2]=e[a];break;case 2:B[b+4*a>>2]=e[a];break;case 4:v[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(g){U(1280);
h("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:U(1280);h("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:ad(b,d);break;case 0:w[b>>2]=d;break;case 2:B[b>>2]=d;break;case 4:v[b>>0]=d?1:0}}else U(1281)}
function cd(a,b,c,d){if(c){b=W.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:U(1280);return}else if(b instanceof WebGLBuffer)a=b.name|0;else{U(1280);return}break;default:U(1280);return}switch(d){case 1:ad(c,a);break;case 0:w[c>>2]=a;break;case 2:B[c>>2]=a;break;case 4:v[c>>0]=a?1:0;break;default:throw"internal emscriptenWebGLGetIndexed() error, bad type: "+d;}}else U(1281)}
function dd(a){var b=La(a)+1,c=Ga(b);Ka(a,D,c,b);return c}function ed(a,b,c,d){if(c)if(a=W.getUniform(O[a],Q[b]),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:w[c>>2]=a;break;case 2:B[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:w[c+4*b>>2]=a[b];break;case 2:B[c+4*b>>2]=a[b]}else U(1281)}
function fd(a,b,c,d){if(c)if(a=W.getVertexAttrib(a,b),34975==b)w[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:w[c>>2]=a;break;case 2:B[c>>2]=a;break;case 5:w[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:w[c+4*b>>2]=a[b];break;case 2:B[c+4*b>>2]=a[b];break;case 5:w[c+4*b>>2]=Math.fround(a[b])}else U(1281)}function gd(a){a-=5120;return 0==a?v:1==a?D:2==a?wa:4==a?w:6==a?B:5==a||28922==a||28520==a||30779==a||30782==a?G:Pa}
function hd(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}function id(a,b,c,d,e){a=gd(a);var g=hd(a),k=Sc;return a.subarray(e>>g,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<g)+k-1&-k)>>g)}var jd=[],kd=[],ld=null,md=0,nd=null,od=0,pd=0,qd=0,rd=0,sd=[],td={},ud,vd,wd,xd=!1,yd=!1,zd=[];
function uc(){function a(){yd=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}f.preloadPlugins||(f.preloadPlugins=[]);if(!Ad){Ad=!0;try{Bd=!0}catch(c){Bd=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}Cd="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Bd?null:console.log("warning: no BlobBuilder");
Dd="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;f.$g||"undefined"!==typeof Dd||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),f.$g=!0);f.preloadPlugins.push({canHandle:function(c){return!f.$g&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,g){var k=null;if(Bd)try{k=new Blob([c],{type:Ed(d)}),k.size!==c.length&&(k=new Blob([(new Uint8Array(c)).buffer],{type:Ed(d)}))}catch(r){sa("Blob constructor present but fails: "+
r+"; falling back to blob builder")}k||(k=new Cd,k.append((new Uint8Array(c)).buffer),k=k.getBlob());var m=Dd.createObjectURL(k),n=new Image;n.onload=function(){assert(n.complete,"Image "+d+" could not be decoded");var r=document.createElement("canvas");r.width=n.width;r.height=n.height;r.getContext("2d").drawImage(n,0,0);f.preloadedImages[d]=r;Dd.revokeObjectURL(m);e&&e(c)};n.onerror=function(){console.log("Image "+m+" could not be decoded");g&&g()};n.src=m}});f.preloadPlugins.push({canHandle:function(c){return!f.Sh&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,g){function k(t){n||(n=!0,f.preloadedAudios[d]=t,e&&e(c))}function m(){n||(n=!0,f.preloadedAudios[d]=new Audio,g&&g())}var n=!1;if(Bd){try{var r=new Blob([c],{type:Ed(d)})}catch(t){return m()}r=Dd.createObjectURL(r);var u=new Audio;u.addEventListener("canplaythrough",function(){k(u)},!1);u.onerror=function(){if(!n){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var t="",x=0,z=0,
C=0;C<c.length;C++)for(x=x<<8|c[C],z+=8;6<=z;){var F=x>>z-6&63;z-=6;t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[F]}2==z?(t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(x&3)<<4],t+="=="):4==z&&(t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(x&15)<<2],t+="=");u.src="data:audio/x-"+d.substr(-3)+";base64,"+t;k(u)}};u.src=r;Fd(function(){k(u)})}else return m()}});var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&
b.addEventListener("click",function(c){!yd&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Gd(a,b,c,d){if(b&&f.eg&&a==f.canvas)return f.eg;var e;if(b){var g={antialias:!1,alpha:!1,Yg:"undefined"!==typeof WebGL2RenderingContext?2:1};if(d)for(var k in d)g[k]=d[k];if("undefined"!==typeof Xc&&(e=Vc(a,g)))var m=Lc[e].zg}else m=a.getContext("2d");if(!m)return null;c&&(b||assert("undefined"===typeof W,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),f.eg=m,b&&(V=Lc[e],f.eg=W=V&&V.zg),f.Uh=b,zd.forEach(function(n){n()}),uc());return m}
var Hd=!1,Id=void 0,Jd=void 0;
function Kd(a,b){function c(){xd=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Ld,Id&&d.requestPointerLock(),xd=!0,Jd?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=G[SDL.screen>>2]|8388608),Md(f.canvas),Nd()):Md(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),Jd?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=G[SDL.screen>>2]&
-8388609),Md(f.canvas),Nd()):Md(d));if(f.onFullScreen)f.onFullScreen(xd);if(f.onFullscreen)f.onFullscreen(xd)}Id=a;Jd=b;"undefined"===typeof Id&&(Id=!0);"undefined"===typeof Jd&&(Jd=!1);var d=f.canvas;Hd||(Hd=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function Ld(){if(!xd)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Od=0;function Pd(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Od)Od=b+1E3/60;else for(;b+2>=Od;)Od+=1E3/60;setTimeout(a,Math.max(Od-b,0))}}function Fd(a){noExitRuntime=!0;setTimeout(function(){Ea||a()},1E4)}
function Ed(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Qd=0,Rd=0,Sd=0,Td=0;
function Ud(a){if(yd)"mousemove"!=a.type&&"mozMovementX"in a?Sd=Td=0:(Sd=a.movementX||a.mozMovementX||a.webkitMovementX||0,Td=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(Qd=SDL.Qh+Sd,Rd=SDL.Rh+Td):(Qd+=Sd,Rd+=Td);else{var b=f.canvas.getBoundingClientRect(),c=f.canvas.width,d=f.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(g+b.top),e*=c/b.width,a*=d/b.height,Sd=e-Qd,Td=a-Rd,Qd=e,Rd=a)}}function vc(a,b,c){var d="al "+a;la(a,function(e){assert(e,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&cb(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&bb(d)}var Vd=[];function Nd(){var a=f.canvas;Vd.forEach(function(b){b(a.width,a.height)})}function Wd(a,b,c){Md(f.canvas,a,b);c||Nd()}
function Md(a,b,c){b&&c?(a.Fh=b,a.rh=c):(b=a.Fh,c=a.rh);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}Jd?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Ad,Bd,Cd,Dd;
function Xd(a,b){pd=a;qd=b;if(nd)if(0==a)ld=function(){var d=Math.max(0,vd+b-Bc())|0;setTimeout(wd,d)};else if(1==a)ld=function(){Pd(wd)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);ha?(void 0===f.setImmediates&&(f.setImmediates=[]),f.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}ld=function(){setImmediate(wd)}}}
function Yd(a,b,c,d,e){noExitRuntime=!0;assert(!nd,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");nd=a;od=d;var g="undefined"!==typeof d?function(){f.dynCall_vi(a,d)}:function(){f.dynCall_v(a)};var k=md;wd=function(){if(!Ea)if(0<sd.length){var m=Date.now(),n=sd.shift();n.Ug(n.mg);if(ud){var r=ud,u=0==r%1?r-1:Math.floor(r);ud=n.Jh?u:(8*r+(u+.5))/9}console.log('main loop blocker "'+
n.name+'" took '+(Date.now()-m)+" ms");f.setStatus&&(m=f.statusMessage||"Please wait...",n=ud,r=td.Lh,n?n<r?f.setStatus(m+" ("+(r-n)+"/"+r+")"):f.setStatus(m):f.setStatus(""));k<md||setTimeout(wd,0)}else if(!(k<md))if(rd=rd+1|0,1==pd&&1<qd&&0!=rd%qd)ld();else{0==pd&&(vd=Bc());a:if(!(Ea||f.preMainLoop&&!1===f.preMainLoop())){try{g()}catch(t){if(t instanceof pa)break a;t&&"object"===typeof t&&t.stack&&h("exception thrown: "+[t,t.stack]);throw t;}f.postMainLoop&&f.postMainLoop()}k<md||("object"===typeof SDL&&
SDL.audio&&SDL.audio.Bh&&SDL.audio.Bh(),ld())}};e||(b&&0<b?Xd(0,1E3/b):Xd(1,1),ld());if(c)throw"unwind";}var Zd={};function $d(){if(!ae){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Zd)a[b]=Zd[b];var c=[];for(b in a)c.push(b+"="+a[b]);ae=c}return ae}var ae;
function be(a,b,c,d){this.id=a;this.y=this.x=0;this.Hg=!1;this.fh=this.eh=0;this.width=b;this.height=c;this.dh=b;this.bh=c;this.title=d;this.attributes=ce;this.buttons=0;this.keys=[];this.Eg=[];this.Pg=this.rg=this.Fg=this.xg=this.ng=this.og=this.vg=this.qg=this.ih=this.hh=this.jh=this.title=null}function de(a){return 0>=a||!X?null:X[a-1]}
var ee=null,Y=null,X=null,ce=null,fe={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function ge(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 94;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function he(){var a=Y,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function ie(a){Y&&Y.Pg&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||je(Y.Pg,Y.id,a))}function ke(a,b){if(Y){var c=ge(a);if(-1!=c){var d=b&&Y.keys[c];Y.keys[c]=b;Y.Eg[a]=b;Y.rg&&(d&&(b=2),le(Y.rg,Y.id,c,a,b,he()))}}}
function me(){ne()}function oe(){ne()}function pe(a){ke(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function qe(a){ke(a.keyCode,0)}function re(){if(Y)for(var a=0;a<Y.Eg.length;++a)Y.Eg[a]&&ke(a,0)}function se(a){Y&&(Ud(a),a.target==f.canvas&&Y.og&&te(Y.og,Y.id,Qd,Rd))}function ue(a){Y&&a.target==f.canvas&&Y.ng&&je(Y.ng,Y.id,1)}function ve(a){Y&&a.target==f.canvas&&Y.ng&&je(Y.ng,Y.id,0)}
function we(a,b){if(Y&&(Ud(a),a.target==f.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){Y.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else Y.buttons&=~(1<<c);Y.vg&&xe(Y.vg,Y.id,c,b,he())}}function ye(a){Y&&we(a,1)}function ze(a){Y&&we(a,0)}
function Ae(a){switch(a.type){case "DOMMouseScroll":break;case "mousewheel":break;case "wheel":switch(a.deltaMode){case 0:break;case 1:break;case 2:break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}if(Y&&Y.xg&&a.target==f.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;te(Y.xg,Y.id,b,c);a.preventDefault()}}var Be={},Ce=null,De=null;
function ne(){if(rd!==De||!rd){Ce=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;De=rd;for(var a=0;a<Ce.length;++a){var b=Ce[a];if(b){Be[a]||(console.log("glfw joystick connected:",a),Be[a]={id:Fa(wb(b.id),"i8"),Ih:b.buttons.length,Hh:b.axes.length,buttons:Fa(Array(b.buttons.length),"i8"),axes:Fa(Array(4*b.axes.length),"float")});for(var c=Be[a],d=0;d<b.buttons.length;++d)q(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)q(c.axes+
4*d,b.axes[d],"float")}else Be[a]&&(console.log("glfw joystick disconnected",a),Fe(Be[a].id),Fe(Be[a].buttons),Fe(Be[a].axes),delete Be[a])}}}
function Ge(a){function b(m){var n="/.glfw_dropped_files/"+m.name.replace(/\//g,"_"),r=new FileReader;r.onloadend=function(t){if(2!=r.readyState)++g,console.log("failed to read dropped file: "+m.name+": "+r.error);else{var x=new Uint8Array(t.target.result);var z=z||{};z.flags=z.flags||"w";t=bc(n,z.flags,z.mode);if("string"===typeof x){var C=new Uint8Array(La(x)+1);x=Ka(x,C,0,C.length);hc(t,C,0,x,void 0,z.ph)}else if(ArrayBuffer.isView(x))hc(t,x,0,x.byteLength,void 0,z.ph);else throw Error("Unsupported data type");
dc(t);if(++g===e){He(Y.Fg,Y.id,e,c);for(z=0;z<d.length;++z)Fe(d[z]);Fe(c)}}};r.readAsArrayBuffer(m);var u=Fa(wb(n),"i8");d.push(u);q(c+4*k,u,"i8*")}if(Y&&Y.Fg&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=Fa(Array(4*a.dataTransfer.files.length),"i8*"),d=[],e=a.dataTransfer.files.length,g=0;mc("/",".glfw_dropped_files");for(var k=0;k<e;++k)b(a.dataTransfer.files[k]);return!1}}function Ie(a){if(Y&&Y.Fg)return a.preventDefault(),!1}var Je=[];
function Pb(a,b,c,d){a||(a=this);this.parent=a;this.cg=a.cg;this.kg=null;this.id=Gb++;this.name=b;this.mode=c;this.Rf={};this.Sf={};this.rdev=d}Object.defineProperties(Pb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},vh:{get:function(){return K(this.mode)}},uh:{get:function(){return 8192===(this.mode&61440)}}});ic();Hb=Array(4096);
Wb(J,"/");L("/tmp");L("/home");L("/home/web_user");
(function(){L("/dev");ub(259,{read:function(){return 0},write:function(d,e,g,k){return k}});Yb("/dev/null",259);tb(1280,xb);tb(1536,yb);Yb("/dev/tty",1280);Yb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(ia)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){p("random_device")});pc("/dev","random",b);pc("/dev","urandom",b);
L("/dev/shm");L("/dev/shm/tmp")})();L("/proc");L("/proc/self");L("/proc/self/fd");Wb({cg:function(){var a=Ab("/proc/self","fd",16895,73);a.Rf={lookup:function(b,c){var d=Fb[+c];if(!d)throw new I(8);b={parent:null,cg:{Zg:"fake"},Rf:{readlink:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");f.FS_createFolder=lc;f.FS_createPath=mc;f.FS_createDataFile=oc;f.FS_createPreloadedFile=tc;f.FS_createLazyFile=sc;f.FS_createLink=qc;f.FS_createDevice=pc;f.FS_unlink=$b;
for(var W,Z=0;32>Z;++Z)Yc.push(Array(Z));var Ke=new Float32Array(288);for(Z=0;288>Z;++Z)jd[Z]=Ke.subarray(0,Z+1);var Le=new Int32Array(288);for(Z=0;288>Z;++Z)kd[Z]=Le.subarray(0,Z+1);f.requestFullscreen=function(a,b){Kd(a,b)};f.requestAnimationFrame=function(a){Pd(a)};f.setCanvasSize=function(a,b,c){Wd(a,b,c)};f.pauseMainLoop=function(){ld=null;md++};f.resumeMainLoop=function(){md++;var a=pd,b=qd,c=nd;nd=null;Yd(c,0,!1,od,!0);Xd(a,b);ld()};
f.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};f.createContext=function(a,b,c,d){return Gd(a,b,c,d)};function wb(a,b){var c=Array(La(a)+1);a=Ka(a,c,0,c.length);b&&(c.length=a);return c}
var Re={b:function(a,b,c,d){p("Assertion failed: "+E(a)+", at: "+[b?E(b):"unknown filename",c,d?E(d):"unknown function"])},n:function(a,b,c){yc=c;try{var d=Ac(a);switch(b){case 0:var e=zc();return 0>e?-28:bc(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=zc(),d.flags|=e,0;case 12:return e=zc(),wa[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return mb(28),-1;default:return-28}}catch(g){return"undefined"!==typeof M&&g instanceof I||p(g),-g.Vf}},
Aa:function(a,b){try{var c=Ac(a);return xc(c.path,b)}catch(d){return"undefined"!==typeof M&&d instanceof I||p(d),-d.Vf}},Ca:function(a,b,c){yc=c;try{var d=Ac(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=zc();return w[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=zc();if(!d.Sf.th)throw new I(59);return d.Sf.th(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?
0:-59;default:p("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof M&&g instanceof I||p(g),-g.Vf}},Oa:function(a,b,c,d,e,g){try{a:{g<<=12;var k=!1;if(0!==(d&16)&&0!==a%16384)var m=-28;else{if(0!==(d&32)){var n=Me(16384,b);if(!n){m=-48;break a}Ne(n,0,b);k=!0}else{var r=Fb[e];if(!r){m=-8;break a}var u=g;if(0!==(c&2)&&0===(d&2)&&2!==(r.flags&2097155))throw new I(2);if(1===(r.flags&2097155))throw new I(2);if(!r.Sf.ug)throw new I(43);var t=r.Sf.ug(r,a,b,u,c,d);n=t.Ah;k=t.Bg}wc[n]={xh:n,wh:b,
Bg:k,fd:e,zh:c,flags:d,offset:g};m=n}}return m}catch(x){return"undefined"!==typeof M&&x instanceof I||p(x),-x.Vf}},Za:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=wc[a];if(d&&b===d.wh){var e=Fb[d.fd];if(d.zh&2){var g=d.flags,k=d.offset,m=D.slice(a,a+b);e&&e.Sf.wg&&e.Sf.wg(e,m,k,b,g)}wc[a]=null;d.Bg&&Fe(d.xh)}c=0}return c}catch(n){return"undefined"!==typeof M&&n instanceof I||p(n),-n.Vf}},o:function(a,b,c){yc=c;try{var d=E(a),e=zc();return bc(d,b,e).fd}catch(g){return"undefined"!==typeof M&&
g instanceof I||p(g),-g.Vf}},ya:function(a,b,c){try{var d=Ac(a);return fc(d,b,c)}catch(e){return"undefined"!==typeof M&&e instanceof I||p(e),-e.Vf}},za:function(a,b){try{return a=E(a),xc(a,b)}catch(c){return"undefined"!==typeof M&&c instanceof I||p(c),-c.Vf}},Da:function(){},ua:function(){p()},j:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Bc();else return mb(28),-1;w[b>>2]=a/1E3|0;w[b+4>>2]=a%1E3*1E6|0;return 0},c:function(a,b,c){Je.length=0;var d;for(c>>=2;d=D[b++];)Je.push(105>d?
Ba[++c>>1]:w[c]),++c;return kb[a].apply(null,Je)},_:function(a){W.activeTexture(a)},Z:function(a,b){W.attachShader(O[a],R[b])},uc:function(a,b){W.beginQuery(a,Mc[b])},pa:function(a,b){W.Zf.beginQueryEXT(a,S[b])},$b:function(a){W.beginTransformFeedback(a)},Y:function(a,b,c){W.bindAttribLocation(O[a],b,E(c))},W:function(a,b){35051==a?W.Dg=b:35052==a&&(W.$f=b);W.bindBuffer(a,Gc[b])},Yb:function(a,b,c){W.bindBufferBase(a,b,Gc[c])},Zb:function(a,b,c,d,e){W.bindBufferRange(a,b,Gc[c],d,e)},V:function(a,
b){W.bindFramebuffer(a,Hc[b])},U:function(a,b){W.bindRenderbuffer(a,Ic[b])},cb:function(a,b){W.bindSampler(a,T[b])},T:function(a,b){W.bindTexture(a,Jc[b])},Va:function(a,b){W.bindTransformFeedback(a,Nc[b])},ec:function(a){W.bindVertexArray(Kc[a])},ha:function(a){W.bindVertexArray(Kc[a])},S:function(a,b,c,d){W.blendColor(a,b,c,d)},R:function(a){W.blendEquation(a)},Q:function(a,b){W.blendEquationSeparate(a,b)},P:function(a,b){W.blendFunc(a,b)},O:function(a,b,c,d){W.blendFuncSeparate(a,b,c,d)},ic:function(a,
b,c,d,e,g,k,m,n,r){W.blitFramebuffer(a,b,c,d,e,g,k,m,n,r)},N:function(a,b,c,d){2<=V.version?c?W.bufferData(a,D,d,c,b):W.bufferData(a,b,d):W.bufferData(a,c?D.subarray(c,c+b):b,d)},L:function(a,b,c,d){2<=V.version?W.bufferSubData(a,b,D,d,c):W.bufferSubData(a,b,D.subarray(d,d+c))},K:function(a){return W.checkFramebufferStatus(a)},J:function(a){W.clear(a)},zb:function(a,b,c,d){W.clearBufferfi(a,b,c,d)},Ab:function(a,b,c){W.clearBufferfv(a,b,B,c>>2)},Cb:function(a,b,c){W.clearBufferiv(a,b,w,c>>2)},Bb:function(a,
b,c){W.clearBufferuiv(a,b,G,c>>2)},I:function(a,b,c,d){W.clearColor(a,b,c,d)},H:function(a){W.clearDepth(a)},G:function(a){W.clearStencil(a)},lb:function(a,b,c,d){return W.clientWaitSync(Oc[a],b,(c>>>0)+4294967296*d)},F:function(a,b,c,d){W.colorMask(!!a,!!b,!!c,!!d)},E:function(a){W.compileShader(R[a])},D:function(a,b,c,d,e,g,k,m){2<=V.version?W.$f?W.compressedTexImage2D(a,b,c,d,e,g,k,m):W.compressedTexImage2D(a,b,c,d,e,g,D,m,k):W.compressedTexImage2D(a,b,c,d,e,g,m?D.subarray(m,m+k):null)},zc:function(a,
b,c,d,e,g,k,m,n){W.$f?W.compressedTexImage3D(a,b,c,d,e,g,k,m,n):W.compressedTexImage3D(a,b,c,d,e,g,k,D,n,m)},C:function(a,b,c,d,e,g,k,m,n){2<=V.version?W.$f?W.compressedTexSubImage2D(a,b,c,d,e,g,k,m,n):W.compressedTexSubImage2D(a,b,c,d,e,g,k,D,n,m):W.compressedTexSubImage2D(a,b,c,d,e,g,k,n?D.subarray(n,n+m):null)},yc:function(a,b,c,d,e,g,k,m,n,r,u){W.$f?W.compressedTexSubImage3D(a,b,c,d,e,g,k,m,n,r,u):W.compressedTexSubImage3D(a,b,c,d,e,g,k,m,n,D,u,r)},xb:function(a,b,c,d,e){W.copyBufferSubData(a,
b,c,d,e)},A:function(a,b,c,d,e,g,k,m){W.copyTexImage2D(a,b,c,d,e,g,k,m)},z:function(a,b,c,d,e,g,k,m){W.copyTexSubImage2D(a,b,c,d,e,g,k,m)},Ac:function(a,b,c,d,e,g,k,m,n){W.copyTexSubImage3D(a,b,c,d,e,g,k,m,n)},y:function(){var a=Uc(O),b=W.createProgram();b.name=a;O[a]=b;return a},x:function(a){var b=Uc(R);R[b]=W.createShader(a);return b},w:function(a){W.cullFace(a)},v:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Gc[d];e&&(W.deleteBuffer(e),e.name=0,Gc[d]=null,d==W.Dg&&(W.Dg=0),d==W.$f&&
(W.$f=0))}},u:function(a,b){for(var c=0;c<a;++c){var d=w[b+4*c>>2],e=Hc[d];e&&(W.deleteFramebuffer(e),e.name=0,Hc[d]=null)}},t:function(a){if(a){var b=O[a];b?(W.deleteProgram(b),b.name=0,O[a]=null,Pc[a]=null):U(1281)}},wc:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Mc[d];e&&(W.deleteQuery(e),Mc[d]=null)}},ra:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=S[d];e&&(W.Zf.deleteQueryEXT(e),S[d]=null)}},s:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Ic[d];e&&(W.deleteRenderbuffer(e),
e.name=0,Ic[d]=null)}},eb:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=T[d];e&&(W.deleteSampler(e),e.name=0,T[d]=null)}},r:function(a){if(a){var b=R[a];b?(W.deleteShader(b),R[a]=null):U(1281)}},mb:function(a){if(a){var b=Oc[a];b?(W.deleteSync(b),b.name=0,Oc[a]=null):U(1281)}},Xe:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Jc[d];e&&(W.deleteTexture(e),e.name=0,Jc[d]=null)}},Ua:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Nc[d];e&&(W.deleteTransformFeedback(e),e.name=
0,Nc[d]=null)}},dc:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2];W.deleteVertexArray(Kc[d]);Kc[d]=null}},fa:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2];W.deleteVertexArray(Kc[d]);Kc[d]=null}},We:function(a){W.depthFunc(a)},Ve:function(a){W.depthMask(!!a)},Ue:function(a,b){W.depthRange(a,b)},Te:function(a,b){W.detachShader(O[a],R[b])},Se:function(a){W.disable(a)},Re:function(a){W.disableVertexAttribArray(a)},Qe:function(a,b,c){W.drawArrays(a,b,c)},qb:function(a,b,c,d){W.drawArraysInstanced(a,
b,c,d)},ba:function(a,b,c,d){W.drawArraysInstanced(a,b,c,d)},Kc:function(a,b,c,d){W.drawArraysInstanced(a,b,c,d)},Lc:function(a,b,c,d){W.drawArraysInstanced(a,b,c,d)},Fa:function(a,b,c,d){W.drawArraysInstanced(a,b,c,d)},pc:function(a,b){for(var c=Yc[a],d=0;d<a;d++)c[d]=w[b+4*d>>2];W.drawBuffers(c)},Gc:function(a,b){for(var c=Yc[a],d=0;d<a;d++)c[d]=w[b+4*d>>2];W.drawBuffers(c)},ca:function(a,b){for(var c=Yc[a],d=0;d<a;d++)c[d]=w[b+4*d>>2];W.drawBuffers(c)},Pe:function(a,b,c,d){W.drawElements(a,b,c,
d)},pb:function(a,b,c,d,e){W.drawElementsInstanced(a,b,c,d,e)},aa:function(a,b,c,d,e){W.drawElementsInstanced(a,b,c,d,e)},Hc:function(a,b,c,d,e){W.drawElementsInstanced(a,b,c,d,e)},Ic:function(a,b,c,d,e){W.drawElementsInstanced(a,b,c,d,e)},Jc:function(a,b,c,d,e){W.drawElementsInstanced(a,b,c,d,e)},Ec:function(a,b,c,d,e,g){W.drawElements(a,d,e,g)},Oe:function(a){W.enable(a)},Me:function(a){W.enableVertexAttribArray(a)},tc:function(a){W.endQuery(a)},oa:function(a){W.Zf.endQueryEXT(a)},_b:function(){W.endTransformFeedback()},
ob:function(a,b){return(a=W.fenceSync(a,b))?(b=Uc(Oc),a.name=b,Oc[b]=a,b):0},Le:function(){W.finish()},Ke:function(){W.flush()},Je:function(a,b,c,d){W.framebufferRenderbuffer(a,b,c,Ic[d])},Ie:function(a,b,c,d,e){W.framebufferTexture2D(a,b,c,Jc[d],e)},fc:function(a,b,c,d,e){W.framebufferTextureLayer(a,b,Jc[c],d,e)},He:function(a){W.frontFace(a)},Ge:function(a,b){Zc(a,b,"createBuffer",Gc)},Ee:function(a,b){Zc(a,b,"createFramebuffer",Hc)},xc:function(a,b){Zc(a,b,"createQuery",Mc)},sa:function(a,b){for(var c=
0;c<a;c++){var d=W.Zf.createQueryEXT();if(!d){for(U(1282);c<a;)w[b+4*c++>>2]=0;break}var e=Uc(S);d.name=e;S[e]=d;w[b+4*c>>2]=e}},De:function(a,b){Zc(a,b,"createRenderbuffer",Ic)},fb:function(a,b){Zc(a,b,"createSampler",T)},Be:function(a,b){Zc(a,b,"createTexture",Jc)},Ta:function(a,b){Zc(a,b,"createTransformFeedback",Nc)},cc:function(a,b){Zc(a,b,"createVertexArray",Kc)},ea:function(a,b){Zc(a,b,"createVertexArray",Kc)},Fe:function(a){W.generateMipmap(a)},Ae:function(a,b,c,d,e,g,k){$c("getActiveAttrib",
a,b,c,d,e,g,k)},ze:function(a,b,c,d,e,g,k){$c("getActiveUniform",a,b,c,d,e,g,k)},sb:function(a,b,c,d,e){a=O[a];if(a=W.getActiveUniformBlockName(a,b))e&&0<c?(c=Ka(a,D,e,c),d&&(w[d>>2]=c)):d&&(w[d>>2]=0)},tb:function(a,b,c,d){if(d)switch(a=O[a],c){case 35393:a=W.getActiveUniformBlockName(a,b);w[d>>2]=a.length+1;break;default:if(a=W.getActiveUniformBlockParameter(a,b,c))if("number"==typeof a)w[d>>2]=a;else for(b=0;b<a.length;b++)w[d+4*b>>2]=a[b]}else U(1281)},vb:function(a,b,c,d,e){if(e)if(0<b&&0==c)U(1281);
else{a=O[a];for(var g=[],k=0;k<b;k++)g.push(w[c+4*k>>2]);if(a=W.getActiveUniforms(a,g,d))for(b=a.length,k=0;k<b;k++)w[e+4*k>>2]=a[k]}else U(1281)},ye:function(a,b,c,d){a=W.getAttachedShaders(O[a]);var e=a.length;e>b&&(e=b);w[c>>2]=e;for(b=0;b<e;++b)w[d+4*b>>2]=R.indexOf(a[b])},xe:function(a,b){return W.getAttribLocation(O[a],E(b))},we:function(a,b){bd(a,b,4)},gb:function(a,b,c){c?ad(c,W.getBufferParameter(a,b)):U(1281)},ve:function(a,b,c){c?w[c>>2]=W.getBufferParameter(a,b):U(1281)},ue:function(){var a=
W.getError()||Tc;Tc=0;return a},te:function(a,b){bd(a,b,2)},Lb:function(a,b){return W.getFragDataLocation(O[a],E(b))},se:function(a,b,c,d){a=W.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;w[d>>2]=a},hb:function(a,b,c){cd(a,b,c,1)},jb:function(a,b){bd(a,b,1)},ac:function(a,b,c){cd(a,b,c,0)},re:function(a,b){bd(a,b,0)},Ha:function(a,b,c,d,e){if(0>d)U(1281);else if(e){if(a=W.getInternalformatParameter(a,b,c),null!==a)for(b=0;b<a.length&&
b<d;++b)w[e+b>>2]=a[b]}else U(1281)},Pa:function(){U(1282)},pe:function(a,b,c,d){a=W.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?Ka(a,D,d,b):0;c&&(w[c>>2]=b)},qe:function(a,b,c){if(c)if(a>=Fc)U(1281);else{var d=Pc[a];if(d)if(35716==b)a=W.getProgramInfoLog(O[a]),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(35719==b)w[c>>2]=d.Kg;else if(35722==b){if(-1==d.ig){a=O[a];var e=W.getProgramParameter(a,35721);for(b=d.ig=0;b<e;++b)d.ig=Math.max(d.ig,W.getActiveAttrib(a,b).name.length+
1)}w[c>>2]=d.ig}else if(35381==b){if(-1==d.jg)for(a=O[a],e=W.getProgramParameter(a,35382),b=d.jg=0;b<e;++b)d.jg=Math.max(d.jg,W.getActiveUniformBlockName(a,b).length+1);w[c>>2]=d.jg}else w[c>>2]=W.getProgramParameter(O[a],b);else U(1282)}else U(1281)},ja:function(a,b,c){if(c){a=W.Zf.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;ad(c,d)}else U(1281)},la:function(a,b,c){if(c){a=W.Zf.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>2]=d}else U(1281)},ia:function(a,
b,c){if(c){a=W.Zf.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;ad(c,d)}else U(1281)},qc:function(a,b,c){if(c){a=W.getQueryParameter(Mc[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>2]=d}else U(1281)},ka:function(a,b,c){if(c){a=W.Zf.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>2]=d}else U(1281)},sc:function(a,b,c){c?w[c>>2]=W.getQuery(a,b):U(1281)},ma:function(a,b,c){c?w[c>>2]=W.Zf.getQueryEXT(a,b):U(1281)},oe:function(a,b,c){c?w[c>>2]=W.getRenderbufferParameter(a,
b):U(1281)},Xa:function(a,b,c){c?(a=T[a],B[c>>2]=W.getSamplerParameter(a,b)):U(1281)},Ya:function(a,b,c){c?(a=T[a],w[c>>2]=W.getSamplerParameter(a,b)):U(1281)},me:function(a,b,c,d){a=W.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?Ka(a,D,d,b):0;c&&(w[c>>2]=b)},le:function(a,b,c,d){a=W.getShaderPrecisionFormat(a,b);w[c>>2]=a.rangeMin;w[c+4>>2]=a.rangeMax;w[d>>2]=a.precision},ke:function(a,b,c,d){if(a=W.getShaderSource(R[a]))b=0<b&&d?Ka(a,D,d,b):0,c&&(w[c>>2]=b)},ne:function(a,b,c){c?
35716==b?(a=W.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1):35720==b?(a=W.getShaderSource(R[a]),w[c>>2]=null===a||0==a.length?0:a.length+1):w[c>>2]=W.getShaderParameter(R[a],b):U(1281)},je:function(a){if(Qc[a])return Qc[a];switch(a){case 7939:var b=W.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=dd(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=W.getParameter(a))||U(1280);b=dd(b);break;case 7938:b=W.getParameter(7938);b=
2<=V.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=dd(b);break;case 35724:b=W.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=dd(b);break;default:return U(1280),0}return Qc[a]=b},yb:function(a,b){if(2>V.version)return U(1282),0;var c=Rc[a];if(c)return 0>b||b>=c.length?(U(1281),0):c[b];switch(a){case 7939:return c=W.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+
d})),c=c.map(function(d){return dd(d)}),c=Rc[a]=c,0>b||b>=c.length?(U(1281),0):c[b];default:return U(1280),0}},ib:function(a,b,c,d,e){0>c?U(1281):e?(a=W.getSyncParameter(Oc[a],b),w[d>>2]=a,null!==a&&d&&(w[d>>2]=1)):U(1281)},ie:function(a,b,c){c?B[c>>2]=W.getTexParameter(a,b):U(1281)},ge:function(a,b,c){c?w[c>>2]=W.getTexParameter(a,b):U(1281)},Vb:function(a,b,c,d,e,g,k){a=O[a];if(a=W.getTransformFeedbackVarying(a,b))k&&0<c?(c=Ka(a.name,D,k,c),d&&(w[d>>2]=c)):d&&(w[d>>2]=0),e&&(w[e>>2]=a.size),g&&
(w[g>>2]=a.type)},ub:function(a,b){return W.getUniformBlockIndex(O[a],E(b))},wb:function(a,b,c,d){if(d)if(0<b&&(0==c||0==d))U(1281);else{a=O[a];for(var e=[],g=0;g<b;g++)e.push(E(w[c+4*g>>2]));if(a=W.getUniformIndices(a,e))for(b=a.length,g=0;g<b;g++)w[d+4*g>>2]=a[g]}else U(1281)},de:function(a,b){b=E(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=Pc[a]&&Pc[a].gh[b])&&0<=c&&c<a[0]?a[1]+c:-1},fe:function(a,b,c){ed(a,b,c,2)},ee:function(a,
b,c){ed(a,b,c,0)},Nb:function(a,b,c){ed(a,b,c,0)},Tb:function(a,b,c){fd(a,b,c,0)},Sb:function(a,b,c){fd(a,b,c,0)},ae:function(a,b,c){c?w[c>>2]=W.getVertexAttribOffset(a,b):U(1281)},ce:function(a,b,c){fd(a,b,c,2)},be:function(a,b,c){fd(a,b,c,5)},$d:function(a,b){W.hint(a,b)},La:function(a,b,c){for(var d=Yc[b],e=0;e<b;e++)d[e]=w[c+4*e>>2];W.invalidateFramebuffer(a,d)},Ka:function(a,b,c,d,e,g,k){for(var m=Yc[b],n=0;n<b;n++)m[n]=w[c+4*n>>2];W.invalidateSubFramebuffer(a,m,d,e,g,k)},_d:function(a){return(a=
Gc[a])?W.isBuffer(a):0},Zd:function(a){return W.isEnabled(a)},Xd:function(a){return(a=Hc[a])?W.isFramebuffer(a):0},Wd:function(a){return(a=O[a])?W.isProgram(a):0},vc:function(a){return(a=Mc[a])?W.isQuery(a):0},qa:function(a){return(a=S[a])?W.Zf.isQueryEXT(a):0},Vd:function(a){return(a=Ic[a])?W.isRenderbuffer(a):0},db:function(a){return(a=T[a])?W.isSampler(a):0},Ud:function(a){return(a=R[a])?W.isShader(a):0},nb:function(a){return W.isSync(Oc[a])},Td:function(a){return(a=Jc[a])?W.isTexture(a):0},Sa:function(a){return W.isTransformFeedback(Nc[a])},
bc:function(a){return(a=Kc[a])?W.isVertexArray(a):0},da:function(a){return(a=Kc[a])?W.isVertexArray(a):0},Sd:function(a){W.lineWidth(a)},Rd:function(a){W.linkProgram(O[a]);var b=O[a];a=Pc[a]={gh:{},Kg:0,ig:-1,jg:-1};for(var c=a.gh,d=W.getProgramParameter(b,35718),e=0;e<d;++e){var g=W.getActiveUniform(b,e),k=g.name;a.Kg=Math.max(a.Kg,k.length+1);"]"==k.slice(-1)&&(k=k.slice(0,k.lastIndexOf("[")));var m=W.getUniformLocation(b,k);if(m){var n=Uc(Q);c[k]=[g.size,n];Q[n]=m;for(var r=1;r<g.size;++r)m=W.getUniformLocation(b,
k+"["+r+"]"),n=Uc(Q),Q[n]=m}}},Ra:function(){W.pauseTransformFeedback()},Qd:function(a,b){3317==a&&(Sc=b);W.pixelStorei(a,b)},Pd:function(a,b){W.polygonOffset(a,b)},Na:function(){U(1280)},Ma:function(){U(1280)},na:function(a,b){W.Zf.queryCounterEXT(S[a],b)},Fc:function(a){W.readBuffer(a)},Od:function(a,b,c,d,e,g,k){if(2<=V.version)if(W.Dg)W.readPixels(a,b,c,d,e,g,k);else{var m=gd(g);W.readPixels(a,b,c,d,e,g,m,k>>hd(m))}else(k=id(g,e,c,d,k))?W.readPixels(a,b,c,d,e,g,k):U(1280)},Nd:function(){},Md:function(a,
b,c,d){W.renderbufferStorage(a,b,c,d)},hc:function(a,b,c,d,e){W.renderbufferStorageMultisample(a,b,c,d,e)},Qa:function(){W.resumeTransformFeedback()},Ld:function(a,b){W.sampleCoverage(a,!!b)},$a:function(a,b,c){W.samplerParameterf(T[a],b,c)},_a:function(a,b,c){W.samplerParameterf(T[a],b,B[c>>2])},bb:function(a,b,c){W.samplerParameteri(T[a],b,c)},ab:function(a,b,c){W.samplerParameteri(T[a],b,w[c>>2])},Kd:function(a,b,c,d){W.scissor(a,b,c,d)},Jd:function(){U(1280)},Id:function(a,b,c,d){for(var e="",
g=0;g<b;++g){var k=d?w[d+4*g>>2]:-1;e+=E(w[c+4*g>>2],0>k?void 0:k)}W.shaderSource(R[a],e)},Hd:function(a,b,c){W.stencilFunc(a,b,c)},Gd:function(a,b,c,d){W.stencilFuncSeparate(a,b,c,d)},Fd:function(a){W.stencilMask(a)},Ed:function(a,b){W.stencilMaskSeparate(a,b)},Cd:function(a,b,c){W.stencilOp(a,b,c)},Bd:function(a,b,c,d){W.stencilOpSeparate(a,b,c,d)},Ad:function(a,b,c,d,e,g,k,m,n){if(2<=V.version)if(W.$f)W.texImage2D(a,b,c,d,e,g,k,m,n);else if(n){var r=gd(m);W.texImage2D(a,b,c,d,e,g,k,m,r,n>>hd(r))}else W.texImage2D(a,
b,c,d,e,g,k,m,null);else W.texImage2D(a,b,c,d,e,g,k,m,n?id(m,k,d,e,n):null)},Dc:function(a,b,c,d,e,g,k,m,n,r){if(W.$f)W.texImage3D(a,b,c,d,e,g,k,m,n,r);else if(r){var u=gd(n);W.texImage3D(a,b,c,d,e,g,k,m,n,u,r>>hd(u))}else W.texImage3D(a,b,c,d,e,g,k,m,n,null)},zd:function(a,b,c){W.texParameterf(a,b,c)},yd:function(a,b,c){W.texParameterf(a,b,B[c>>2])},xd:function(a,b,c){W.texParameteri(a,b,c)},wd:function(a,b,c){W.texParameteri(a,b,w[c>>2])},Ja:function(a,b,c,d,e){W.texStorage2D(a,b,c,d,e)},Ia:function(a,
b,c,d,e,g){W.texStorage3D(a,b,c,d,e,g)},vd:function(a,b,c,d,e,g,k,m,n){if(2<=V.version)if(W.$f)W.texSubImage2D(a,b,c,d,e,g,k,m,n);else if(n){var r=gd(m);W.texSubImage2D(a,b,c,d,e,g,k,m,r,n>>hd(r))}else W.texSubImage2D(a,b,c,d,e,g,k,m,null);else r=null,n&&(r=id(m,k,e,g,n)),W.texSubImage2D(a,b,c,d,e,g,k,m,r)},Bc:function(a,b,c,d,e,g,k,m,n,r,u){if(W.$f)W.texSubImage3D(a,b,c,d,e,g,k,m,n,r,u);else if(u){var t=gd(r);W.texSubImage3D(a,b,c,d,e,g,k,m,n,r,t,u>>hd(t))}else W.texSubImage3D(a,b,c,d,e,g,k,m,n,
r,null)},Wb:function(a,b,c,d){a=O[a];for(var e=[],g=0;g<b;g++)e.push(E(w[c+4*g>>2]));W.transformFeedbackVaryings(a,e,d)},ud:function(a,b){W.uniform1f(Q[a],b)},td:function(a,b,c){if(2<=V.version)W.uniform1fv(Q[a],B,c>>2,b);else{if(288>=b)for(var d=jd[b-1],e=0;e<b;++e)d[e]=B[c+4*e>>2];else d=B.subarray(c>>2,c+4*b>>2);W.uniform1fv(Q[a],d)}},rd:function(a,b){W.uniform1i(Q[a],b)},qd:function(a,b,c){if(2<=V.version)W.uniform1iv(Q[a],w,c>>2,b);else{if(288>=b)for(var d=kd[b-1],e=0;e<b;++e)d[e]=w[c+4*e>>2];
else d=w.subarray(c>>2,c+4*b>>2);W.uniform1iv(Q[a],d)}},Kb:function(a,b){W.uniform1ui(Q[a],b)},Gb:function(a,b,c){W.uniform1uiv(Q[a],G,c>>2,b)},pd:function(a,b,c){W.uniform2f(Q[a],b,c)},od:function(a,b,c){if(2<=V.version)W.uniform2fv(Q[a],B,c>>2,2*b);else{if(144>=b)for(var d=jd[2*b-1],e=0;e<2*b;e+=2)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2];else d=B.subarray(c>>2,c+8*b>>2);W.uniform2fv(Q[a],d)}},nd:function(a,b,c){W.uniform2i(Q[a],b,c)},md:function(a,b,c){if(2<=V.version)W.uniform2iv(Q[a],w,c>>2,2*
b);else{if(144>=b)for(var d=kd[2*b-1],e=0;e<2*b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2];else d=w.subarray(c>>2,c+8*b>>2);W.uniform2iv(Q[a],d)}},Jb:function(a,b,c){W.uniform2ui(Q[a],b,c)},Fb:function(a,b,c){W.uniform2uiv(Q[a],G,c>>2,2*b)},ld:function(a,b,c,d){W.uniform3f(Q[a],b,c,d)},kd:function(a,b,c){if(2<=V.version)W.uniform3fv(Q[a],B,c>>2,3*b);else{if(96>=b)for(var d=jd[3*b-1],e=0;e<3*b;e+=3)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2],d[e+2]=B[c+(4*e+8)>>2];else d=B.subarray(c>>2,c+12*b>>2);W.uniform3fv(Q[a],
d)}},jd:function(a,b,c,d){W.uniform3i(Q[a],b,c,d)},id:function(a,b,c){if(2<=V.version)W.uniform3iv(Q[a],w,c>>2,3*b);else{if(96>=b)for(var d=kd[3*b-1],e=0;e<3*b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2];else d=w.subarray(c>>2,c+12*b>>2);W.uniform3iv(Q[a],d)}},Ib:function(a,b,c,d){W.uniform3ui(Q[a],b,c,d)},Eb:function(a,b,c){W.uniform3uiv(Q[a],G,c>>2,3*b)},gd:function(a,b,c,d,e){W.uniform4f(Q[a],b,c,d,e)},fd:function(a,b,c){if(2<=V.version)W.uniform4fv(Q[a],B,c>>2,4*b);else{if(72>=
b){var d=jd[4*b-1],e=B;c>>=2;for(var g=0;g<4*b;g+=4){var k=c+g;d[g]=e[k];d[g+1]=e[k+1];d[g+2]=e[k+2];d[g+3]=e[k+3]}}else d=B.subarray(c>>2,c+16*b>>2);W.uniform4fv(Q[a],d)}},ed:function(a,b,c,d,e){W.uniform4i(Q[a],b,c,d,e)},dd:function(a,b,c){if(2<=V.version)W.uniform4iv(Q[a],w,c>>2,4*b);else{if(72>=b)for(var d=kd[4*b-1],e=0;e<4*b;e+=4)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2],d[e+3]=w[c+(4*e+12)>>2];else d=w.subarray(c>>2,c+16*b>>2);W.uniform4iv(Q[a],d)}},Hb:function(a,b,c,d,
e){W.uniform4ui(Q[a],b,c,d,e)},Db:function(a,b,c){W.uniform4uiv(Q[a],G,c>>2,4*b)},rb:function(a,b,c){a=O[a];W.uniformBlockBinding(a,b,c)},cd:function(a,b,c,d){if(2<=V.version)W.uniformMatrix2fv(Q[a],!!c,B,d>>2,4*b);else{if(72>=b)for(var e=jd[4*b-1],g=0;g<4*b;g+=4)e[g]=B[d+4*g>>2],e[g+1]=B[d+(4*g+4)>>2],e[g+2]=B[d+(4*g+8)>>2],e[g+3]=B[d+(4*g+12)>>2];else e=B.subarray(d>>2,d+16*b>>2);W.uniformMatrix2fv(Q[a],!!c,e)}},oc:function(a,b,c,d){W.uniformMatrix2x3fv(Q[a],!!c,B,d>>2,6*b)},mc:function(a,b,c,d){W.uniformMatrix2x4fv(Q[a],
!!c,B,d>>2,8*b)},bd:function(a,b,c,d){if(2<=V.version)W.uniformMatrix3fv(Q[a],!!c,B,d>>2,9*b);else{if(32>=b)for(var e=jd[9*b-1],g=0;g<9*b;g+=9)e[g]=B[d+4*g>>2],e[g+1]=B[d+(4*g+4)>>2],e[g+2]=B[d+(4*g+8)>>2],e[g+3]=B[d+(4*g+12)>>2],e[g+4]=B[d+(4*g+16)>>2],e[g+5]=B[d+(4*g+20)>>2],e[g+6]=B[d+(4*g+24)>>2],e[g+7]=B[d+(4*g+28)>>2],e[g+8]=B[d+(4*g+32)>>2];else e=B.subarray(d>>2,d+36*b>>2);W.uniformMatrix3fv(Q[a],!!c,e)}},nc:function(a,b,c,d){W.uniformMatrix3x2fv(Q[a],!!c,B,d>>2,6*b)},kc:function(a,b,c,d){W.uniformMatrix3x4fv(Q[a],
!!c,B,d>>2,12*b)},ad:function(a,b,c,d){if(2<=V.version)W.uniformMatrix4fv(Q[a],!!c,B,d>>2,16*b);else{if(18>=b){var e=jd[16*b-1],g=B;d>>=2;for(var k=0;k<16*b;k+=16){var m=d+k;e[k]=g[m];e[k+1]=g[m+1];e[k+2]=g[m+2];e[k+3]=g[m+3];e[k+4]=g[m+4];e[k+5]=g[m+5];e[k+6]=g[m+6];e[k+7]=g[m+7];e[k+8]=g[m+8];e[k+9]=g[m+9];e[k+10]=g[m+10];e[k+11]=g[m+11];e[k+12]=g[m+12];e[k+13]=g[m+13];e[k+14]=g[m+14];e[k+15]=g[m+15]}}else e=B.subarray(d>>2,d+64*b>>2);W.uniformMatrix4fv(Q[a],!!c,e)}},lc:function(a,b,c,d){W.uniformMatrix4x2fv(Q[a],
!!c,B,d>>2,8*b)},jc:function(a,b,c,d){W.uniformMatrix4x3fv(Q[a],!!c,B,d>>2,12*b)},$c:function(a){W.useProgram(O[a])},_c:function(a){W.validateProgram(O[a])},Zc:function(a,b){W.vertexAttrib1f(a,b)},Xc:function(a,b){W.vertexAttrib1f(a,B[b>>2])},Wc:function(a,b,c){W.vertexAttrib2f(a,b,c)},Vc:function(a,b){W.vertexAttrib2f(a,B[b>>2],B[b+4>>2])},Uc:function(a,b,c,d){W.vertexAttrib3f(a,b,c,d)},Tc:function(a,b){W.vertexAttrib3f(a,B[b>>2],B[b+4>>2],B[b+8>>2])},Sc:function(a,b,c,d,e){W.vertexAttrib4f(a,b,
c,d,e)},Rc:function(a,b){W.vertexAttrib4f(a,B[b>>2],B[b+4>>2],B[b+8>>2],B[b+12>>2])},Wa:function(a,b){W.vertexAttribDivisor(a,b)},$:function(a,b){W.vertexAttribDivisor(a,b)},Mc:function(a,b){W.vertexAttribDivisor(a,b)},Oc:function(a,b){W.vertexAttribDivisor(a,b)},Ga:function(a,b){W.vertexAttribDivisor(a,b)},Rb:function(a,b,c,d,e){W.vertexAttribI4i(a,b,c,d,e)},Pb:function(a,b){W.vertexAttribI4i(a,w[b>>2],w[b+4>>2],w[b+8>>2],w[b+12>>2])},Qb:function(a,b,c,d,e){W.vertexAttribI4ui(a,b,c,d,e)},Ob:function(a,
b){W.vertexAttribI4ui(a,G[b>>2],G[b+4>>2],G[b+8>>2],G[b+12>>2])},Ub:function(a,b,c,d,e){W.vertexAttribIPointer(a,b,c,d,e)},Qc:function(a,b,c,d,e,g){W.vertexAttribPointer(a,b,c,!!d,e,g)},Pc:function(a,b,c,d){W.viewport(a,b,c,d)},kb:function(a,b,c,d){W.waitSync(Oc[a],b,(c>>>0)+4294967296*d)},g:function(){return 0},ta:function(a,b,c){D.copyWithin(a,b,b+c)},e:function(a){a>>>=0;var b=D.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,
a,d);0<d%65536&&(d+=65536-d%65536);a:{try{Ca.grow(Math.min(2147483648,d)-Oa.byteLength+65535>>>16);Qa(Ca.buffer);var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},X:Yd,f:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},wa:function(a,b){var c=0;$d().forEach(function(d,e){var g=b+c;e=w[a+4*e>>2]=g;for(g=0;g<d.length;++g)v[e++>>0]=d.charCodeAt(g);v[e>>0]=0;c+=d.length+1});return 0},xa:function(a,b){var c=$d();w[a>>
2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});w[b>>2]=d;return 0},k:function(a){Oe(a)},l:function(a){try{var b=Ac(a);dc(b);return 0}catch(c){return"undefined"!==typeof M&&c instanceof I||p(c),c.Vf}},va:function(a,b){try{var c=Ac(a);v[b>>0]=c.tty?2:K(c.mode)?3:40960===(c.mode&61440)?7:4;return 0}catch(d){return"undefined"!==typeof M&&d instanceof I||p(d),d.Vf}},Ba:function(a,b,c,d){try{a:{for(var e=Ac(a),g=a=0;g<c;g++){var k=w[b+(8*g+4)>>2],m=fc(e,w[b+8*g>>2],k,void 0);if(0>m){var n=-1;
break a}a+=m;if(m<k)break}n=a}w[d>>2]=n;return 0}catch(r){return"undefined"!==typeof M&&r instanceof I||p(r),r.Vf}},Ea:function(a,b,c,d,e){try{var g=Ac(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;ec(g,a,d);y=[g.position>>>0,(A=g.position,1<=+xa(A)?0<A?(ya(+za(A/4294967296),4294967295)|0)>>>0:~~+Aa((A-+(~~A>>>0))/4294967296)>>>0:0)];w[e>>2]=y[0];w[e+4>>2]=y[1];g.Ig&&0===a&&0===d&&(g.Ig=null);return 0}catch(k){return"undefined"!==typeof M&&k instanceof I||p(k),k.Vf}},
p:function(a,b,c,d){try{a:{for(var e=Ac(a),g=a=0;g<c;g++){var k=hc(e,v,w[b+8*g>>2],w[b+(8*g+4)>>2],void 0);if(0>k){var m=-1;break a}a+=k}m=a}w[d>>2]=m;return 0}catch(n){return"undefined"!==typeof M&&n instanceof I||p(n),n.Vf}},m:function(a){var b=Date.now();w[a>>2]=b/1E3|0;w[a+4>>2]=b%1E3*1E3|0;return 0},he:function(a,b,c,d){var e;for(e=0;e<X.length&&null!==X[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var g=e+1;if(0>=a||0>=b)g=0;else{d?Kd():Wd(a,b);for(e=0;e<
X.length&&null==X[e];e++);e==X.length&&(f.eg=Gd(f.canvas,!0,!0,{antialias:1<ce[135181],depth:0<ce[135173],stencil:0<ce[135174],alpha:0<ce[135172]}));f.eg?(a=new be(g,a,b,c),g-1==X.length?X.push(a):X[g-1]=a,Y=a,g=a.id):g=0}return g},Ce:function(){ce=fe},Xb:function(a){a:{if(a=de(a)){a.hh&&Pe(a.hh,a.id);X[a.id-1]=null;Y.id==a.id&&(Y=null);for(a=0;a<X.length;a++)if(null!==X[a]){a=void 0;break a}f.eg=void 0}a=void 0}return a},rc:function(a,b,c){q(b,Qd,"double");q(c,Rd,"double")},gc:function(a,b,c){var d=
0,e=0;if(a=de(a))d=a.width,e=a.height;b&&q(b,d,"i32");c&&q(c,e,"i32")},a:function(a){return Qe(a)},Ne:function(){if(X)return 1;Bc();ce=fe;X=[];Y=null;window.addEventListener("gamepadconnected",me,!0);window.addEventListener("gamepaddisconnected",oe,!0);window.addEventListener("keydown",pe,!0);window.addEventListener("keypress",ie,!0);window.addEventListener("keyup",qe,!0);window.addEventListener("blur",re,!0);f.canvas.addEventListener("touchmove",se,!0);f.canvas.addEventListener("touchstart",ye,!0);
f.canvas.addEventListener("touchcancel",ze,!0);f.canvas.addEventListener("touchend",ze,!0);f.canvas.addEventListener("mousemove",se,!0);f.canvas.addEventListener("mousedown",ye,!0);f.canvas.addEventListener("mouseup",ze,!0);f.canvas.addEventListener("wheel",Ae,!0);f.canvas.addEventListener("mousewheel",Ae,!0);f.canvas.addEventListener("mouseenter",ue,!0);f.canvas.addEventListener("mouseleave",ve,!0);f.canvas.addEventListener("drop",Ge,!0);f.canvas.addEventListener("dragover",Ie,!0);Vd.push(function(a,
b){if(Y){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(Y.eh=Y.x,Y.fh=Y.y,Y.dh=Y.width,Y.bh=Y.height,Y.x=Y.y=0,Y.width=screen.width,Y.height=screen.height,Y.Hg=!0):1==Y.Hg?(Y.x=Y.eh,Y.y=Y.fh,Y.width=Y.dh,Y.height=Y.bh,Y.Hg=!1):Y.width!=a||Y.height!=b?(Y.width=a,Y.height=b):c=!1;c&&(Wd(Y.width,Y.height,!0),Y&&Y.jh&&He(Y.jh,Y.id,Y.width,Y.height),Y&&Y.qg&&He(Y.qg,Y.id,Y.width,Y.height))}});return 1},Yd:function(){},M:function(){},sd:function(a,
b){if(a=de(a)){var c=a.og;a.og=b;b=c}else b=null;return b},Ye:function(a){var b=ee;ee=a;return b},Dd:function(a,b){a=de(a);if(!a)return null;var c=a.qg;a.qg=b;return c},hd:function(a,b){if(a=de(a)){var c=a.rg;a.rg=b;b=c}else b=null;return b},Nc:function(a,b){if(a=de(a)){var c=a.vg;a.vg=b;b=c}else b=null;return b},Yc:function(a,b){if(a=de(a)){var c=a.xg;a.xg=b;b=c}else b=null;return b},Cc:function(a,b){a=de(a);if(!a)return null;var c=a.ih;a.ih=b;return c},B:function(){},Mb:function(){window.removeEventListener("gamepadconnected",
me,!0);window.removeEventListener("gamepaddisconnected",oe,!0);window.removeEventListener("keydown",pe,!0);window.removeEventListener("keypress",ie,!0);window.removeEventListener("keyup",qe,!0);window.removeEventListener("blur",re,!0);f.canvas.removeEventListener("touchmove",se,!0);f.canvas.removeEventListener("touchstart",ye,!0);f.canvas.removeEventListener("touchcancel",ze,!0);f.canvas.removeEventListener("touchend",ze,!0);f.canvas.removeEventListener("mousemove",se,!0);f.canvas.removeEventListener("mousedown",
ye,!0);f.canvas.removeEventListener("mouseup",ze,!0);f.canvas.removeEventListener("wheel",Ae,!0);f.canvas.removeEventListener("mousewheel",Ae,!0);f.canvas.removeEventListener("mouseenter",ue,!0);f.canvas.removeEventListener("mouseleave",ve,!0);f.canvas.removeEventListener("drop",Ge,!0);f.canvas.removeEventListener("dragover",Ie,!0);f.canvas.width=f.canvas.height=1;Y=X=null},i:function(a,b){ce[a]=b},memory:Ca,h:function(a,b){if(0===a)return mb(28),-1;var c=w[a>>2];a=w[a+4>>2];if(0>a||999999999<a||
0>c)return mb(28),-1;0!==b&&(w[b>>2]=0,w[b+4>>2]=0);b=1E6*c+a/1E3;for(c=Bc();Bc()-c<b/1E3;);},Ze:function(){},ga:function(){mb(52);return-1},q:function(){},d:function(){return 0},table:Da};
(function(){function a(e){f.asm=e.exports;cb("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return jb().then(function(g){return WebAssembly.instantiate(g,d)}).then(e,function(g){h("failed to asynchronously prepare wasm: "+g);p(g)})}var d={a:Re};bb("wasm-instantiate");if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return h("Module.instantiateWasm callback failed with error: "+e),!1}(function(){if(va||"function"!==typeof WebAssembly.instantiateStreaming||fb()||db("file://")||
"function"!==typeof fetch)return c(b);fetch(eb,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){h("wasm streaming compile failed: "+g);h("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var lb=f.___wasm_call_ctors=function(){return(lb=f.___wasm_call_ctors=f.asm._e).apply(null,arguments)},Fe=f._free=function(){return(Fe=f._free=f.asm.$e).apply(null,arguments)},Ga=f._malloc=function(){return(Ga=f._malloc=f.asm.af).apply(null,arguments)};f._main=function(){return(f._main=f.asm.bf).apply(null,arguments)};
var nb=f.___errno_location=function(){return(nb=f.___errno_location=f.asm.cf).apply(null,arguments)},Qe=f._emscripten_GetProcAddress=function(){return(Qe=f._emscripten_GetProcAddress=f.asm.df).apply(null,arguments)},Ne=f._memset=function(){return(Ne=f._memset=f.asm.ef).apply(null,arguments)},Na=f.stackAlloc=function(){return(Na=f.stackAlloc=f.asm.ff).apply(null,arguments)},Me=f._memalign=function(){return(Me=f._memalign=f.asm.gf).apply(null,arguments)},Pe=f.dynCall_vi=function(){return(Pe=f.dynCall_vi=
f.asm.hf).apply(null,arguments)};f.dynCall_v=function(){return(f.dynCall_v=f.asm.jf).apply(null,arguments)};f.dynCall_iiiii=function(){return(f.dynCall_iiiii=f.asm.kf).apply(null,arguments)};f.dynCall_ii=function(){return(f.dynCall_ii=f.asm.lf).apply(null,arguments)};f.dynCall_iiii=function(){return(f.dynCall_iiii=f.asm.mf).apply(null,arguments)};var He=f.dynCall_viii=function(){return(He=f.dynCall_viii=f.asm.nf).apply(null,arguments)};
f.dynCall_iiiiii=function(){return(f.dynCall_iiiiii=f.asm.of).apply(null,arguments)};f.dynCall_iii=function(){return(f.dynCall_iii=f.asm.pf).apply(null,arguments)};
var je=f.dynCall_vii=function(){return(je=f.dynCall_vii=f.asm.qf).apply(null,arguments)},te=f.dynCall_vidd=function(){return(te=f.dynCall_vidd=f.asm.rf).apply(null,arguments)},le=f.dynCall_viiiii=function(){return(le=f.dynCall_viiiii=f.asm.sf).apply(null,arguments)},xe=f.dynCall_viiii=function(){return(xe=f.dynCall_viiii=f.asm.tf).apply(null,arguments)};f.dynCall_jiji=function(){return(f.dynCall_jiji=f.asm.uf).apply(null,arguments)};
f.dynCall_ji=function(){return(f.dynCall_ji=f.asm.vf).apply(null,arguments)};f.dynCall_iidiiii=function(){return(f.dynCall_iidiiii=f.asm.wf).apply(null,arguments)};f.dynCall_vffff=function(){return(f.dynCall_vffff=f.asm.xf).apply(null,arguments)};f.dynCall_vf=function(){return(f.dynCall_vf=f.asm.yf).apply(null,arguments)};f.dynCall_viiiiiiii=function(){return(f.dynCall_viiiiiiii=f.asm.zf).apply(null,arguments)};f.dynCall_viiiiiiiii=function(){return(f.dynCall_viiiiiiiii=f.asm.Af).apply(null,arguments)};
f.dynCall_i=function(){return(f.dynCall_i=f.asm.Bf).apply(null,arguments)};f.dynCall_vff=function(){return(f.dynCall_vff=f.asm.Cf).apply(null,arguments)};f.dynCall_viiiiiii=function(){return(f.dynCall_viiiiiii=f.asm.Df).apply(null,arguments)};f.dynCall_vfi=function(){return(f.dynCall_vfi=f.asm.Ef).apply(null,arguments)};f.dynCall_viif=function(){return(f.dynCall_viif=f.asm.Ff).apply(null,arguments)};f.dynCall_vif=function(){return(f.dynCall_vif=f.asm.Gf).apply(null,arguments)};
f.dynCall_viff=function(){return(f.dynCall_viff=f.asm.Hf).apply(null,arguments)};f.dynCall_vifff=function(){return(f.dynCall_vifff=f.asm.If).apply(null,arguments)};f.dynCall_viffff=function(){return(f.dynCall_viffff=f.asm.Jf).apply(null,arguments)};f.dynCall_viiiiii=function(){return(f.dynCall_viiiiii=f.asm.Kf).apply(null,arguments)};f.dynCall_viiiiiiiiii=function(){return(f.dynCall_viiiiiiiiii=f.asm.Lf).apply(null,arguments)};
f.dynCall_viiiiiiiiiii=function(){return(f.dynCall_viiiiiiiiiii=f.asm.Mf).apply(null,arguments)};f.dynCall_viifi=function(){return(f.dynCall_viifi=f.asm.Nf).apply(null,arguments)};f.dynCall_iidii=function(){return(f.dynCall_iidii=f.asm.Of).apply(null,arguments)};f.dynCall_fii=function(){return(f.dynCall_fii=f.asm.Pf).apply(null,arguments)};f.getMemory=function(a){if(Xa)a=Ga(a);else{var b=w[10592];w[10592]=b+a+15&-16;a=b}return a};f.addRunDependency=bb;f.removeRunDependency=cb;f.FS_createFolder=lc;
f.FS_createPath=mc;f.FS_createDataFile=oc;f.FS_createPreloadedFile=tc;f.FS_createLazyFile=sc;f.FS_createLink=qc;f.FS_createDevice=pc;f.FS_unlink=$b;var Se;function pa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ab=function Te(){Se||Ue();Se||(ab=Te)};
function Ue(a){function b(){if(!Se&&(Se=!0,f.calledRun=!0,!Ea)){Xa=!0;f.noFSInit||jc||(jc=!0,ic(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?pc("/dev","stdin",f.stdin):Zb("/dev/tty","/dev/stdin"),f.stdout?pc("/dev","stdout",null,f.stdout):Zb("/dev/tty","/dev/stdout"),f.stderr?pc("/dev","stderr",null,f.stderr):Zb("/dev/tty1","/dev/stderr"),bc("/dev/stdin","r"),bc("/dev/stdout","w"),bc("/dev/stderr","w"));Sa(Ua);Ib=!1;Sa(Va);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(Ve){var c=
a,d=f._main;c=c||[];var e=c.length+1,g=Na(4*(e+1));w[g>>2]=Ma(da);for(var k=1;k<e;k++)w[(g>>2)+k]=Ma(c[k-1]);w[(g>>2)+e]=0;try{var m=d(e,g);Oe(m,!0)}catch(n){n instanceof pa||("unwind"==n?noExitRuntime=!0:((c=n)&&"object"===typeof n&&n.stack&&(c=[n,n.stack]),h("exception thrown: "+c),ea(1,n)))}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)c=f.postRun.shift(),Wa.unshift(c);Sa(Wa)}}a=a||ca;if(!(0<Za)){if(f.preRun)for("function"==typeof f.preRun&&
(f.preRun=[f.preRun]);f.preRun.length;)Ya();Sa(Ta);0<Za||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}f.run=Ue;function Oe(a,b){if(!b||!noExitRuntime||0!==a){if(!noExitRuntime&&(Ea=!0,f.onExit))f.onExit(a);ea(a,new pa(a))}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Ve=!0;f.noInitialRun&&(Ve=!1);noExitRuntime=!0;Ue();
