var g;g||(g=typeof Module !== 'undefined' ? Module : {});g.cg||(g.cg=0);g.cg++;
g.ENVIRONMENT_IS_PTHREAD||g.$ww||function(a){function b(n,q,t,v){if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)require("fs").readFile(n,function(z,E){z?v(z):t(E.buffer)});else{var w=new XMLHttpRequest;w.open("GET",n,!0);w.responseType="arraybuffer";w.onprogress=function(z){var E=q;z.total&&(E=z.total);if(z.loaded){w.tf?g.Gf[n].loaded=z.loaded:(w.tf=!0,g.Gf||(g.Gf={}),g.Gf[n]={loaded:z.loaded,total:E});var H=E=z=0,O;for(O in g.Gf){var W=g.Gf[O];
z+=W.total;E+=W.loaded;H++}z=Math.ceil(z*g.cg/H);g.setStatus&&g.setStatus(`Downloading data... (${E}/${z})`)}else!g.Gf&&g.setStatus&&g.setStatus("Downloading data...")};w.onerror=function(){throw Error("NetworkError for: "+n);};w.onload=function(){if(200==w.status||304==w.status||206==w.status||0==w.status&&w.response)t(w.response);else throw Error(w.statusText+" : "+w.responseURL);};w.send(null)}}function c(n){console.error("package error:",n)}function d(){function n(w,z,E){this.start=w;this.end=
z;this.audio=E}function q(w){if(!w)throw"Loading data file failed."+Error().stack;if(w.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;w=new Uint8Array(w);n.prototype.ig=w;w=a.files;for(var z=0;z<w.length;++z)n.prototype.tf[w[z].filename].onload();g.removeRunDependency("datafile_build/web/index.data")}g.FS_createPath("/","assets",!0,!0);g.FS_createPath("/assets","cursors",!0,!0);g.FS_createPath("/assets","maps",!0,!0);g.FS_createPath("/assets/maps","map objects",
!0,!0);g.FS_createPath("/assets","music",!0,!0);g.FS_createPath("/assets","sounds",!0,!0);n.prototype={tf:{},open:function(w,z){this.name=z;this.tf[z]=this;g.addRunDependency(`fp ${this.name}`)},send:function(){},onload:function(){this.finish(this.ig.subarray(this.start,this.end))},finish:function(w){g.FS_createDataFile(this.name,null,w,!0,!0,!0);g.removeRunDependency(`fp ${this.name}`);this.tf[this.name]=null}};for(var t=a.files,v=0;v<t.length;++v)(new n(t[v].start,t[v].end,t[v].audio||0)).open("GET",
t[v].filename);g.addRunDependency("datafile_build/web/index.data");g.xg||(g.xg={});g.xg["build/web/index.data"]={ph:!1};m?(q(m),m=null):h=q}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof g.locateFilePackage||
g.locateFile||(g.locateFile=g.locateFilePackage,k("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=g.locateFile?g.locateFile("index.data",""):"index.data",f=a.remote_package_size,h=null,m=g.getPreloadedPackage?g.getPreloadedPackage(e,f):null;m||b(e,f,function(n){h?(h(n),h=null):m=n},c);g.calledRun?d():(g.preRun||(g.preRun=[]),g.preRun.push(d))}({files:[{filename:"/assets/atlantis.ttf",start:0,end:93808},{filename:"/assets/atlas.dat",
start:93808,end:206885},{filename:"/assets/atlas.png",start:206885,end:1420232},{filename:"/assets/cursors/cursor-cd-clench.png",start:1420232,end:1426304},{filename:"/assets/cursors/cursor-cd.png",start:1426304,end:1432547},{filename:"/assets/cursors/cursor-clench.png",start:1432547,end:1439814},{filename:"/assets/cursors/cursor.png",start:1439814,end:1447286},{filename:"/assets/flan.png",start:1447286,end:1470074},{filename:"/assets/icon.ico",start:1470074,end:1484824},{filename:"/assets/icon.png",
start:1484824,end:1485548},{filename:"/assets/icon.rc",start:1485548,end:1485567},{filename:"/assets/icon.res",start:1485567,end:1500589},{filename:"/assets/maps/map objects/ash1.png",start:1500589,end:1502236},{filename:"/assets/maps/map objects/ash10.png",start:1502236,end:1503875},{filename:"/assets/maps/map objects/ash2.png",start:1503875,end:1505501},{filename:"/assets/maps/map objects/ash3.png",start:1505501,end:1507154},{filename:"/assets/maps/map objects/ash4.png",start:1507154,end:1508811},
{filename:"/assets/maps/map objects/ash5.png",start:1508811,end:1510483},{filename:"/assets/maps/map objects/ash6.png",start:1510483,end:1512156},{filename:"/assets/maps/map objects/ash7.png",start:1512156,end:1513801},{filename:"/assets/maps/map objects/ash8.png",start:1513801,end:1515444},{filename:"/assets/maps/map objects/ash9.png",start:1515444,end:1517090},{filename:"/assets/maps/map objects/backwall.png",start:1517090,end:1518705},{filename:"/assets/maps/map objects/backwallcornerleft.png",
start:1518705,end:1520464},{filename:"/assets/maps/map objects/backwallcornerleftinner.png",start:1520464,end:1522144},{filename:"/assets/maps/map objects/backwallcornerleftouter.png",start:1522144,end:1523791},{filename:"/assets/maps/map objects/backwallcornerright.png",start:1523791,end:1525545},{filename:"/assets/maps/map objects/backwallcornerrightinner.png",start:1525545,end:1527227},{filename:"/assets/maps/map objects/backwallcornerrightouter.png",start:1527227,end:1528879},{filename:"/assets/maps/map objects/backwalldark.png",
start:1528879,end:1530500},{filename:"/assets/maps/map objects/blank.png",start:1530500,end:1532073},{filename:"/assets/maps/map objects/books1.png",start:1532073,end:1532441},{filename:"/assets/maps/map objects/books10.png",start:1532441,end:1532786},{filename:"/assets/maps/map objects/books11.png",start:1532786,end:1533110},{filename:"/assets/maps/map objects/books12.png",start:1533110,end:1533445},{filename:"/assets/maps/map objects/books2.png",start:1533445,end:1533815},{filename:"/assets/maps/map objects/books3.png",
start:1533815,end:1534246},{filename:"/assets/maps/map objects/books4.png",start:1534246,end:1534651},{filename:"/assets/maps/map objects/books5.png",start:1534651,end:1535051},{filename:"/assets/maps/map objects/books6.png",start:1535051,end:1535445},{filename:"/assets/maps/map objects/books7.png",start:1535445,end:1535758},{filename:"/assets/maps/map objects/books8.png",start:1535758,end:1536053},{filename:"/assets/maps/map objects/books9.png",start:1536053,end:1536376},{filename:"/assets/maps/map objects/bookshelf_bl.png",
start:1536376,end:1538600},{filename:"/assets/maps/map objects/bookshelf_br.png",start:1538600,end:1540812},{filename:"/assets/maps/map objects/bookshelf_tl.png",start:1540812,end:1543040},{filename:"/assets/maps/map objects/bookshelf_tr.png",start:1543040,end:1545269},{filename:"/assets/maps/map objects/bookshelfback.png",start:1545269,end:1547495},{filename:"/assets/maps/map objects/bookshelfcornerbl.png",start:1547495,end:1549727},{filename:"/assets/maps/map objects/bookshelfcornerbr.png",start:1549727,
end:1551949},{filename:"/assets/maps/map objects/bookshelfcornertl.png",start:1551949,end:1554193},{filename:"/assets/maps/map objects/bookshelfcornertr.png",start:1554193,end:1556425},{filename:"/assets/maps/map objects/bookshelfempty.png",start:1556425,end:1558631},{filename:"/assets/maps/map objects/bookshelffront.png",start:1558631,end:1560849},{filename:"/assets/maps/map objects/bookshelfleft.png",start:1560849,end:1563044},{filename:"/assets/maps/map objects/bookshelfright.png",start:1563044,
end:1565239},{filename:"/assets/maps/map objects/candle-cut-1.png",start:1565239,end:1566964},{filename:"/assets/maps/map objects/candle-cut-2.png",start:1566964,end:1568671},{filename:"/assets/maps/map objects/candle-cut-3.png",start:1568671,end:1570377},{filename:"/assets/maps/map objects/candle-cut-4.png",start:1570377,end:1572079},{filename:"/assets/maps/map objects/candle-lit-1.png",start:1572079,end:1573835},{filename:"/assets/maps/map objects/candle-lit-2.png",start:1573835,end:1575591},{filename:"/assets/maps/map objects/candle-lit-3.png",
start:1575591,end:1577355},{filename:"/assets/maps/map objects/candle-lit-4.png",start:1577355,end:1579137},{filename:"/assets/maps/map objects/candle-unlit-1.png",start:1579137,end:1580894},{filename:"/assets/maps/map objects/candle-unlit-2.png",start:1580894,end:1582686},{filename:"/assets/maps/map objects/candle-unlit-3.png",start:1582686,end:1584446},{filename:"/assets/maps/map objects/candle-unlit-4.png",start:1584446,end:1586243},{filename:"/assets/maps/map objects/darkness.png",start:1586243,
end:1587854},{filename:"/assets/maps/map objects/darknessbl.png",start:1587854,end:1589473},{filename:"/assets/maps/map objects/darknessbr.png",start:1589473,end:1591095},{filename:"/assets/maps/map objects/darknesstl.png",start:1591095,end:1592722},{filename:"/assets/maps/map objects/darknesstr.png",start:1592722,end:1594356},{filename:"/assets/maps/map objects/dragon.png",start:1594356,end:1601855},{filename:"/assets/maps/map objects/dragonwall.png",start:1601855,end:1606125},{filename:"/assets/maps/map objects/dragonwall2.png",
start:1606125,end:1610345},{filename:"/assets/maps/map objects/edge.png",start:1610345,end:1611984},{filename:"/assets/maps/map objects/edgebl.png",start:1611984,end:1613690},{filename:"/assets/maps/map objects/edgebr.png",start:1613690,end:1615390},{filename:"/assets/maps/map objects/edgecornerbl.png",start:1615390,end:1617124},{filename:"/assets/maps/map objects/edgecornerbr.png",start:1617124,end:1618810},{filename:"/assets/maps/map objects/edgecornertl.png",start:1618810,end:1620512},{filename:"/assets/maps/map objects/edgecornertr.png",
start:1620512,end:1622238},{filename:"/assets/maps/map objects/edgeleft.png",start:1622238,end:1623869},{filename:"/assets/maps/map objects/edgeright.png",start:1623869,end:1625503},{filename:"/assets/maps/map objects/edgetl.png",start:1625503,end:1627198},{filename:"/assets/maps/map objects/edgetop.png",start:1627198,end:1628835},{filename:"/assets/maps/map objects/edgetr.png",start:1628835,end:1630536},{filename:"/assets/maps/map objects/fire.png",start:1630536,end:1632193},{filename:"/assets/maps/map objects/frontwall.png",
start:1632193,end:1634012},{filename:"/assets/maps/map objects/frontwall2.png",start:1634012,end:1636792},{filename:"/assets/maps/map objects/leftwall.png",start:1636792,end:1638407},{filename:"/assets/maps/map objects/leftwallinner.png",start:1638407,end:1640012},{filename:"/assets/maps/map objects/leftwallouter.png",start:1640012,end:1641613},{filename:"/assets/maps/map objects/lightsource.png",start:1641613,end:1641811},{filename:"/assets/maps/map objects/pillarleft.png",start:1641811,end:1644198},
{filename:"/assets/maps/map objects/pillarleftinner.png",start:1644198,end:1646299},{filename:"/assets/maps/map objects/pillarleftinner2.png",start:1646299,end:1649049},{filename:"/assets/maps/map objects/pillarleftouter.png",start:1649049,end:1651017},{filename:"/assets/maps/map objects/pillarleftouter2.png",start:1651017,end:1653922},{filename:"/assets/maps/map objects/pillarright.png",start:1653922,end:1656308},{filename:"/assets/maps/map objects/pillarrightinner.png",start:1656308,end:1658364},
{filename:"/assets/maps/map objects/pillarrightinner2.png",start:1658364,end:1661042},{filename:"/assets/maps/map objects/pillarrightouter.png",start:1661042,end:1663039},{filename:"/assets/maps/map objects/pillarrightouter2.png",start:1663039,end:1665905},{filename:"/assets/maps/map objects/rightwall.png",start:1665905,end:1667526},{filename:"/assets/maps/map objects/rightwallinner.png",start:1667526,end:1669133},{filename:"/assets/maps/map objects/rightwallouter.png",start:1669133,end:1670737},
{filename:"/assets/maps/map objects/ruinedshelvesinner1.png",start:1670737,end:1675894},{filename:"/assets/maps/map objects/ruinedshelvesinner2.png",start:1675894,end:1680944},{filename:"/assets/maps/map objects/ruinedshelvesouter1.png",start:1680944,end:1688529},{filename:"/assets/maps/map objects/ruinedshelvesouter2.png",start:1688529,end:1696055},{filename:"/assets/maps/map.png",start:1696055,end:1719127},{filename:"/assets/maps/map.tmj",start:1719127,end:1742343},{filename:"/assets/maps/map2.tmj",
start:1742343,end:1770533},{filename:"/assets/maps/map3.tmj",start:1770533,end:1791847},{filename:"/assets/maps/map_lava.png",start:1791847,end:1806286},{filename:"/assets/music/intro.ogg",start:1806286,end:2100389,audio:1},{filename:"/assets/music/main.ogg",start:2100389,end:6658100,audio:1},{filename:"/assets/music/tutorial.ogg",start:6658100,end:6929358,audio:1},{filename:"/assets/prose-lite.ttf",start:6929358,end:6955574},{filename:"/assets/screenflash.png",start:6955574,end:7027084},{filename:"/assets/sounds/asmusDeath.ogg",
start:7027084,end:7090822,audio:1},{filename:"/assets/sounds/asmusDeath2.ogg",start:7090822,end:7118674,audio:1},{filename:"/assets/sounds/asmusDying.ogg",start:7118674,end:7131209,audio:1},{filename:"/assets/sounds/asmusHit.ogg",start:7131209,end:7139172,audio:1},{filename:"/assets/sounds/asmusKill.ogg",start:7139172,end:7161594,audio:1},{filename:"/assets/sounds/asmusShooting.ogg",start:7161594,end:7172388,audio:1},{filename:"/assets/sounds/asmusSlash.ogg",start:7172388,end:7181704,audio:1},{filename:"/assets/sounds/asmusSlashRecharge.ogg",
start:7181704,end:7208953,audio:1},{filename:"/assets/sounds/asmusSpawn.ogg",start:7208953,end:7254196,audio:1},{filename:"/assets/sounds/asmusWalk.ogg",start:7254196,end:7268174,audio:1},{filename:"/assets/sounds/asmusWalkShooting.ogg",start:7268174,end:7279228,audio:1},{filename:"/assets/sounds/blast.ogg",start:7279228,end:7308027,audio:1},{filename:"/assets/sounds/bobHurt.ogg",start:7308027,end:7330975,audio:1},{filename:"/assets/sounds/bulletDeflect.ogg",start:7330975,end:7340827,audio:1},{filename:"/assets/sounds/bulletWallHit.ogg",
start:7340827,end:7348440,audio:1},{filename:"/assets/sounds/candleAmbience.ogg",start:7348440,end:7395282,audio:1},{filename:"/assets/sounds/candleAoe.ogg",start:7395282,end:7445899,audio:1},{filename:"/assets/sounds/candleDragons.ogg",start:7445899,end:7470695,audio:1},{filename:"/assets/sounds/candleExplosion.ogg",start:7470695,end:7501040,audio:1},{filename:"/assets/sounds/candleGuitar.ogg",start:7501040,end:7512598,audio:1},{filename:"/assets/sounds/candleLaser.ogg",start:7512598,end:7543386,
audio:1},{filename:"/assets/sounds/candleLaserCharging.ogg",start:7543386,end:7563097,audio:1},{filename:"/assets/sounds/candleLines.ogg",start:7563097,end:7596840,audio:1},{filename:"/assets/sounds/candlePopcorn.ogg",start:7596840,end:7607595,audio:1},{filename:"/assets/sounds/candleRecharge.ogg",start:7607595,end:7638628,audio:1},{filename:"/assets/sounds/candleShot.ogg",start:7638628,end:7652714,audio:1},{filename:"/assets/sounds/candleShotgun.ogg",start:7652714,end:7679279,audio:1},{filename:"/assets/sounds/candleSlash.ogg",
start:7679279,end:7700494,audio:1},{filename:"/assets/sounds/candleThunder.ogg",start:7700494,end:7716587,audio:1},{filename:"/assets/sounds/candleWaves.ogg",start:7716587,end:7731510,audio:1},{filename:"/assets/sounds/dragonDeath.ogg",start:7731510,end:7775387,audio:1},{filename:"/assets/sounds/dragonFinalDiamonds.ogg",start:7775387,end:7819933,audio:1},{filename:"/assets/sounds/dragonFinalDna.ogg",start:7819933,end:7866598,audio:1},{filename:"/assets/sounds/dragonFinalDragons.ogg",start:7866598,
end:7920713,audio:1},{filename:"/assets/sounds/dragonFinalInchworms.ogg",start:7920713,end:7964566,audio:1},{filename:"/assets/sounds/dragonFinalLaser.ogg",start:7964566,end:8033832,audio:1},{filename:"/assets/sounds/dragonFinalLaserCharging.ogg",start:8033832,end:8063208,audio:1},{filename:"/assets/sounds/dragonGuitarFull.ogg",start:8063208,end:8078547,audio:1},{filename:"/assets/sounds/dragonGuitarNormal.ogg",start:8078547,end:8095920,audio:1},{filename:"/assets/sounds/dragonGuitarSlow.ogg",start:8095920,
end:8113125,audio:1},{filename:"/assets/sounds/dragonLaser.ogg",start:8113125,end:8134003,audio:1},{filename:"/assets/sounds/dragonLaserCharging.ogg",start:8134003,end:8150668,audio:1},{filename:"/assets/sounds/dragonMorph.ogg",start:8150668,end:8177612,audio:1},{filename:"/assets/sounds/dragonSpawnerShoot.ogg",start:8177612,end:8200950,audio:1},{filename:"/assets/sounds/dragonSpawnerSpawn.ogg",start:8200950,end:8240044,audio:1},{filename:"/assets/sounds/dragonSpawnerTelegraph.ogg",start:8240044,
end:8251859,audio:1},{filename:"/assets/sounds/dragonSweepLaser.ogg",start:8251859,end:8307527,audio:1},{filename:"/assets/sounds/dragonSweepLaserCharging.ogg",start:8307527,end:8322633,audio:1},{filename:"/assets/sounds/dragonWave.ogg",start:8322633,end:8357804,audio:1},{filename:"/assets/sounds/hand.ogg",start:8357804,end:8478285,audio:1},{filename:"/assets/sounds/horn.ogg",start:8478285,end:8508305,audio:1},{filename:"/assets/sounds/hurt.ogg",start:8508305,end:8515727,audio:1},{filename:"/assets/sounds/lava.ogg",
start:8515727,end:8589390,audio:1},{filename:"/assets/sounds/lucineBackflip.ogg",start:8589390,end:8612378,audio:1},{filename:"/assets/sounds/lucineBallExplode.ogg",start:8612378,end:8638466,audio:1},{filename:"/assets/sounds/lucineBallLoop.ogg",start:8638466,end:8668998,audio:1},{filename:"/assets/sounds/lucineBallThrow.ogg",start:8668998,end:8699635,audio:1},{filename:"/assets/sounds/lucineCircle.ogg",start:8699635,end:8736400,audio:1},{filename:"/assets/sounds/lucineDash.ogg",start:8736400,end:8755011,
audio:1},{filename:"/assets/sounds/lucineDashBullets.ogg",start:8755011,end:8773404,audio:1},{filename:"/assets/sounds/lucineDeath.ogg",start:8773404,end:8944045,audio:1},{filename:"/assets/sounds/lucineDiamonds.ogg",start:8944045,end:8968229,audio:1},{filename:"/assets/sounds/lucineDragon.ogg",start:8968229,end:8996680,audio:1},{filename:"/assets/sounds/lucineFlowers.ogg",start:8996680,end:9023670,audio:1},{filename:"/assets/sounds/lucineGetUp.ogg",start:9023670,end:9039673,audio:1},{filename:"/assets/sounds/lucineHit.ogg",
start:9039673,end:9048507,audio:1},{filename:"/assets/sounds/lucineIntro.ogg",start:9048507,end:9060457,audio:1},{filename:"/assets/sounds/lucineJump.ogg",start:9060457,end:9090230,audio:1},{filename:"/assets/sounds/lucineMeditation.ogg",start:9090230,end:9137969,audio:1},{filename:"/assets/sounds/lucineMeditationBullets.ogg",start:9137969,end:9180997,audio:1},{filename:"/assets/sounds/lucineMeteorAmbience.ogg",start:9180997,end:9198962,audio:1},{filename:"/assets/sounds/lucineMinefield.ogg",start:9198962,
end:9208630,audio:1},{filename:"/assets/sounds/lucineMorph.ogg",start:9208630,end:9245112,audio:1},{filename:"/assets/sounds/lucineNuke.ogg",start:9245112,end:9330436,audio:1},{filename:"/assets/sounds/lucinePhase1Death.ogg",start:9330436,end:9345371,audio:1},{filename:"/assets/sounds/lucineSpears.ogg",start:9345371,end:9358573,audio:1},{filename:"/assets/sounds/lucineSpinAmbience.ogg",start:9358573,end:9391624,audio:1},{filename:"/assets/sounds/lucineSpinShoot.ogg",start:9391624,end:9438353,audio:1},
{filename:"/assets/sounds/lucineStagger.ogg",start:9438353,end:9471745,audio:1},{filename:"/assets/sounds/lucineSwipe.ogg",start:9471745,end:9486493,audio:1},{filename:"/assets/sounds/lucineTeleportFinish.ogg",start:9486493,end:9514270,audio:1},{filename:"/assets/sounds/lucineTeleportSitting.ogg",start:9514270,end:9542182,audio:1},{filename:"/assets/sounds/lucineTeleportStart.ogg",start:9542182,end:9567954,audio:1},{filename:"/assets/sounds/lucineTornadoAmbience.ogg",start:9567954,end:9605957,audio:1},
{filename:"/assets/sounds/lucineTornadoShot.ogg",start:9605957,end:9641255,audio:1},{filename:"/assets/sounds/lucineWhips2.ogg",start:9641255,end:9675658,audio:1},{filename:"/assets/sounds/lucineWhipsAmbience.ogg",start:9675658,end:9703229,audio:1},{filename:"/assets/sounds/lucineWhipsBullets.ogg",start:9703229,end:9729305,audio:1},{filename:"/assets/sounds/meteorAoe.ogg",start:9729305,end:9770639,audio:1},{filename:"/assets/sounds/plop.ogg",start:9770639,end:9779183,audio:1},{filename:"/assets/sounds/quake.ogg",
start:9779183,end:9840244,audio:1},{filename:"/assets/sounds/teleportAoe.ogg",start:9840244,end:9863222,audio:1},{filename:"/assets/sounds/text.ogg",start:9863222,end:9868799,audio:1}],remote_package_size:9868799});var aa=Object.assign({},g),ba=[],ca="./this.program",da=(a,b)=>{throw b;},ea="object"==typeof window,ha="function"==typeof importScripts,ia="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,ja="",ka,la,ma;
if(ia){var fs=require("fs"),na=require("path");ja=ha?na.dirname(ja)+"/":__dirname+"/";ka=(a,b)=>{a=a.startsWith("file://")?new URL(a):na.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ma=a=>{a=ka(a,!0);a.buffer||(a=new Uint8Array(a));return a};la=(a,b,c,d=!0)=>{a=a.startsWith("file://")?new URL(a):na.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,f)=>{e?c(e):b(d?f.buffer:f)})};!g.thisProgram&&1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=
typeof module&&(module.exports=g);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof oa||a.context instanceof oa))throw a;});da=(a,b)=>{process.exitCode=a;throw b;};g.inspect=()=>"[Emscripten Module object]"}else if(ea||ha)ha?ja=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ja=document.currentScript.src),ja=0!==ja.indexOf("blob:")?ja.substr(0,ja.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},
ha&&(ma=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),la=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var pa=g.print||console.log.bind(console),k=g.printErr||console.error.bind(console);Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);
g.quit&&(da=g.quit);var qa;g.wasmBinary&&(qa=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&l("no native wasm support detected");var ra,sa=!1,ta,p,r,ua,va,u,x,y,wa;function xa(){var a=ra.buffer;g.HEAP8=p=new Int8Array(a);g.HEAP16=ua=new Int16Array(a);g.HEAPU8=r=new Uint8Array(a);g.HEAPU16=va=new Uint16Array(a);g.HEAP32=u=new Int32Array(a);g.HEAPU32=x=new Uint32Array(a);g.HEAPF32=y=new Float32Array(a);g.HEAPF64=wa=new Float64Array(a)}var ya,za=[],Aa=[],Ba=[],Ca=[];
function Da(){var a=g.preRun.shift();za.unshift(a)}var Ea=0,Fa=null,Ga=null;function Ha(){Ea++;g.monitorRunDependencies&&g.monitorRunDependencies(Ea)}function Ia(){Ea--;g.monitorRunDependencies&&g.monitorRunDependencies(Ea);if(0==Ea&&(null!==Fa&&(clearInterval(Fa),Fa=null),Ga)){var a=Ga;Ga=null;a()}}function l(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";k(a);sa=!0;ta=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}
function Ja(a){return a.startsWith("data:application/octet-stream;base64,")}var Ka;Ka="index.wasm";if(!Ja(Ka)){var La=Ka;Ka=g.locateFile?g.locateFile(La,ja):ja+La}function Ma(a){if(a==Ka&&qa)return new Uint8Array(qa);if(ma)return ma(a);throw"both async and sync fetching of the wasm failed";}
function Na(a){if(!qa&&(ea||ha)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ma(a));if(la)return new Promise((b,c)=>{la(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Ma(a))}function Oa(a,b,c){return Na(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{k(`failed to asynchronously prepare wasm: ${d}`);l(d)})}
function Pa(a,b){var c=Ka;qa||"function"!=typeof WebAssembly.instantiateStreaming||Ja(c)||c.startsWith("file://")||ia||"function"!=typeof fetch?Oa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){k(`wasm streaming compile failed: ${e}`);k("falling back to ArrayBuffer instantiation");return Oa(c,a,b)}))}
var A,B,Ta={122492:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,122639:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,122873:a=>{"undefined"===typeof g.SDL2&&(g.SDL2={});var b=g.SDL2;a?b.capture={}:b.audio={};b.uf||("undefined"!==typeof AudioContext?b.uf=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.uf=new webkitAudioContext),b.uf&&
Qa(b.uf));return void 0===b.uf?-1:0},123366:()=>g.SDL2.uf.sampleRate,123434:(a,b,c,d)=>{function e(){}function f(m){void 0!==h.capture.Kf&&(clearTimeout(h.capture.Kf),h.capture.Kf=void 0);h.capture.Tf=h.uf.createMediaStreamSource(m);h.capture.wf=h.uf.createScriptProcessor(b,a,1);h.capture.wf.onaudioprocess=function(n){void 0!==h&&void 0!==h.capture&&(n.outputBuffer.getChannelData(0).fill(0),h.capture.Zf=n.inputBuffer,Ra(c,[d]))};h.capture.Tf.connect(h.capture.wf);h.capture.wf.connect(h.uf.destination);
h.capture.stream=m}var h=g.SDL2;h.capture.Xf=h.uf.createBuffer(a,b,h.uf.sampleRate);h.capture.Xf.getChannelData(0).fill(0);h.capture.Kf=setTimeout(function(){h.capture.Zf=h.capture.Xf;Ra(c,[d])},b/h.uf.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},125086:(a,b,c,d)=>{var e=g.SDL2;e.audio.wf=
e.uf.createScriptProcessor(b,0,a);e.audio.wf.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.pg=f.outputBuffer,Ra(c,[d]))};e.audio.wf.connect(e.uf.destination)},125496:(a,b)=>{for(var c=g.SDL2,d=c.capture.Zf.numberOfChannels,e=0;e<d;++e){var f=c.capture.Zf.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var h=0;h<b;++h)Sa(a+4*h,f[h]);else for(h=0;h<b;++h)Sa(a+4*(h*d+e),
f[h])}},126101:(a,b)=>{for(var c=g.SDL2,d=c.audio.pg.numberOfChannels,e=0;e<d;++e){var f=c.audio.pg.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var h=0;h<b;++h)f[h]=y[a+(h*d+e<<2)>>2]}},126581:a=>{var b=g.SDL2;if(a){void 0!==b.capture.Kf&&clearTimeout(b.capture.Kf);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);
b.capture.stream=void 0}void 0!==b.capture.wf&&(b.capture.wf.onaudioprocess=function(){},b.capture.wf.disconnect(),b.capture.wf=void 0);void 0!==b.capture.Tf&&(b.capture.Tf.disconnect(),b.capture.Tf=void 0);void 0!==b.capture.Xf&&(b.capture.Xf=void 0);b.capture=void 0}else void 0!=b.audio.wf&&(b.audio.wf.disconnect(),b.audio.wf=void 0),b.audio=void 0;void 0!==b.uf&&void 0===b.audio&&void 0===b.capture&&(b.uf.close(),b.uf=void 0)}};
function oa(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ua=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},Qa=a=>{var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&Ua(d,c,()=>{"suspended"===a.state&&a.resume()})})})},Va=a=>{for(;0<a.length;)a.shift()(g)},Wa=[],C=a=>{var b=Wa[a];b||(a>=Wa.length&&(Wa.length=a+1),Wa[a]=b=ya.get(a));return b},Ra=(a,b)=>{if("vi".includes("j")){var c=g.dynCall_vi;b&&b.length?c.apply(null,[a].concat(b)):c.call(null,a)}else C(a).apply(null,b)};
function Sa(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":p[a>>0]=b;break;case "i8":p[a>>0]=b;break;case "i16":ua[a>>1]=b;break;case "i32":u[a>>2]=b;break;case "i64":l("to do setValue(i64) use WASM_BIGINT");case "float":y[a>>2]=b;break;case "double":wa[a>>3]=b;break;case "*":x[a>>2]=b;break;default:l(`invalid type for setValue: ${c}`)}}
var Xa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,D=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Xa)return Xa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Ya=(a,b)=>a?D(r,a,b):"",Za=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},F=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Za(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},$a=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));
return a+b},ab=a=>{if("/"===a)return"/";a=F(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},bb=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(ia)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}l("initRandomDevice")},cb=a=>(cb=bb())(a);
function db(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Za(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var eb=[],fb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},gb=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var m=a.charCodeAt(++f);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>
12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e};function hb(a){var b=Array(fb(a)+1);a=gb(a,b,0,b.length);b.length=a;return b}var ib=[];function jb(a,b){ib[a]={input:[],output:[],Df:b};kb(a,lb)}
var lb={open(a){var b=ib[a.node.rdev];if(!b)throw new G(43);a.tty=b;a.seekable=!1},close(a){a.tty.Df.fsync(a.tty)},fsync(a){a.tty.Df.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Df.rg)throw new G(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.Df.rg(a.tty)}catch(m){throw new G(29);}if(void 0===h&&0===e)throw new G(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Df.hg)throw new G(60);try{for(var e=0;e<d;e++)a.tty.Df.hg(a.tty,b[c+
e])}catch(f){throw new G(29);}d&&(a.node.timestamp=Date.now());return e}},mb={rg(){a:{if(!eb.length){var a=null;if(ia){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c?a=b.slice(0,c).toString("utf-8"):a=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}eb=hb(a)}a=
eb.shift()}return a},hg(a,b){null===b||10===b?(pa(D(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(pa(D(a.output,0)),a.output=[])},Rg(){return{jh:25856,lh:5,ih:191,kh:35387,hh:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Sg(){return 0},Tg(){return[24,80]}},nb={hg(a,b){null===b||10===b?(k(D(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(k(D(a.output,0)),a.output=[])}};
function ob(a,b){var c=a.pf?a.pf.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.pf,a.pf=new Uint8Array(b),0<a.sf&&a.pf.set(c.subarray(0,a.sf),0))}
var I={Bf:null,Cf(){return I.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new G(63);I.Bf||(I.Bf={dir:{node:{Af:I.qf.Af,xf:I.qf.xf,lookup:I.qf.lookup,Uf:I.qf.Uf,rename:I.qf.rename,unlink:I.qf.unlink,rmdir:I.qf.rmdir,readdir:I.qf.readdir,symlink:I.qf.symlink},stream:{Ef:I.rf.Ef}},file:{node:{Af:I.qf.Af,xf:I.qf.xf},stream:{Ef:I.rf.Ef,read:I.rf.read,write:I.rf.write,lg:I.rf.lg,gg:I.rf.gg,wg:I.rf.wg}},link:{node:{Af:I.qf.Af,xf:I.qf.xf,readlink:I.qf.readlink},
stream:{}},og:{node:{Af:I.qf.Af,xf:I.qf.xf},stream:pb}});c=qb(a,b,c,d);16384===(c.mode&61440)?(c.qf=I.Bf.dir.node,c.rf=I.Bf.dir.stream,c.pf={}):32768===(c.mode&61440)?(c.qf=I.Bf.file.node,c.rf=I.Bf.file.stream,c.sf=0,c.pf=null):40960===(c.mode&61440)?(c.qf=I.Bf.link.node,c.rf=I.Bf.link.stream):8192===(c.mode&61440)&&(c.qf=I.Bf.og.node,c.rf=I.Bf.og.stream);c.timestamp=Date.now();a&&(a.pf[b]=c,a.timestamp=c.timestamp);return c},rh(a){return a.pf?a.pf.subarray?a.pf.subarray(0,a.sf):new Uint8Array(a.pf):
new Uint8Array(0)},qf:{Af(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.sf:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Kg=4096;b.blocks=Math.ceil(b.size/b.Kg);return b},xf(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==
b.size&&(b=b.size,a.sf!=b))if(0==b)a.pf=null,a.sf=0;else{var c=a.pf;a.pf=new Uint8Array(b);c&&a.pf.set(c.subarray(0,Math.min(b,a.sf)));a.sf=b}},lookup(){throw rb[44];},Uf(a,b,c,d){return I.createNode(a,b,c,d)},rename(a,b,c){if(16384===(a.mode&61440)){try{var d=sb(b,c)}catch(f){}if(d)for(var e in d.pf)throw new G(55);}delete a.parent.pf[a.name];a.parent.timestamp=Date.now();a.name=c;b.pf[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink(a,b){delete a.pf[b];a.timestamp=Date.now()},rmdir(a,b){var c=
sb(a,b),d;for(d in c.pf)throw new G(55);delete a.pf[b];a.timestamp=Date.now()},readdir(a){var b=[".",".."],c;for(c in a.pf)a.pf.hasOwnProperty(c)&&b.push(c);return b},symlink(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new G(28);return a.link}},rf:{read(a,b,c,d,e){var f=a.node.pf;if(e>=a.node.sf)return 0;a=Math.min(a.node.sf-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===
p.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.pf||a.pf.subarray)){if(f)return a.pf=b.subarray(c,c+d),a.sf=d;if(0===a.sf&&0===e)return a.pf=b.slice(c,c+d),a.sf=d;if(e+d<=a.sf)return a.pf.set(b.subarray(c,c+d),e),d}ob(a,e+d);if(a.pf.subarray&&b.subarray)a.pf.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.pf[e+f]=b[c+f];a.sf=Math.max(a.sf,e+d);return d},Ef(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.sf);if(0>b)throw new G(28);return b},
lg(a,b,c){ob(a.node,b+c);a.node.sf=Math.max(a.node.sf,b+c)},gg(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new G(43);a=a.node.pf;if(e&2||a.buffer!==p.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;l();b=void 0;if(!b)throw new G(48);p.set(a,b)}else c=!1,b=a.byteOffset;return{zh:b,dh:c}},wg(a,b,c,d){I.rf.write(a,b,0,d,c,!1);return 0}}},tb=(a,b,c)=>{var d=`al ${a}`;la(a,e=>{e||l(`Loading data file "${a}" failed (no arrayBuffer).`);b(new Uint8Array(e));
d&&Ia(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&Ha(d)},ub=g.preloadPlugins||[],xb=(a,b,c,d)=>{"undefined"!=typeof vb&&wb();var e=!1;ub.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},zb=(a,b,c,d,e,f,h,m,n,q)=>{function t(z){function E(H){q&&q();m||yb(a,b,H,d,e,n);f&&f();Ia(w)}xb(z,v,E,()=>{h&&h();Ia(w)})||E(z)}var v=b?db(F(a+"/"+b)):a,w=`cp ${v}`;Ha(w);"string"==typeof c?tb(c,z=>t(z),h):t(c)},Ab=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Bb=null,
Cb={},Db=[],Eb=1,Fb=null,Gb=!0,G=null,rb={};function Hb(a,b={}){a=db(a);if(!a)return{path:"",node:null};b=Object.assign({qg:!0,jg:0},b);if(8<b.jg)throw new G(32);a=a.split("/").filter(h=>!!h);for(var c=Bb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=sb(c,a[e]);d=F(d+"/"+a[e]);c.Jf&&(!f||f&&b.qg)&&(c=c.Jf.root);if(!f||b.Nf)for(f=0;40960===(c.mode&61440);)if(c=Ib(d),d=db($a(d),c),c=Hb(d,{jg:b.jg+1}).node,40<f++)throw new G(32);}return{path:d,node:c}}
function Jb(a){for(var b;;){if(a===a.parent)return a=a.Cf.vg,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Kb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Fb.length}function sb(a,b){var c;if(c=(c=Lb(a,"x"))?c:a.qf.lookup?0:2)throw new G(c,a);for(c=Fb[Kb(a.id,b)];c;c=c.Hf){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.qf.lookup(a,b)}
function qb(a,b,c,d){a=new Mb(a,b,c,d);b=Kb(a.parent.id,a.name);a.Hf=Fb[b];return Fb[b]=a}function Nb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Lb(a,b){if(Gb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ob(a,b){try{return sb(a,b),20}catch(c){}return Lb(a,"wx")}function Pb(){for(var a=0;4096>=a;a++)if(!Db[a])return a;throw new G(33);}
function Qb(a){a=Db[a];if(!a)throw new G(8);return a}function Rb(a,b=-1){Sb||(Sb=function(){this.tf={}},Sb.prototype={},Object.defineProperties(Sb.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.tf.flags},set(c){this.tf.flags=c}},position:{get(){return this.tf.position},set(c){this.tf.position=c}}}));a=Object.assign(new Sb,a);-1==b&&(b=Pb());a.fd=b;return Db[b]=a}var pb={open(a){a.rf=Cb[a.node.rdev].rf;a.rf.open&&a.rf.open(a)},Ef(){throw new G(70);}};
function kb(a,b){Cb[a]={rf:b}}function Tb(a,b){var c="/"===b,d=!b;if(c&&Bb)throw new G(10);if(!c&&!d){var e=Hb(b,{qg:!1});b=e.path;e=e.node;if(e.Jf)throw new G(10);if(16384!==(e.mode&61440))throw new G(54);}b={type:a,yh:{},vg:b,Xg:[]};a=a.Cf(b);a.Cf=b;b.root=a;c?Bb=a:e&&(e.Jf=b,e.Cf&&e.Cf.Xg.push(b))}function Ub(a,b,c){var d=Hb(a,{parent:!0}).node;a=ab(a);if(!a||"."===a||".."===a)throw new G(28);var e=Ob(d,a);if(e)throw new G(e);if(!d.qf.Uf)throw new G(63);return d.qf.Uf(d,a,b,c)}
function J(a,b){return Ub(a,(void 0!==b?b:511)&1023|16384,0)}function Vb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Ub(a,b|8192,c)}function Wb(a,b){if(!db(a))throw new G(44);var c=Hb(b,{parent:!0}).node;if(!c)throw new G(44);b=ab(b);var d=Ob(c,b);if(d)throw new G(d);if(!c.qf.symlink)throw new G(63);c.qf.symlink(c,b,a)}
function Xb(a){var b=Hb(a,{parent:!0}).node;if(!b)throw new G(44);var c=ab(a);a=sb(b,c);a:{try{var d=sb(b,c)}catch(f){d=f.vf;break a}var e=Lb(b,"wx");d=e?e:16384===(d.mode&61440)?31:0}if(d)throw new G(d);if(!b.qf.unlink)throw new G(63);if(a.Jf)throw new G(10);b.qf.unlink(b,c);b=Kb(a.parent.id,a.name);if(Fb[b]===a)Fb[b]=a.Hf;else for(b=Fb[b];b;){if(b.Hf===a){b.Hf=a.Hf;break}b=b.Hf}}
function Ib(a){a=Hb(a).node;if(!a)throw new G(44);if(!a.qf.readlink)throw new G(28);return db(Jb(a.parent),a.qf.readlink(a))}function Yb(a,b){a=Hb(a,{Nf:!b}).node;if(!a)throw new G(44);if(!a.qf.Af)throw new G(63);return a.qf.Af(a)}function Zb(a){return Yb(a,!0)}function $b(a,b){a="string"==typeof a?Hb(a,{Nf:!0}).node:a;if(!a.qf.xf)throw new G(63);a.qf.xf(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function ac(a,b,c){if(""===a)throw new G(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=F(a);try{e=Hb(a,{Nf:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new G(20);}else e=Ub(a,c,0),d=!0;if(!e)throw new G(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new G(54);
if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==Nb(b)||b&512)?31:Lb(e,Nb(b)):44))throw new G(c);if(b&512&&!d){c=e;c="string"==typeof c?Hb(c,{Nf:!0}).node:c;if(!c.qf.xf)throw new G(63);if(16384===(c.mode&61440))throw new G(31);if(32768!==(c.mode&61440))throw new G(28);if(d=Lb(c,"w"))throw new G(d);c.qf.xf(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Rb({node:e,path:Jb(e),flags:b,seekable:!0,position:0,rf:e.rf,$g:[],error:!1});e.rf.open&&e.rf.open(e);!g.logReadFiles||b&1||(bc||
(bc={}),a in bc||(bc[a]=1));return e}function cc(a){if(null===a.fd)throw new G(8);a.eg&&(a.eg=null);try{a.rf.close&&a.rf.close(a)}catch(b){throw b;}finally{Db[a.fd]=null}a.fd=null}function dc(a,b,c){if(null===a.fd)throw new G(8);if(!a.seekable||!a.rf.Ef)throw new G(70);if(0!=c&&1!=c&&2!=c)throw new G(28);a.position=a.rf.Ef(a,b,c);a.$g=[]}
function ec(a,b,c,d,e,f){if(0>d||0>e)throw new G(28);if(null===a.fd)throw new G(8);if(0===(a.flags&2097155))throw new G(8);if(16384===(a.node.mode&61440))throw new G(31);if(!a.rf.write)throw new G(28);a.seekable&&a.flags&1024&&dc(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new G(70);b=a.rf.write(a,b,c,d,e,f);h||(a.position+=b);return b}
function fc(){G||(G=function(a,b){this.name="ErrnoError";this.node=b;this.Zg=function(c){this.vf=c};this.Zg(a);this.message="FS error"},G.prototype=Error(),G.prototype.constructor=G,[44].forEach(a=>{rb[a]=new G(a);rb[a].stack="<generic error, no stack>"}))}var gc;function hc(a,b){a="string"==typeof a?a:Jb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=F(a+"/"+c);try{J(d)}catch(e){}a=d}}return d}
function ic(a,b,c,d){a=F(("string"==typeof a?a:Jb(a))+"/"+b);c=Ab(c,d);return Ub(a,(void 0!==c?c:438)&4095|32768,0)}function yb(a,b,c,d,e,f){var h=b;a&&(a="string"==typeof a?a:Jb(a),h=b?F(a+"/"+b):a);a=Ab(d,e);h=Ub(h,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}$b(h,a|146);b=ac(h,577);ec(b,c,0,c.length,0,f);cc(b);$b(h,a)}return h}
function jc(a,b,c,d){a=F(("string"==typeof a?a:Jb(a))+"/"+b);b=Ab(!!c,!!d);jc.tg||(jc.tg=64);var e=jc.tg++<<8|0;kb(e,{open(f){f.seekable=!1},close(){d&&d.buffer&&d.buffer.length&&d(10)},read(f,h,m,n){for(var q=0,t=0;t<n;t++){try{var v=c()}catch(w){throw new G(29);}if(void 0===v&&0===q)throw new G(6);if(null===v||void 0===v)break;q++;h[m+t]=v}q&&(f.node.timestamp=Date.now());return q},write(f,h,m,n){for(var q=0;q<n;q++)try{d(h[m+q])}catch(t){throw new G(29);}n&&(f.node.timestamp=Date.now());return q}});
return Vb(a,b,e)}function kc(a){if(!(a.Ug||a.Vg||a.link||a.pf)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ka)try{a.pf=hb(ka(a.url)),a.sf=a.pf.length}catch(b){throw new G(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function lc(a,b,c,d,e){function f(){this.fg=!1;this.tf=[]}f.prototype.get=function(t){if(!(t>this.length-1||0>t)){var v=t%this.chunkSize;return this.sg(t/this.chunkSize|0)[v]}};f.prototype.ig=function(t){this.sg=t};f.prototype.mg=function(){var t=new XMLHttpRequest;t.open("HEAD",c,!1);t.send(null);if(!(200<=t.status&&300>t.status||304===t.status))throw Error("Couldn't load "+c+". Status: "+t.status);var v=Number(t.getResponseHeader("Content-length")),w,z=(w=t.getResponseHeader("Accept-Ranges"))&&
"bytes"===w;t=(w=t.getResponseHeader("Content-Encoding"))&&"gzip"===w;var E=1048576;z||(E=v);var H=this;H.ig(O=>{var W=O*E,fa=(O+1)*E-1;fa=Math.min(fa,v-1);if("undefined"==typeof H.tf[O]){var Fe=H.tf;if(W>fa)throw Error("invalid range ("+W+", "+fa+") or no bytes requested!");if(fa>v-1)throw Error("only "+v+" bytes available! programmer error!");var R=new XMLHttpRequest;R.open("GET",c,!1);v!==E&&R.setRequestHeader("Range","bytes="+W+"-"+fa);R.responseType="arraybuffer";R.overrideMimeType&&R.overrideMimeType("text/plain; charset=x-user-defined");
R.send(null);if(!(200<=R.status&&300>R.status||304===R.status))throw Error("Couldn't load "+c+". Status: "+R.status);W=void 0!==R.response?new Uint8Array(R.response||[]):hb(R.responseText||"");Fe[O]=W}if("undefined"==typeof H.tf[O])throw Error("doXHR failed!");return H.tf[O]});if(t||!v)E=v=1,E=v=this.sg(0).length,pa("LazyFiles on gzip forces download of the whole file when length is accessed");this.Jg=v;this.Ig=E;this.fg=!0};if("undefined"!=typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var h=new f;Object.defineProperties(h,{length:{get:function(){this.fg||this.mg();return this.Jg}},chunkSize:{get:function(){this.fg||this.mg();return this.Ig}}});var m=void 0}else m=c,h=void 0;var n=ic(a,b,d,e);h?n.pf=h:m&&(n.pf=null,n.url=m);Object.defineProperties(n,{sf:{get:function(){return this.pf.length}}});var q={};Object.keys(n.rf).forEach(t=>{var v=n.rf[t];q[t]=function(){kc(n);return v.apply(null,arguments)}});q.read=(t,v,w,z,E)=>{kc(n);t=t.node.pf;if(E>=t.length)v=0;else{z=Math.min(t.length-
E,z);if(t.slice)for(var H=0;H<z;H++)v[w+H]=t[E+H];else for(H=0;H<z;H++)v[w+H]=t.get(E+H);v=z}return v};q.gg=()=>{kc(n);l();throw new G(48);};n.rf=q;return n}var K={},Sb,bc;function mc(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":Qb(a).path;if(0==b.length){if(!c)throw new G(44);return a}return F(a+"/"+b)}
function nc(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&F(b)!==F(Jb(f.node)))return-54;throw f;}u[c>>2]=d.dev;u[c+4>>2]=d.mode;x[c+8>>2]=d.nlink;u[c+12>>2]=d.uid;u[c+16>>2]=d.gid;u[c+20>>2]=d.rdev;B=[d.size>>>0,(A=d.size,1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];u[c+24>>2]=B[0];u[c+28>>2]=B[1];u[c+32>>2]=4096;u[c+36>>2]=d.blocks;a=d.atime.getTime();b=d.mtime.getTime();var e=d.ctime.getTime();B=[Math.floor(a/1E3)>>>0,(A=Math.floor(a/1E3),1<=
+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];u[c+40>>2]=B[0];u[c+44>>2]=B[1];x[c+48>>2]=a%1E3*1E3;B=[Math.floor(b/1E3)>>>0,(A=Math.floor(b/1E3),1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];u[c+56>>2]=B[0];u[c+60>>2]=B[1];x[c+64>>2]=b%1E3*1E3;B=[Math.floor(e/1E3)>>>0,(A=Math.floor(e/1E3),1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];u[c+72>>2]=B[0];
u[c+76>>2]=B[1];x[c+80>>2]=e%1E3*1E3;B=[d.ino>>>0,(A=d.ino,1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];u[c+88>>2]=B[0];u[c+92>>2]=B[1];return 0}var oc=void 0;function pc(){var a=u[oc>>2];oc+=4;return a}var qc=[],rc=(a,b)=>{qc.length=0;for(var c;c=r[a++];)b+=105!=c&&b%8?4:0,qc.push(105==c?u[b>>2]:wa[b>>3]),b+=105==c?4:8;return qc},sc;sc=()=>performance.now();
var tc=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,h)=>b.drawElementsInstancedANGLE(c,d,e,f,h))},uc=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},
vc=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},wc=1,xc=[],L=[],yc=[],zc=[],Ac=[],M=[],Bc=[],Cc=[],N=[],P=[],Dc=[],Ec=[],Fc={},Gc={},Hc=4;function Q(a){Ic||(Ic=a)}
var Jc=a=>{for(var b=wc++,c=a.length;c<b;c++)a[c]=null;return b},Lc=(a,b)=>{a.tf||(a.tf=a.getContext,a.getContext=function(d,e){e=a.tf(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.ug?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Kc(c,b):0},Kc=(a,b)=>{var c=Jc(Cc),d={handle:c,attributes:b,version:b.ug,Yf:a};a.canvas&&(a.canvas.bh=d);Cc[c]=d;("undefined"==typeof b.Ng||b.Ng)&&Mc(d);return c},Mc=a=>{a||(a=S);if(!a.Pg){a.Pg=!0;var b=a.Yf;tc(b);uc(b);vc(b);b.nh=
b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.sh=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.yf=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.yf)b.yf=b.getExtension("EXT_disjoint_timer_query");b.vh=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},Nc={},Ic,S,Oc=a=>{T.bindVertexArray(Bc[a])},Pc=(a,b)=>{for(var c=
0;c<a;c++){var d=u[b+4*c>>2];T.deleteVertexArray(Bc[d]);Bc[d]=null}},Qc=(a,b,c,d)=>{T.drawArraysInstanced(a,b,c,d)},Rc=[],Sc=(a,b)=>{for(var c=Rc[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];T.drawBuffers(c)},Tc=(a,b,c,d,e)=>{T.drawElementsInstanced(a,b,c,d,e)},Uc=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=T[c](),h=f&&Jc(d);f?(f.name=h,d[h]=f):Q(1282);u[b+4*e>>2]=h}};function Vc(a,b){Uc(a,b,"createVertexArray",Bc)}
var Wc=(a,b,c,d,e,f,h,m)=>{b=L[b];if(a=T[a](b,c))d=m&&gb(a.name,r,m,d),e&&(u[e>>2]=d),f&&(u[f>>2]=a.size),h&&(u[h>>2]=a.type)},Xc=(a,b)=>{x[a>>2]=b;x[a+4>>2]=(b-x[a>>2])/4294967296},Yc=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&Q(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=T.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>S.version){Q(1282);return}d=2*(T.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>S.version){Q(1280);
return}d=33307==a?3:0}if(void 0===d)switch(e=T.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":Q(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:Q(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof
Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:u[b+4*a>>2]=e[a];break;case 2:y[b+4*a>>2]=e[a];break;case 4:p[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){Q(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:Q(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:Xc(b,d);break;case 0:u[b>>2]=d;
break;case 2:y[b>>2]=d;break;case 4:p[b>>0]=d?1:0}}else Q(1281)},Zc=(a,b,c,d)=>{if(c){b=T.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:Q(1280);return}else if(b instanceof WebGLBuffer)a=b.name|0;else{Q(1280);return}break;default:Q(1280);return}switch(d){case 1:Xc(c,a);break;case 0:u[c>>2]=a;break;case 2:y[c>>2]=a;break;case 4:p[c>>0]=a?1:0;break;default:throw"internal emscriptenWebGLGetIndexed() error, bad type: "+
d;}}else Q(1281)},$c=(a,b,c)=>{if(c){a=N[a];b=2>S.version?T.yf.getQueryObjectEXT(a,b):T.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;Xc(c,d)}else Q(1281)},ad=(a,b,c)=>{if(c){a=T.yf.getQueryObjectEXT(N[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else Q(1281)},cd=a=>{var b=fb(a)+1,c=bd(b);c&&gb(a,r,c,b);return c},dd=a=>{var b=Fc[a];if(!b){switch(a){case 7939:b=T.getSupportedExtensions()||[];b=b.concat(b.map(d=>"GL_"+d));b=cd(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=
T.getParameter(a))||Q(1280);b=b&&cd(b);break;case 7938:b=T.getParameter(7938);b=2<=S.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=cd(b);break;case 35724:b=T.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=cd(b);break;default:Q(1280)}Fc[a]=b}return b},ed=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),fd=a=>{var b=a.Lf,c=a.Dg,d;if(!b)for(a.Lf=b={},a.Cg={},d=0;d<T.getProgramParameter(a,
35718);++d){var e=T.getActiveUniform(a,d);var f=e.name;e=e.size;var h=ed(f);h=0<h?f.slice(0,h):f;var m=a.kg;a.kg+=e;c[h]=[e,m];for(f=0;f<e;++f)b[m]=f,a.Cg[m++]=h}},U=a=>{var b=T.Mg;if(b){var c=b.Lf[a];"number"==typeof c&&(b.Lf[a]=c=T.getUniformLocation(b,b.Cg[a]+(0<c?"["+c+"]":"")));return c}Q(1282)},gd=(a,b,c,d)=>{if(c)if(a=L[a],fd(a),a=T.getUniform(a,U(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:y[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*
b>>2]=a[b];break;case 2:y[c+4*b>>2]=a[b]}else Q(1281)},hd=(a,b,c,d)=>{if(c)if(a=T.getVertexAttrib(a,b),34975==b)u[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:y[c>>2]=a;break;case 5:u[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:y[c+4*b>>2]=a[b];break;case 5:u[c+4*b>>2]=Math.fround(a[b])}else Q(1281)},jd=(a,b,c)=>{hd(a,b,c,0)},kd=a=>(a=Bc[a])?T.isVertexArray(a):0,ld=a=>{a-=5120;return 0==
a?p:1==a?r:2==a?ua:4==a?u:6==a?y:5==a||28922==a||28520==a||30779==a||30782==a?x:va},md=(a,b,c,d,e)=>{a=ld(a);var f=31-Math.clz32(a.BYTES_PER_ELEMENT),h=Hc;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<f)+h-1&-h)>>f)},nd=[],od=[],pd=(a,b)=>{T.vertexAttribDivisor(a,b)},qd=a=>{a instanceof oa||"unwind"==a||da(1,a)},rd=a=>{ta=a;if(!noExitRuntime){if(g.onExit)g.onExit(a);sa=!0}da(a,new oa(a))},sd=a=>{ta=a;rd(a)},td=()=>{if(!noExitRuntime)try{var a=
ta;ta=a;rd(a)}catch(b){qd(b)}},ud=a=>{setTimeout(()=>{if(!sa)try{a(),td()}catch(b){qd(b)}},1E4)},vd=!1,wd=null,xd=0,yd=null,zd=0,Ad=0,Bd=0,Cd=0,Dd=[],Ed={},Fd,Gd,Hd,Id=!1,Jd=!1,Kd=[];
function wb(){function a(){Jd=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}if(!Ld){Ld=!0;ub.push({canHandle:function(c){return!g.xh&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var h=new Blob([c],{type:Md(d)});h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:Md(d)}));var m=URL.createObjectURL(h),n=new Image;n.onload=()=>{n.complete||l(`Image ${d} could not be decoded`);
var q=document.createElement("canvas");q.width=n.width;q.height=n.height;q.getContext("2d").drawImage(n,0,0);URL.revokeObjectURL(m);e&&e(c)};n.onerror=()=>{k(`Image ${m} could not be decoded`);f&&f()};n.src=m}});ub.push({canHandle:function(c){return!g.wh&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){h||(h=!0,e&&e(c))}var h=!1,m=URL.createObjectURL(new Blob([c],{type:Md(d)})),n=new Audio;n.addEventListener("canplaythrough",()=>f(n),!1);n.onerror=function(){if(!h){k(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var q="",t=0,v=0,w=0;w<c.length;w++)for(t=t<<8|c[w],v+=8;6<=v;){var z=t>>v-6&63;v-=6;q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[z]}2==v?(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&3)<<4],q+="=="):4==v&&(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&15)<<2],q+="=");n.src="data:audio/x-"+d.substr(-3)+";base64,"+q;f(n)}};n.src=m;ud(()=>{f(n)})}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",
c=>{!Jd&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Nd(a,b,c,d){if(b&&g.Ff&&a==g.canvas)return g.Ff;var e;if(b){var f={antialias:!1,alpha:!1,ug:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var h in d)f[h]=d[h];if("undefined"!=typeof Nc&&(e=Lc(a,f)))var m=Cc[e].Yf}else m=a.getContext("2d");if(!m)return null;c&&(b||"undefined"==typeof T||l("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.Ff=m,b&&(S=Cc[e],g.Ff=T=S&&S.Yf),g.Ah=b,Kd.forEach(n=>n()),wb());return m}var Od=!1,Pd=void 0,Qd=void 0;
function Rd(a,b){function c(){Id=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Sd,Pd&&d.requestPointerLock(),Id=!0,Qd?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=x[SDL.screen>>2]|8388608),Td(g.canvas),Ud()):Td(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Qd?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=x[SDL.screen>>2]&
-8388609),Td(g.canvas),Ud()):Td(d));if(g.onFullScreen)g.onFullScreen(Id);if(g.onFullscreen)g.onFullscreen(Id)}Pd=a;Qd=b;"undefined"==typeof Pd&&(Pd=!0);"undefined"==typeof Qd&&(Qd=!1);var d=g.canvas;Od||(Od=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function Sd(){if(!Id)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Vd=0;function Wd(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Vd)Vd=b+1E3/60;else for(;b+2>=Vd;)Vd+=1E3/60;setTimeout(a,Math.max(Vd-b,0))}}
function Md(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Xd=0,Yd=0,Zd=0,$d=0;
function ae(a){if(Jd)"mousemove"!=a.type&&"mozMovementX"in a?Zd=$d=0:(Zd=a.movementX||a.mozMovementX||a.webkitMovementX||0,$d=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(Xd=SDL.th+Zd,Yd=SDL.uh+$d):(Xd+=Zd,Yd+=$d);else{var b=g.canvas.getBoundingClientRect(),c=g.canvas.width,d=g.canvas.height,e="undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset,f="undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(f+b.top),e*=c/b.width,a*=d/b.height,Zd=e-Xd,$d=a-Yd,Xd=e,Yd=a)}}var be=[];function Ud(){var a=g.canvas;be.forEach(b=>b(a.width,a.height))}function ce(a,b,c){Td(g.canvas,a,b);c||Ud()}
function Td(a,b,c){b&&c?(a.ah=b,a.Og=c):(b=a.ah,c=a.Og);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Qd?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var vb={},Ld,de=(a,b)=>{Ad=a;Bd=b;if(yd)if(vd||(vd=!0),0==a)wd=function(){var d=Math.max(0,Gd+b-sc())|0;setTimeout(Hd,d)};else if(1==a)wd=function(){Wd(Hd)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);ha?(void 0===g.setImmediates&&(g.setImmediates=[]),g.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}wd=function(){setImmediate(Hd)}}},ee=(a,b,c,d,e)=>{!yd||l("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");yd=a;zd=d;var f=xd;vd=!1;Hd=function(){if(!sa)if(0<Dd.length){var h=Dd.shift();h.qh(h.eh);if(Fd){var m=Fd,n=0==m%1?m-1:Math.floor(m);Fd=h.mh?n:(8*m+(n+.5))/9}g.setStatus&&(h=g.statusMessage||"Please wait...",m=Fd,n=Ed.oh,m?m<n?g.setStatus(h+" ("+
(n-m)+"/"+n+")"):g.setStatus(h):g.setStatus(""));f<xd||setTimeout(Hd,0)}else if(!(f<xd))if(Cd=Cd+1|0,1==Ad&&1<Bd&&0!=Cd%Bd)wd();else{0==Ad&&(Gd=sc());if(!(sa||g.preMainLoop&&!1===g.preMainLoop())){if(!sa)try{a(),td()}catch(q){qd(q)}g.postMainLoop&&g.postMainLoop()}f<xd||("object"==typeof SDL&&SDL.audio&&SDL.audio.Yg&&SDL.audio.Yg(),wd())}};e||(b&&0<b?de(0,1E3/b):de(1,1),wd());if(c)throw"unwind";},fe={},he=()=>{if(!ge){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",
LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in fe)void 0===fe[b]?delete a[b]:a[b]=fe[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);ge=c}return ge},ge;
function ie(a,b,c,d,e){this.id=a;this.y=this.x=0;this.dg=!1;this.Bg=this.Ag=0;this.width=b;this.height=c;this.zg=b;this.yg=c;this.title=d;this.Wg=e;this.attributes=je;this.buttons=0;this.keys=[];this.ag=[];this.ng=this.Pf=this.bg=this.Wf=this.Mf=this.If=this.Vf=this.Fg=this.Of=this.Gg=this.Eg=this.Hg=this.title=null}
var X=a=>0>=a||!V?null:V[a-1],ke=null,Y=null,le=null,V=null,me=null,je=null,ne={131073:0,131074:0,131075:1,131076:1,131077:1,131082:0,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0,139276:0},oe=a=>{switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;
case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;
case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;
case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;
case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}},
pe=()=>{var a=Y,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b},qe=a=>{Y&&Y.ng&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||C(Y.ng)(Y.id,a))},re=(a,b)=>{if(Y){var c=oe(a);if(-1!=c){var d=b&&Y.keys[c];Y.keys[c]=b;Y.ag[a]=b;Y.Pf&&(d&&(b=2),C(Y.Pf)(Y.id,c,a,b,pe()))}}},te=()=>{se()},ue=()=>{se()},ve=a=>{re(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()},we=a=>{re(a.keyCode,0)},xe=()=>{if(Y)for(var a=0;a<Y.ag.length;++a)Y.ag[a]&&
re(a,0)},ye=a=>{Y&&(ae(a),a.target==g.canvas&&Y.If&&Y.If&&C(Y.If)(Y.id,Xd,Yd))},ze=a=>{Y&&a.target==g.canvas&&Y.Mf&&C(Y.Mf)(Y.id,1)},Ae=a=>{Y&&a.target==g.canvas&&Y.Mf&&C(Y.Mf)(Y.id,0)},Be=(a,b)=>{if(Y&&(ae(a),a.target==g.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){Y.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else Y.buttons&=~(1<<c);Y.Vf&&C(Y.Vf)(Y.id,c,b,pe())}},Ce=a=>{Y&&Be(a,1)},De=a=>{Y&&Be(a,0)},Ee=a=>{switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=
a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);if(Y&&Y.Wf&&a.target==g.canvas){var c=b;b="mousewheel"==a.type?a.wheelDeltaX:a.deltaX;C(Y.Wf)(Y.id,b,c);a.preventDefault()}},Ge={},He=[],Ie=null,se=()=>{if(Cd!==Ie||!Cd){He=navigator.getGamepads?navigator.getGamepads():
navigator.webkitGetGamepads?navigator.webkitGetGamepads:[];Ie=Cd;for(var a=0;a<He.length;++a){var b=He[a];if(b){Ge[a]||(pa("glfw joystick connected:",a),Ge[a]={id:cd(b.id),gh:b.buttons.length,fh:b.axes.length,buttons:bd(b.buttons.length),axes:bd(4*b.axes.length)});for(var c=Ge[a],d=0;d<b.buttons.length;++d)p[c.buttons+d>>0]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)y[c.axes+4*d>>2]=b.axes[d]}else Ge[a]&&(pa("glfw joystick disconnected",a),Je(Ge[a].id),Je(Ge[a].buttons),Je(Ge[a].axes),delete Ge[a])}}},
Ke=a=>{function b(m){var n="/.glfw_dropped_files/"+m.name.replace(/\//g,"_"),q=new FileReader;q.onloadend=v=>{if(2!=q.readyState)++f,pa("failed to read dropped file: "+m.name+": "+q.error);else{var w=new Uint8Array(v.target.result);v={};v.flags=v.flags||577;var z=ac(n,v.flags,v.mode);if("string"==typeof w){var E=new Uint8Array(fb(w)+1);w=gb(w,E,0,E.length);ec(z,E,0,w,void 0,v.Lg)}else if(ArrayBuffer.isView(w))ec(z,w,0,w.byteLength,void 0,v.Lg);else throw Error("Unsupported data type");cc(z);if(++f===
e){C(Y.bg)(Y.id,e,c);for(v=0;v<d.length;++v)Je(d[v]);Je(c)}}};q.readAsArrayBuffer(m);var t=cd(n);d.push(t);x[c+4*h>>2]=t}if(Y&&Y.bg&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=bd(4*a.dataTransfer.files.length),d=[],e=a.dataTransfer.files.length,f=0;hc("/",".glfw_dropped_files");for(var h=0;h<e;++h)b(a.dataTransfer.files[h]);return!1}},Le=a=>{if(Y&&Y.bg)return a.preventDefault(),!1};
function Mb(a,b,c,d){a||(a=this);this.parent=a;this.Cf=a.Cf;this.Jf=null;this.id=Eb++;this.name=b;this.mode=c;this.qf={};this.rf={};this.rdev=d}Object.defineProperties(Mb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Vg:{get:function(){return 16384===(this.mode&61440)}},Ug:{get:function(){return 8192===(this.mode&61440)}}});fc();
Fb=Array(4096);Tb(I,"/");J("/tmp");J("/home");J("/home/web_user");(function(){J("/dev");kb(259,{read:()=>0,write:(d,e,f,h)=>h});Vb("/dev/null",259);jb(1280,mb);jb(1536,nb);Vb("/dev/tty",1280);Vb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=cb(a).byteLength);return a[--b]};jc("/dev","random",c);jc("/dev","urandom",c);J("/dev/shm");J("/dev/shm/tmp")})();
(function(){J("/proc");var a=J("/proc/self");J("/proc/self/fd");Tb({Cf(){var b=qb(a,"fd",16895,73);b.qf={lookup(c,d){var e=Qb(+d);c={parent:null,Cf:{vg:"fake"},qf:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();g.FS_createPath=hc;g.FS_createDataFile=yb;g.FS_createPreloadedFile=zb;g.FS_unlink=Xb;g.FS_createLazyFile=lc;g.FS_createDevice=jc;for(var T,Z=0;32>Z;++Z)Rc.push(Array(Z));var Me=new Float32Array(288);for(Z=0;288>Z;++Z)nd[Z]=Me.subarray(0,Z+1);var Ne=new Int32Array(288);
for(Z=0;288>Z;++Z)od[Z]=Ne.subarray(0,Z+1);g.requestFullscreen=(a,b)=>Rd(a,b);g.requestAnimationFrame=a=>Wd(a);g.setCanvasSize=(a,b,c)=>ce(a,b,c);g.pauseMainLoop=()=>{wd=null;xd++};g.resumeMainLoop=()=>{xd++;var a=Ad,b=Bd,c=yd;yd=null;ee(c,0,!1,zd,!0);de(a,b);wd()};g.getUserMedia=()=>{window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};g.createContext=(a,b,c,d)=>Nd(a,b,c,d);
var Pe={a:(a,b,c,d)=>{l(`Assertion failed: ${a?D(r,a):""}, at: `+[b?b?D(r,b):"":"unknown filename",c,d?d?D(r,d):"":"unknown function"])},k:function(a,b,c){oc=c;try{var d=Qb(a);switch(b){case 0:var e=pc();if(0>e)return-28;for(;Db[e];)e++;return Rb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=pc(),d.flags|=e,0;case 5:return e=pc(),ua[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return u[Oe()>>2]=28,-1;default:return-28}}catch(f){if("undefined"==typeof K||
"ErrnoError"!==f.name)throw f;return-f.vf}},Qa:function(a,b){try{var c=Qb(a);return nc(Yb,c.path,b)}catch(d){if("undefined"==typeof K||"ErrnoError"!==d.name)throw d;return-d.vf}},Ua:function(a,b,c){oc=c;try{var d=Qb(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Df.Rg){b=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=pc();u[e>>2]=25856;u[e+4>>2]=5;u[e+8>>2]=191;u[e+12>>2]=35387;for(var f=0;32>f;f++)p[e+f+17>>0]=b[f]||0}return 0;
case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Df.Sg)for(e=pc(),b=[],f=0;32>f;f++)b.push(p[e+f+17>>0]);return 0;case 21519:if(!d.tty)return-59;e=pc();return u[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:e=pc();if(!d.rf.Qg)throw new G(59);return d.rf.Qg(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Df.Tg&&(f=[24,80],e=pc(),ua[e>>1]=f[0],ua[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if("undefined"==
typeof K||"ErrnoError"!==h.name)throw h;return-h.vf}},Oa:function(a,b){try{return a=a?D(r,a):"",nc(Zb,a,b)}catch(c){if("undefined"==typeof K||"ErrnoError"!==c.name)throw c;return-c.vf}},Ka:function(a,b,c){try{return b=b?D(r,b):"",b=mc(a,b),b=F(b),"/"===b[b.length-1]&&(b=b.substr(0,b.length-1)),J(b,c),0}catch(d){if("undefined"==typeof K||"ErrnoError"!==d.name)throw d;return-d.vf}},Na:function(a,b,c,d){try{b=b?D(r,b):"";var e=d&256;b=mc(a,b,d&4096);return nc(e?Zb:Yb,b,c)}catch(f){if("undefined"==typeof K||
"ErrnoError"!==f.name)throw f;return-f.vf}},Va:function(a,b,c,d){oc=d;try{b=b?D(r,b):"";b=mc(a,b);var e=d?pc():0;return ac(b,c,e).fd}catch(f){if("undefined"==typeof K||"ErrnoError"!==f.name)throw f;return-f.vf}},Pa:function(a,b){try{return a=a?D(r,a):"",nc(Yb,a,b)}catch(c){if("undefined"==typeof K||"ErrnoError"!==c.name)throw c;return-c.vf}},Wa:()=>!0,i:()=>{l("")},Ha:(a,b,c)=>{b=rc(b,c);return Ta[a].apply(null,b)},b:(a,b,c)=>{b=rc(b,c);return Ta[a].apply(null,b)},l:()=>Date.now(),f:sc,ka:function(a){T.activeTexture(a)},
ja:(a,b)=>{T.attachShader(L[a],M[b])},Oc:(a,b)=>{T.beginQuery(a,N[b])},Ba:(a,b)=>{T.yf.beginQueryEXT(a,N[b])},tc:function(a){T.beginTransformFeedback(a)},ia:(a,b,c)=>{T.bindAttribLocation(L[a],b,c?D(r,c):"")},ha:(a,b)=>{35051==a?T.$f=b:35052==a&&(T.zf=b);T.bindBuffer(a,xc[b])},qc:(a,b,c)=>{T.bindBufferBase(a,b,xc[c])},rc:(a,b,c,d,e)=>{T.bindBufferRange(a,b,xc[c],d,e)},fa:(a,b)=>{T.bindFramebuffer(a,yc[b])},ea:(a,b)=>{T.bindRenderbuffer(a,zc[b])},tb:(a,b)=>{T.bindSampler(a,P[b])},da:(a,b)=>{T.bindTexture(a,
Ac[b])},lb:(a,b)=>{T.bindTransformFeedback(a,Dc[b])},yc:Oc,ta:Oc,ca:function(a,b,c,d){T.blendColor(a,b,c,d)},ba:function(a){T.blendEquation(a)},aa:function(a,b){T.blendEquationSeparate(a,b)},$:function(a,b){T.blendFunc(a,b)},_:function(a,b,c,d){T.blendFuncSeparate(a,b,c,d)},Cc:function(a,b,c,d,e,f,h,m,n,q){T.blitFramebuffer(a,b,c,d,e,f,h,m,n,q)},Z:(a,b,c,d)=>{2<=S.version?c&&b?T.bufferData(a,r,d,c,b):T.bufferData(a,b,d):T.bufferData(a,c?r.subarray(c,c+b):b,d)},Y:(a,b,c,d)=>{2<=S.version?c&&T.bufferSubData(a,
b,r,d,c):T.bufferSubData(a,b,r.subarray(d,d+c))},W:function(a){return T.checkFramebufferStatus(a)},V:function(a){T.clear(a)},Sb:function(a,b,c,d){T.clearBufferfi(a,b,c,d)},Tb:(a,b,c)=>{T.clearBufferfv(a,b,y,c>>2)},Wb:(a,b,c)=>{T.clearBufferiv(a,b,u,c>>2)},Vb:(a,b,c)=>{T.clearBufferuiv(a,b,x,c>>2)},U:function(a,b,c,d){T.clearColor(a,b,c,d)},T:function(a){T.clearDepth(a)},S:function(a){T.clearStencil(a)},Db:(a,b,c,d)=>T.clientWaitSync(Ec[a],b,(c>>>0)+4294967296*d),R:(a,b,c,d)=>{T.colorMask(!!a,!!b,
!!c,!!d)},Q:a=>{T.compileShader(M[a])},P:(a,b,c,d,e,f,h,m)=>{2<=S.version?T.zf||!h?T.compressedTexImage2D(a,b,c,d,e,f,h,m):T.compressedTexImage2D(a,b,c,d,e,f,r,m,h):T.compressedTexImage2D(a,b,c,d,e,f,m?r.subarray(m,m+h):null)},Tc:(a,b,c,d,e,f,h,m,n)=>{T.zf?T.compressedTexImage3D(a,b,c,d,e,f,h,m,n):T.compressedTexImage3D(a,b,c,d,e,f,h,r,n,m)},O:(a,b,c,d,e,f,h,m,n)=>{2<=S.version?T.zf||!m?T.compressedTexSubImage2D(a,b,c,d,e,f,h,m,n):T.compressedTexSubImage2D(a,b,c,d,e,f,h,r,n,m):T.compressedTexSubImage2D(a,
b,c,d,e,f,h,n?r.subarray(n,n+m):null)},Sc:(a,b,c,d,e,f,h,m,n,q,t)=>{T.zf?T.compressedTexSubImage3D(a,b,c,d,e,f,h,m,n,q,t):T.compressedTexSubImage3D(a,b,c,d,e,f,h,m,n,r,t,q)},Qb:function(a,b,c,d,e){T.copyBufferSubData(a,b,c,d,e)},N:function(a,b,c,d,e,f,h,m){T.copyTexImage2D(a,b,c,d,e,f,h,m)},L:function(a,b,c,d,e,f,h,m){T.copyTexSubImage2D(a,b,c,d,e,f,h,m)},Uc:function(a,b,c,d,e,f,h,m,n){T.copyTexSubImage3D(a,b,c,d,e,f,h,m,n)},K:()=>{var a=Jc(L),b=T.createProgram();b.name=a;b.Sf=b.Qf=b.Rf=0;b.kg=1;
L[a]=b;return a},J:a=>{var b=Jc(M);M[b]=T.createShader(a);return b},I:function(a){T.cullFace(a)},H:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=xc[d];e&&(T.deleteBuffer(e),e.name=0,xc[d]=null,d==T.$f&&(T.$f=0),d==T.zf&&(T.zf=0))}},G:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=yc[d];e&&(T.deleteFramebuffer(e),e.name=0,yc[d]=null)}},F:a=>{if(a){var b=L[a];b?(T.deleteProgram(b),b.name=0,L[a]=null):Q(1281)}},Qc:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=N[d];e&&(T.deleteQuery(e),N[d]=null)}},
Da:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=N[d];e&&(T.yf.deleteQueryEXT(e),N[d]=null)}},E:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=zc[d];e&&(T.deleteRenderbuffer(e),e.name=0,zc[d]=null)}},vb:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=P[d];e&&(T.deleteSampler(e),e.name=0,P[d]=null)}},D:a=>{if(a){var b=M[a];b?(T.deleteShader(b),M[a]=null):Q(1281)}},Eb:a=>{if(a){var b=Ec[a];b?(T.deleteSync(b),b.name=0,Ec[a]=null):Q(1281)}},C:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Ac[d];
e&&(T.deleteTexture(e),e.name=0,Ac[d]=null)}},kb:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Dc[d];e&&(T.deleteTransformFeedback(e),e.name=0,Dc[d]=null)}},xc:Pc,sa:Pc,A:function(a){T.depthFunc(a)},z:a=>{T.depthMask(!!a)},y:function(a,b){T.depthRange(a,b)},x:(a,b)=>{T.detachShader(L[a],M[b])},w:function(a){T.disable(a)},v:a=>{T.disableVertexAttribArray(a)},u:(a,b,c)=>{T.drawArrays(a,b,c)},Ib:Qc,na:Qc,cd:Qc,dd:Qc,Xa:Qc,Jc:Sc,_c:Sc,oa:Sc,t:(a,b,c,d)=>{T.drawElements(a,b,c,d)},Hb:Tc,ma:Tc,$c:Tc,
ad:Tc,bd:Tc,Yc:(a,b,c,d,e,f)=>{T.drawElements(a,d,e,f)},s:function(a){T.enable(a)},r:a=>{T.enableVertexAttribArray(a)},Nc:function(a){T.endQuery(a)},Aa:a=>{T.yf.endQueryEXT(a)},sc:function(){T.endTransformFeedback()},Gb:(a,b)=>(a=T.fenceSync(a,b))?(b=Jc(Ec),a.name=b,Ec[b]=a,b):0,cf:function(){T.finish()},bf:function(){T.flush()},af:(a,b,c,d)=>{T.framebufferRenderbuffer(a,b,c,zc[d])},$e:(a,b,c,d,e)=>{T.framebufferTexture2D(a,b,c,Ac[d],e)},Ac:(a,b,c,d,e)=>{T.framebufferTextureLayer(a,b,Ac[c],d,e)},
_e:function(a){T.frontFace(a)},Ze:(a,b)=>{Uc(a,b,"createBuffer",xc)},Xe:(a,b)=>{Uc(a,b,"createFramebuffer",yc)},Rc:(a,b)=>{Uc(a,b,"createQuery",N)},Ea:(a,b)=>{for(var c=0;c<a;c++){var d=T.yf.createQueryEXT();if(!d){for(Q(1282);c<a;)u[b+4*c++>>2]=0;break}var e=Jc(N);d.name=e;N[e]=d;u[b+4*c>>2]=e}},We:(a,b)=>{Uc(a,b,"createRenderbuffer",zc)},wb:(a,b)=>{Uc(a,b,"createSampler",P)},Ve:(a,b)=>{Uc(a,b,"createTexture",Ac)},jb:(a,b)=>{Uc(a,b,"createTransformFeedback",Dc)},wc:Vc,qa:Vc,Ye:function(a){T.generateMipmap(a)},
Ue:(a,b,c,d,e,f,h)=>{Wc("getActiveAttrib",a,b,c,d,e,f,h)},Te:(a,b,c,d,e,f,h)=>{Wc("getActiveUniform",a,b,c,d,e,f,h)},Lb:(a,b,c,d,e)=>{a=L[a];if(a=T.getActiveUniformBlockName(a,b))e&&0<c?(c=gb(a,r,e,c),d&&(u[d>>2]=c)):d&&(u[d>>2]=0)},Mb:(a,b,c,d)=>{if(d)if(a=L[a],35393==c)u[d>>2]=T.getActiveUniformBlockName(a,b).length+1;else{if(a=T.getActiveUniformBlockParameter(a,b,c),null!==a)if(35395==c)for(c=0;c<a.length;c++)u[d+4*c>>2]=a[c];else u[d>>2]=a}else Q(1281)},Ob:(a,b,c,d,e)=>{if(e)if(0<b&&0==c)Q(1281);
else{a=L[a];for(var f=[],h=0;h<b;h++)f.push(u[c+4*h>>2]);if(a=T.getActiveUniforms(a,f,d))for(b=a.length,h=0;h<b;h++)u[e+4*h>>2]=a[h]}else Q(1281)},Se:(a,b,c,d)=>{a=T.getAttachedShaders(L[a]);var e=a.length;e>b&&(e=b);u[c>>2]=e;for(b=0;b<e;++b)u[d+4*b>>2]=M.indexOf(a[b])},Re:(a,b)=>T.getAttribLocation(L[a],b?D(r,b):""),Qe:(a,b)=>{Yc(a,b,4)},xb:(a,b,c)=>{c?Xc(c,T.getBufferParameter(a,b)):Q(1281)},Pe:(a,b,c)=>{c?u[c>>2]=T.getBufferParameter(a,b):Q(1281)},Oe:()=>{var a=T.getError()||Ic;Ic=0;return a},
Ne:(a,b)=>{Yc(a,b,2)},ec:(a,b)=>T.getFragDataLocation(L[a],b?D(r,b):""),Me:(a,b,c,d)=>{a=T.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;u[d>>2]=a},zb:(a,b,c)=>Zc(a,b,c,1),Bb:(a,b)=>{Yc(a,b,1)},uc:(a,b,c)=>Zc(a,b,c,0),Le:(a,b)=>{Yc(a,b,0)},Za:(a,b,c,d,e)=>{if(0>d)Q(1281);else if(e){if(a=T.getInternalformatParameter(a,b,c),null!==a)for(b=0;b<a.length&&b<d;++b)u[e+4*b>>2]=a[b]}else Q(1281)},fb:()=>{Q(1282)},Ie:(a,b,c,d)=>{a=T.getProgramInfoLog(L[a]);
null===a&&(a="(unknown error)");b=0<b&&d?gb(a,r,d,b):0;c&&(u[c>>2]=b)},Je:(a,b,c)=>{if(c)if(a>=wc)Q(1281);else if(a=L[a],35716==b)a=T.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.Sf)for(b=0;b<T.getProgramParameter(a,35718);++b)a.Sf=Math.max(a.Sf,T.getActiveUniform(a,b).name.length+1);u[c>>2]=a.Sf}else if(35722==b){if(!a.Qf)for(b=0;b<T.getProgramParameter(a,35721);++b)a.Qf=Math.max(a.Qf,T.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.Qf}else if(35381==
b){if(!a.Rf)for(b=0;b<T.getProgramParameter(a,35382);++b)a.Rf=Math.max(a.Rf,T.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.Rf}else u[c>>2]=T.getProgramParameter(a,b);else Q(1281)},va:$c,xa:ad,ua:$c,Lc:(a,b,c)=>{if(c){a=T.getQueryParameter(N[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else Q(1281)},wa:ad,Mc:(a,b,c)=>{c?u[c>>2]=T.getQuery(a,b):Q(1281)},ya:(a,b,c)=>{c?u[c>>2]=T.yf.getQueryEXT(a,b):Q(1281)},He:(a,b,c)=>{c?u[c>>2]=T.getRenderbufferParameter(a,b):Q(1281)},nb:(a,b,c)=>{c?
y[c>>2]=T.getSamplerParameter(P[a],b):Q(1281)},ob:(a,b,c)=>{c?u[c>>2]=T.getSamplerParameter(P[a],b):Q(1281)},Fe:(a,b,c,d)=>{a=T.getShaderInfoLog(M[a]);null===a&&(a="(unknown error)");b=0<b&&d?gb(a,r,d,b):0;c&&(u[c>>2]=b)},Ee:(a,b,c,d)=>{a=T.getShaderPrecisionFormat(a,b);u[c>>2]=a.rangeMin;u[c+4>>2]=a.rangeMax;u[d>>2]=a.precision},De:(a,b,c,d)=>{if(a=T.getShaderSource(M[a]))b=0<b&&d?gb(a,r,d,b):0,c&&(u[c>>2]=b)},Ge:(a,b,c)=>{c?35716==b?(a=T.getShaderInfoLog(M[a]),null===a&&(a="(unknown error)"),u[c>>
2]=a?a.length+1:0):35720==b?(a=T.getShaderSource(M[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=T.getShaderParameter(M[a],b):Q(1281)},Ce:dd,Rb:(a,b)=>{if(2>S.version)return Q(1282),0;var c=Gc[a];if(c)return 0>b||b>=c.length?(Q(1281),0):c[b];switch(a){case 7939:return c=T.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return cd(d)}),c=Gc[a]=c,0>b||b>=c.length?(Q(1281),0):c[b];default:return Q(1280),0}},Ab:(a,b,c,d,e)=>{0>c?Q(1281):e?(a=T.getSyncParameter(Ec[a],
b),null!==a&&(u[e>>2]=a,d&&(u[d>>2]=1))):Q(1281)},Be:(a,b,c)=>{c?y[c>>2]=T.getTexParameter(a,b):Q(1281)},Ae:(a,b,c)=>{c?u[c>>2]=T.getTexParameter(a,b):Q(1281)},nc:(a,b,c,d,e,f,h)=>{a=L[a];if(a=T.getTransformFeedbackVarying(a,b))h&&0<c?(c=gb(a.name,r,h,c),d&&(u[d>>2]=c)):d&&(u[d>>2]=0),e&&(u[e>>2]=a.size),f&&(u[f>>2]=a.type)},Nb:(a,b)=>T.getUniformBlockIndex(L[a],b?D(r,b):""),Pb:(a,b,c,d)=>{if(d)if(0<b&&(0==c||0==d))Q(1281);else{a=L[a];for(var e=[],f=0;f<b;f++)e.push(Ya(u[c+4*f>>2]));if(a=T.getUniformIndices(a,
e))for(b=a.length,f=0;f<b;f++)u[d+4*f>>2]=a[f]}else Q(1281)},we:(a,b)=>{b=b?D(r,b):"";if(a=L[a]){fd(a);var c=a.Lf,d=0,e=b,f=ed(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Dg[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||T.getUniformLocation(a,b)))return d}else Q(1281);return-1},ye:(a,b,c)=>{gd(a,b,c,2)},xe:(a,b,c)=>{gd(a,b,c,0)},fc:(a,b,c)=>gd(a,b,c,0),lc:jd,kc:jd,te:(a,b,c)=>{c?u[c>>2]=T.getVertexAttribOffset(a,b):Q(1281)},ve:(a,b,c)=>{hd(a,b,c,2)},ue:(a,b,c)=>{hd(a,b,c,5)},se:function(a,b){T.hint(a,
b)},bb:(a,b,c)=>{for(var d=Rc[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];T.invalidateFramebuffer(a,d)},ab:(a,b,c,d,e,f,h)=>{for(var m=Rc[b],n=0;n<b;n++)m[n]=u[c+4*n>>2];T.invalidateSubFramebuffer(a,m,d,e,f,h)},re:a=>(a=xc[a])?T.isBuffer(a):0,qe:function(a){return T.isEnabled(a)},pe:a=>(a=yc[a])?T.isFramebuffer(a):0,oe:a=>(a=L[a])?T.isProgram(a):0,Pc:a=>(a=N[a])?T.isQuery(a):0,Ca:a=>(a=N[a])?T.yf.isQueryEXT(a):0,ne:a=>(a=zc[a])?T.isRenderbuffer(a):0,ub:a=>(a=P[a])?T.isSampler(a):0,me:a=>(a=M[a])?T.isShader(a):
0,Fb:a=>T.isSync(Ec[a]),le:a=>(a=Ac[a])?T.isTexture(a):0,ib:a=>T.isTransformFeedback(Dc[a]),vc:kd,pa:kd,ke:function(a){T.lineWidth(a)},je:a=>{a=L[a];T.linkProgram(a);a.Lf=0;a.Dg={}},hb:function(){T.pauseTransformFeedback()},ie:(a,b)=>{3317==a&&(Hc=b);T.pixelStorei(a,b)},he:function(a,b){T.polygonOffset(a,b)},eb:()=>{Q(1280)},cb:()=>{Q(1280)},za:(a,b)=>{T.yf.queryCounterEXT(N[a],b)},Zc:function(a){T.readBuffer(a)},ge:(a,b,c,d,e,f,h)=>{if(2<=S.version)if(T.$f)T.readPixels(a,b,c,d,e,f,h);else{var m=
ld(f);T.readPixels(a,b,c,d,e,f,m,h>>31-Math.clz32(m.BYTES_PER_ELEMENT))}else(h=md(f,e,c,d,h))?T.readPixels(a,b,c,d,e,f,h):Q(1280)},fe:()=>{},de:function(a,b,c,d){T.renderbufferStorage(a,b,c,d)},Bc:function(a,b,c,d,e){T.renderbufferStorageMultisample(a,b,c,d,e)},gb:function(){T.resumeTransformFeedback()},ce:(a,b)=>{T.sampleCoverage(a,!!b)},qb:(a,b,c)=>{T.samplerParameterf(P[a],b,c)},pb:(a,b,c)=>{T.samplerParameterf(P[a],b,y[c>>2])},sb:(a,b,c)=>{T.samplerParameteri(P[a],b,c)},rb:(a,b,c)=>{T.samplerParameteri(P[a],
b,u[c>>2])},be:function(a,b,c,d){T.scissor(a,b,c,d)},ae:()=>{Q(1280)},$d:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var h=d?u[d+4*f>>2]:-1;e+=Ya(u[c+4*f>>2],0>h?void 0:h)}T.shaderSource(M[a],e)},_d:function(a,b,c){T.stencilFunc(a,b,c)},Zd:function(a,b,c,d){T.stencilFuncSeparate(a,b,c,d)},Yd:function(a){T.stencilMask(a)},Xd:function(a,b){T.stencilMaskSeparate(a,b)},Wd:function(a,b,c){T.stencilOp(a,b,c)},Ud:function(a,b,c,d){T.stencilOpSeparate(a,b,c,d)},Td:(a,b,c,d,e,f,h,m,n)=>{if(2<=S.version)if(T.zf)T.texImage2D(a,
b,c,d,e,f,h,m,n);else if(n){var q=ld(m);T.texImage2D(a,b,c,d,e,f,h,m,q,n>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else T.texImage2D(a,b,c,d,e,f,h,m,null);else T.texImage2D(a,b,c,d,e,f,h,m,n?md(m,h,d,e,n):null)},Xc:(a,b,c,d,e,f,h,m,n,q)=>{if(T.zf)T.texImage3D(a,b,c,d,e,f,h,m,n,q);else if(q){var t=ld(n);T.texImage3D(a,b,c,d,e,f,h,m,n,t,q>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else T.texImage3D(a,b,c,d,e,f,h,m,n,null)},Sd:function(a,b,c){T.texParameterf(a,b,c)},Rd:(a,b,c)=>{T.texParameterf(a,b,y[c>>2])},Qd:function(a,
b,c){T.texParameteri(a,b,c)},Pd:(a,b,c)=>{T.texParameteri(a,b,u[c>>2])},$a:function(a,b,c,d,e){T.texStorage2D(a,b,c,d,e)},_a:function(a,b,c,d,e,f){T.texStorage3D(a,b,c,d,e,f)},Od:(a,b,c,d,e,f,h,m,n)=>{if(2<=S.version)if(T.zf)T.texSubImage2D(a,b,c,d,e,f,h,m,n);else if(n){var q=ld(m);T.texSubImage2D(a,b,c,d,e,f,h,m,q,n>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else T.texSubImage2D(a,b,c,d,e,f,h,m,null);else q=null,n&&(q=md(m,h,e,f,n)),T.texSubImage2D(a,b,c,d,e,f,h,m,q)},Wc:(a,b,c,d,e,f,h,m,n,q,t)=>{if(T.zf)T.texSubImage3D(a,
b,c,d,e,f,h,m,n,q,t);else if(t){var v=ld(q);T.texSubImage3D(a,b,c,d,e,f,h,m,n,q,v,t>>31-Math.clz32(v.BYTES_PER_ELEMENT))}else T.texSubImage3D(a,b,c,d,e,f,h,m,n,q,null)},pc:(a,b,c,d)=>{a=L[a];for(var e=[],f=0;f<b;f++)e.push(Ya(u[c+4*f>>2]));T.transformFeedbackVaryings(a,e,d)},Nd:(a,b)=>{T.uniform1f(U(a),b)},Md:(a,b,c)=>{if(2<=S.version)b&&T.uniform1fv(U(a),y,c>>2,b);else{if(288>=b)for(var d=nd[b-1],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);T.uniform1fv(U(a),d)}},Ld:(a,b)=>{T.uniform1i(U(a),
b)},Jd:(a,b,c)=>{if(2<=S.version)b&&T.uniform1iv(U(a),u,c>>2,b);else{if(288>=b)for(var d=od[b-1],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);T.uniform1iv(U(a),d)}},cc:(a,b)=>{T.uniform1ui(U(a),b)},_b:(a,b,c)=>{b&&T.uniform1uiv(U(a),x,c>>2,b)},Id:(a,b,c)=>{T.uniform2f(U(a),b,c)},Hd:(a,b,c)=>{if(2<=S.version)b&&T.uniform2fv(U(a),y,c>>2,2*b);else{if(144>=b)for(var d=nd[2*b-1],e=0;e<2*b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=y.subarray(c>>2,c+8*b>>2);T.uniform2fv(U(a),d)}},
Gd:(a,b,c)=>{T.uniform2i(U(a),b,c)},Fd:(a,b,c)=>{if(2<=S.version)b&&T.uniform2iv(U(a),u,c>>2,2*b);else{if(144>=b)for(var d=od[2*b-1],e=0;e<2*b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2];else d=u.subarray(c>>2,c+8*b>>2);T.uniform2iv(U(a),d)}},bc:(a,b,c)=>{T.uniform2ui(U(a),b,c)},Zb:(a,b,c)=>{b&&T.uniform2uiv(U(a),x,c>>2,2*b)},Ed:(a,b,c,d)=>{T.uniform3f(U(a),b,c,d)},Dd:(a,b,c)=>{if(2<=S.version)b&&T.uniform3fv(U(a),y,c>>2,3*b);else{if(96>=b)for(var d=nd[3*b-1],e=0;e<3*b;e+=3)d[e]=y[c+4*e>>2],d[e+
1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>2,c+12*b>>2);T.uniform3fv(U(a),d)}},Cd:(a,b,c,d)=>{T.uniform3i(U(a),b,c,d)},Bd:(a,b,c)=>{if(2<=S.version)b&&T.uniform3iv(U(a),u,c>>2,3*b);else{if(96>=b)for(var d=od[3*b-1],e=0;e<3*b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2];else d=u.subarray(c>>2,c+12*b>>2);T.uniform3iv(U(a),d)}},ac:(a,b,c,d)=>{T.uniform3ui(U(a),b,c,d)},Yb:(a,b,c)=>{b&&T.uniform3uiv(U(a),x,c>>2,3*b)},Ad:(a,b,c,d,e)=>{T.uniform4f(U(a),b,c,d,e)},
yd:(a,b,c)=>{if(2<=S.version)b&&T.uniform4fv(U(a),y,c>>2,4*b);else{if(72>=b){var d=nd[4*b-1],e=y;c>>=2;for(var f=0;f<4*b;f+=4){var h=c+f;d[f]=e[h];d[f+1]=e[h+1];d[f+2]=e[h+2];d[f+3]=e[h+3]}}else d=y.subarray(c>>2,c+16*b>>2);T.uniform4fv(U(a),d)}},xd:(a,b,c,d,e)=>{T.uniform4i(U(a),b,c,d,e)},wd:(a,b,c)=>{if(2<=S.version)b&&T.uniform4iv(U(a),u,c>>2,4*b);else{if(72>=b)for(var d=od[4*b-1],e=0;e<4*b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2];else d=u.subarray(c>>
2,c+16*b>>2);T.uniform4iv(U(a),d)}},$b:(a,b,c,d,e)=>{T.uniform4ui(U(a),b,c,d,e)},Xb:(a,b,c)=>{b&&T.uniform4uiv(U(a),x,c>>2,4*b)},Kb:(a,b,c)=>{a=L[a];T.uniformBlockBinding(a,b,c)},vd:(a,b,c,d)=>{if(2<=S.version)b&&T.uniformMatrix2fv(U(a),!!c,y,d>>2,4*b);else{if(72>=b)for(var e=nd[4*b-1],f=0;f<4*b;f+=4)e[f]=y[d+4*f>>2],e[f+1]=y[d+(4*f+4)>>2],e[f+2]=y[d+(4*f+8)>>2],e[f+3]=y[d+(4*f+12)>>2];else e=y.subarray(d>>2,d+16*b>>2);T.uniformMatrix2fv(U(a),!!c,e)}},Ic:(a,b,c,d)=>{b&&T.uniformMatrix2x3fv(U(a),!!c,
y,d>>2,6*b)},Gc:(a,b,c,d)=>{b&&T.uniformMatrix2x4fv(U(a),!!c,y,d>>2,8*b)},ud:(a,b,c,d)=>{if(2<=S.version)b&&T.uniformMatrix3fv(U(a),!!c,y,d>>2,9*b);else{if(32>=b)for(var e=nd[9*b-1],f=0;f<9*b;f+=9)e[f]=y[d+4*f>>2],e[f+1]=y[d+(4*f+4)>>2],e[f+2]=y[d+(4*f+8)>>2],e[f+3]=y[d+(4*f+12)>>2],e[f+4]=y[d+(4*f+16)>>2],e[f+5]=y[d+(4*f+20)>>2],e[f+6]=y[d+(4*f+24)>>2],e[f+7]=y[d+(4*f+28)>>2],e[f+8]=y[d+(4*f+32)>>2];else e=y.subarray(d>>2,d+36*b>>2);T.uniformMatrix3fv(U(a),!!c,e)}},Hc:(a,b,c,d)=>{b&&T.uniformMatrix3x2fv(U(a),
!!c,y,d>>2,6*b)},Ec:(a,b,c,d)=>{b&&T.uniformMatrix3x4fv(U(a),!!c,y,d>>2,12*b)},td:(a,b,c,d)=>{if(2<=S.version)b&&T.uniformMatrix4fv(U(a),!!c,y,d>>2,16*b);else{if(18>=b){var e=nd[16*b-1],f=y;d>>=2;for(var h=0;h<16*b;h+=16){var m=d+h;e[h]=f[m];e[h+1]=f[m+1];e[h+2]=f[m+2];e[h+3]=f[m+3];e[h+4]=f[m+4];e[h+5]=f[m+5];e[h+6]=f[m+6];e[h+7]=f[m+7];e[h+8]=f[m+8];e[h+9]=f[m+9];e[h+10]=f[m+10];e[h+11]=f[m+11];e[h+12]=f[m+12];e[h+13]=f[m+13];e[h+14]=f[m+14];e[h+15]=f[m+15]}}else e=y.subarray(d>>2,d+64*b>>2);T.uniformMatrix4fv(U(a),
!!c,e)}},Fc:(a,b,c,d)=>{b&&T.uniformMatrix4x2fv(U(a),!!c,y,d>>2,8*b)},Dc:(a,b,c,d)=>{b&&T.uniformMatrix4x3fv(U(a),!!c,y,d>>2,12*b)},sd:a=>{a=L[a];T.useProgram(a);T.Mg=a},rd:a=>{T.validateProgram(L[a])},qd:function(a,b){T.vertexAttrib1f(a,b)},pd:(a,b)=>{T.vertexAttrib1f(a,y[b>>2])},od:function(a,b,c){T.vertexAttrib2f(a,b,c)},nd:(a,b)=>{T.vertexAttrib2f(a,y[b>>2],y[b+4>>2])},md:function(a,b,c,d){T.vertexAttrib3f(a,b,c,d)},ld:(a,b)=>{T.vertexAttrib3f(a,y[b>>2],y[b+4>>2],y[b+8>>2])},kd:function(a,b,c,
d,e){T.vertexAttrib4f(a,b,c,d,e)},jd:(a,b)=>{T.vertexAttrib4f(a,y[b>>2],y[b+4>>2],y[b+8>>2],y[b+12>>2])},mb:pd,la:pd,fd:pd,gd:pd,Ya:pd,jc:function(a,b,c,d,e){T.vertexAttribI4i(a,b,c,d,e)},hc:(a,b)=>{T.vertexAttribI4i(a,u[b>>2],u[b+4>>2],u[b+8>>2],u[b+12>>2])},ic:function(a,b,c,d,e){T.vertexAttribI4ui(a,b,c,d,e)},gc:(a,b)=>{T.vertexAttribI4ui(a,x[b>>2],x[b+4>>2],x[b+8>>2],x[b+12>>2])},mc:(a,b,c,d,e)=>{T.vertexAttribIPointer(a,b,c,d,e)},id:(a,b,c,d,e,f)=>{T.vertexAttribPointer(a,b,c,!!d,e,f)},hd:function(a,
b,c,d){T.viewport(a,b,c,d)},Cb:(a,b,c,d)=>{T.waitSync(Ec[a],b,(c>>>0)+4294967296*d)},Ga:()=>0,Ra:(a,b,c)=>r.copyWithin(a,b,b+c),Ja:a=>{var b=r.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-ra.buffer.byteLength+65535)/65536;try{ra.grow(e);xa();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},ra:(a,b,c)=>{a=C(a);ee(a,b,c)},Fa:()=>{throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";
},La:(a,b)=>{var c=0;he().forEach((d,e)=>{var f=b+c;e=x[a+4*e>>2]=f;for(f=0;f<d.length;++f)p[e++>>0]=d.charCodeAt(f);p[e>>0]=0;c+=d.length+1});return 0},Ma:(a,b)=>{var c=he();x[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);x[b>>2]=d;return 0},q:sd,j:function(a){try{var b=Qb(a);cc(b);return 0}catch(c){if("undefined"==typeof K||"ErrnoError"!==c.name)throw c;return c.vf}},Ta:function(a,b,c,d){try{a:{var e=Qb(a);a=b;for(var f,h=b=0;h<c;h++){var m=x[a>>2],n=x[a+4>>2];a+=8;var q=e,t=m,v=n,w=f,z=p;
if(0>v||0>w)throw new G(28);if(null===q.fd)throw new G(8);if(1===(q.flags&2097155))throw new G(8);if(16384===(q.node.mode&61440))throw new G(31);if(!q.rf.read)throw new G(28);var E="undefined"!=typeof w;if(!E)w=q.position;else if(!q.seekable)throw new G(70);var H=q.rf.read(q,z,t,v,w);E||(q.position+=H);var O=H;if(0>O){var W=-1;break a}b+=O;if(O<n)break;"undefined"!==typeof f&&(f+=O)}W=b}x[d>>2]=W;return 0}catch(fa){if("undefined"==typeof K||"ErrnoError"!==fa.name)throw fa;return fa.vf}},Ia:function(a,
b,c,d,e){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var f=Qb(a);dc(f,b,d);B=[f.position>>>0,(A=f.position,1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];u[e>>2]=B[0];u[e+4>>2]=B[1];f.eg&&0===b&&0===d&&(f.eg=null);return 0}catch(h){if("undefined"==typeof K||"ErrnoError"!==h.name)throw h;return h.vf}},Sa:function(a,b,c,d){try{a:{var e=Qb(a);a=b;for(var f,h=b=0;h<c;h++){var m=x[a>>2],n=x[a+4>>2];a+=8;var q=ec(e,p,
m,n,f);if(0>q){var t=-1;break a}b+=q;"undefined"!==typeof f&&(f+=q)}t=b}x[d>>2]=t;return 0}catch(v){if("undefined"==typeof K||"ErrnoError"!==v.name)throw v;return v.vf}},e:()=>{},Ke:(a,b,c,d)=>{var e;for(e=0;e<V.length&&null!==V[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var f=e+1;if(0>=a||0>=b)f=0;else{d?Rd():ce(a,b);for(e=0;e<V.length&&null==V[e];e++);var h=0<je[139265];e==V.length&&(h?g.Ff=Nd(g.canvas,!0,!0,{antialias:1<je[135181],depth:0<je[135173],stencil:0<
je[135174],alpha:0<je[135172]}):wb());!g.Ff&&h?f=0:(a=new ie(f,a,b,c,d),f-1==V.length?V.push(a):V[f-1]=a,Y=a,f=a.id)}return f},df:()=>{je=ne},d:()=>{},Jb:a=>{a:{if(a=X(a)){a.Eg&&C(a.Eg)(a.id);V[a.id-1]=null;Y.id==a.id&&(Y=null);for(a=0;a<V.length;a++)if(null!==V[a]){a=void 0;break a}g.Ff=void 0}a=void 0}return a},p:a=>{me||(me=Ya(dd(7939)).split(" "));return me.includes(a)?1:me.includes("GL_"+a)},h:(a,b,c)=>{wa[b>>3]=Xd;wa[c>>3]=Yd},o:(a,b,c)=>{var d=0,e=0;if(a=X(a))d=a.width,e=a.height;b&&(u[b>>
2]=d);c&&(u[c>>2]=e)},Kd:(a,b,c)=>{u[b>>2]=0;u[c>>2]=0},ee:()=>1,Vd:()=>0,n:a=>(a=X(a))?a.Wg:0,db:(a,b,c)=>{var d=0,e=0;if(a=X(a))d=a.width,e=a.height;b&&(u[b>>2]=d);c&&(u[c>>2]=e)},B:()=>{if(V)return 1;sc();je=ne;V=[];Y=null;le="number"==typeof devicePixelRatio&&devicePixelRatio||1;window.addEventListener("gamepadconnected",te,!0);window.addEventListener("gamepaddisconnected",ue,!0);window.addEventListener("keydown",ve,!0);window.addEventListener("keypress",qe,!0);window.addEventListener("keyup",
we,!0);window.addEventListener("blur",xe,!0);(function b(){window.matchMedia("(resolution: "+window.devicePixelRatio+"dppx)").addEventListener("change",b,{once:!0});le="number"==typeof devicePixelRatio&&devicePixelRatio||1;Y&&Y.Fg&&C(Y.Fg)(Y.id,le,le)})();g.canvas.addEventListener("touchmove",ye,!0);g.canvas.addEventListener("touchstart",Ce,!0);g.canvas.addEventListener("touchcancel",De,!0);g.canvas.addEventListener("touchend",De,!0);g.canvas.addEventListener("mousemove",ye,!0);g.canvas.addEventListener("mousedown",
Ce,!0);g.canvas.addEventListener("mouseup",De,!0);g.canvas.addEventListener("wheel",Ee,!0);g.canvas.addEventListener("mousewheel",Ee,!0);g.canvas.addEventListener("mouseenter",ze,!0);g.canvas.addEventListener("mouseleave",Ae,!0);g.canvas.addEventListener("drop",Ke,!0);g.canvas.addEventListener("dragover",Le,!0);be.push((b,c)=>{if(Y){var d=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(Y.Ag=Y.x,Y.Bg=Y.y,Y.zg=Y.width,Y.yg=Y.height,Y.x=Y.y=0,Y.width=
screen.width,Y.height=screen.height,Y.dg=!0):1==Y.dg?(Y.x=Y.Ag,Y.y=Y.Bg,Y.width=Y.zg,Y.height=Y.yg,Y.dg=!1):Y.width!=b||Y.height!=c?(Y.width=b,Y.height=c):d=!1;d&&(ce(Y.width,Y.height,!0),Y&&Y.Hg&&C(Y.Hg)(Y.id,Y.width,Y.height),Y&&Y.Of&&C(Y.Of)(Y.id,Y.width,Y.height))}});return 1},ze:()=>{},ga:()=>{},m:()=>{},Kc:(a,b)=>{if(a=X(a)){var c=a.If;a.If=b;b=c}else b=null;return b},M:a=>{var b=ke;ke=a;return b},Vc:(a,b)=>{a=X(a);if(!a)return null;var c=a.Of;a.Of=b;return c},zc:(a,b)=>{if(a=X(a)){var c=a.Pf;
a.Pf=b;b=c}else b=null;return b},dc:(a,b)=>{if(a=X(a)){var c=a.Vf;a.Vf=b;b=c}else b=null;return b},oc:(a,b)=>{if(a=X(a)){var c=a.Wf;a.Wf=b;b=c}else b=null;return b},ed:()=>{},Ub:(a,b)=>{a=X(a);if(!a)return null;var c=a.Gg;a.Gg=b;return c},zd:(a,b,c)=>{if(a=X(a))a.x=b,a.y=c},X:()=>{},g:a=>{a=Math.abs(a);0==a?de(0,0):de(1,a)},yb:()=>{window.removeEventListener("gamepadconnected",te,!0);window.removeEventListener("gamepaddisconnected",ue,!0);window.removeEventListener("keydown",ve,!0);window.removeEventListener("keypress",
qe,!0);window.removeEventListener("keyup",we,!0);window.removeEventListener("blur",xe,!0);g.canvas.removeEventListener("touchmove",ye,!0);g.canvas.removeEventListener("touchstart",Ce,!0);g.canvas.removeEventListener("touchcancel",De,!0);g.canvas.removeEventListener("touchend",De,!0);g.canvas.removeEventListener("mousemove",ye,!0);g.canvas.removeEventListener("mousedown",Ce,!0);g.canvas.removeEventListener("mouseup",De,!0);g.canvas.removeEventListener("wheel",Ee,!0);g.canvas.removeEventListener("mousewheel",
Ee,!0);g.canvas.removeEventListener("mouseenter",ze,!0);g.canvas.removeEventListener("mouseleave",Ae,!0);g.canvas.removeEventListener("drop",Ke,!0);g.canvas.removeEventListener("dragover",Le,!0);g.canvas.width=g.canvas.height=1;Y=V=null},c:(a,b)=>{je[a]=b}},Qe=function(){function a(c){Qe=c=c.exports;ra=Qe.ef;xa();ya=Qe.lf;Aa.unshift(Qe.ff);Ia("wasm-instantiate");return c}var b={a:Pe};Ha("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return k(`Module.instantiateWasm callback failed with error: ${c}`),
!1}Pa(b,function(c){a(c.instance)});return{}}(),Je=a=>(Je=Qe.gf)(a),bd=a=>(bd=Qe.hf)(a),Oe=()=>(Oe=Qe.jf)(),Re=g._main=(a,b,c)=>(Re=g._main=Qe.kf)(a,b,c),Se=a=>(Se=Qe.mf)(a);g.dynCall_jiji=(a,b,c,d,e)=>(g.dynCall_jiji=Qe.nf)(a,b,c,d,e);g.dynCall_ji=(a,b)=>(g.dynCall_ji=Qe.of)(a,b);g.addRunDependency=Ha;g.removeRunDependency=Ia;g.FS_createPath=hc;g.FS_createDataFile=yb;g.FS_createLazyFile=lc;g.FS_createDevice=jc;g.FS_unlink=Xb;g.FS_createPreloadedFile=zb;var Te;Ga=function Ue(){Te||Ve();Te||(Ga=Ue)};
function We(a=[]){var b=Re;a.unshift(ca);var c=a.length,d=Se(4*(c+1)),e=d;a.forEach(h=>{var m=x,n=e>>2,q=fb(h)+1,t=Se(q);gb(h,r,t,q);m[n]=t;e+=4});x[e>>2]=0;try{var f=b(c,d);sd(f,!0)}catch(h){qd(h)}}
function Ve(){var a=ba;function b(){if(!Te&&(Te=!0,g.calledRun=!0,!sa)){g.noFSInit||gc||(gc=!0,fc(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?jc("/dev","stdin",g.stdin):Wb("/dev/tty","/dev/stdin"),g.stdout?jc("/dev","stdout",null,g.stdout):Wb("/dev/tty","/dev/stdout"),g.stderr?jc("/dev","stderr",null,g.stderr):Wb("/dev/tty1","/dev/stderr"),ac("/dev/stdin",0),ac("/dev/stdout",1),ac("/dev/stderr",1));Gb=!1;Va(Aa);Va(Ba);if(g.onRuntimeInitialized)g.onRuntimeInitialized();Xe&&We(a);
if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();Ca.unshift(c)}Va(Ca)}}if(!(0<Ea)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Da();Va(za);0<Ea||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Xe=!0;
g.noInitialRun&&(Xe=!1);Ve();
